## GENERATED by src/nifler2/tools/gramcheck.nim -- do not edit.
## One proc per rule; the dispatch is an if-chain over
## (token kind, indentation class).

import parserrt
export parserrt

const
  Tk1 = {tkIf, tkIntLit, tkParLe, tkSymbol, tkWhile}
  Tk2 = {tkIf, tkIntLit, tkParLe, tkSemiColon, tkSymbol, tkWhile}

proc canSuffix*(p: Parser): bool
proc canSuffix*(p: Parser): bool =
  (((p.tok.kind in {tkParLe})) and noSpaceBefore(p)) or (((p.tok.kind in {tkBracketLe})) and noSpaceBefore(p)) or ((p.tok.kind in {tkDot}))

proc pModule*(p: var Parser)
proc pNotInd*(p: var Parser)
proc pStmt*(p: var Parser)
proc pBody*(p: var Parser)
proc pExprStmt*(p: var Parser)
proc pExpr*(p: var Parser; limit: int)
proc pPrimary*(p: var Parser)
proc pSuffix*(p: var Parser; anchor: int)
proc pAtom*(p: var Parser)

proc pModule*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1):
    let m1 = mark(p)
    pStmt p
    while (p.tok.kind in Tk1 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m2 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m2
      pStmt p
    if ((p.tok.kind in Tk2)) and indClass(p) == icGt:
      error p, "invalid indentation"
    discardUnused m1
  wrap p, m0, "stmts"
  discardUnused m0

proc pNotInd*(p: var Parser) =
  let m0 = mark(p)
  let m3 = mark(p)
  checkInd p, {icNoInd, icLt, icEq}
  discardUnused m3
  discardUnused m0

proc pStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkIf}):
    expect p, tkIf
    pExpr(p, -1)
    expect p, tkColon
    pBody p
    wrap p, m0, "if"
  elif (p.tok.kind in {tkWhile}):
    expect p, tkWhile
    pExpr(p, -1)
    expect p, tkColon
    pBody p
    wrap p, m0, "while"
  else:
    pExprStmt p
  discardUnused m0

proc pBody*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1 and indClass(p) in {icGt}):
    pushInd p
    let m4 = mark(p)
    pStmt p
    while (p.tok.kind in Tk1 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m5 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m5
      pStmt p
    if ((p.tok.kind in Tk2)) and indClass(p) == icGt:
      error p, "invalid indentation"
    discardUnused m4
    popInd p
  elif (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    pStmt p
  else:
    error p, "expected body"
  discardUnused m0

proc pExprStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkIntLit, tkParLe, tkSymbol}):
    pExpr(p, -1)
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pExpr(p, -1)
      wrap p, m0, "asgn"
    elif (p.tok.kind in {tkIntLit, tkParLe, tkSymbol}):
      pExpr(p, -1)
      while (p.tok.kind in {tkIntLit, tkParLe, tkSymbol}):
        let m6 = mark(p)
        pExpr(p, -1)
        discardUnused m6
      wrap p, m0, "cmd"
    else:
      discard
  else:
    error p, "expected exprStmt"
  discardUnused m0

proc pExpr*(p: var Parser; limit: int) =
  let m0 = mark(p)
  pPrimary p
  var prec = getPrecedence(p)
  while prec >= limit and indClass(p) == icNoInd:
    let assoc = (if isRightAssoc(p): 0 else: 1)
    insertLeafAt p, m0, p.tok.s
    getTok p
    pExpr(p, prec + assoc)
    wrap p, m0, "infix"
    prec = getPrecedence(p)
  discardUnused m0

proc pPrimary*(p: var Parser) =
  let m0 = mark(p)
  pAtom p
  while canSuffix(p):
    let m7 = mark(p)
    pSuffix(p, m0)
    discardUnused m7
  discardUnused m0

proc pSuffix*(p: var Parser; anchor: int) =
  let m0 = mark(p)
  if ((p.tok.kind in {tkBracketLe, tkParLe})) and noSpaceBefore(p):
    if (p.tok.kind in {tkParLe}):
      expect p, tkParLe
      if (p.tok.kind in {tkIntLit, tkParLe, tkSymbol}):
        let m8 = mark(p)
        pExpr(p, -1)
        while (p.tok.kind in {tkComma}):
          expect p, tkComma
          pExpr(p, -1)
        discardUnused m8
      expect p, tkParRi
      wrap p, anchor, "call"
    elif (p.tok.kind in {tkBracketLe}):
      expect p, tkBracketLe
      pExpr(p, -1)
      expect p, tkBracketRi
      wrap p, anchor, "at"
    else:
      error p, "expected suffix"
  elif (p.tok.kind in {tkDot}):
    expect p, tkDot
    emitLeaf p            # IDENT
    wrap p, anchor, "dot"
  else:
    error p, "expected suffix"
  discardUnused m0

proc pAtom*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkSymbol}):
    emitLeaf p            # IDENT
  elif (p.tok.kind in {tkIntLit}):
    emitLeaf p            # INT_LIT
  elif (p.tok.kind in {tkParLe}):
    expect p, tkParLe
    pExpr(p, -1)
    expect p, tkParRi
  else:
    error p, "expected atom"
  discardUnused m0

