## GENERATED by src/nifler2/tools/gramcheck.nim -- do not edit.
## One proc per rule; the dispatch is an if-chain over
## (token kind, indentation class).

import parserrt
export parserrt

const
  Tk1 = {tkAccent, tkAddr, tkBracketLe, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkGStrLit, tkGTripleStrLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkRStrLit, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk2 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBlock, tkBracketLe, tkCase, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkWhen, tkXor}
  Tk3 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBracketLe, tkCast, tkCharLit, tkConcept, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkXor}
  Tk4 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBracketLe, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkXor}
  Tk5 = {tkAccent, tkAddr, tkBracketLe, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkGStrLit, tkGTripleStrLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkParLe, tkRStrLit, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk6 = {tkAnd, tkAs, tkDiv, tkDotDot, tkFrom, tkIn, tkIs, tkIsnot, tkMod, tkNot, tkNotin, tkOf, tkOpr, tkOr, tkShl, tkShr, tkXor}
  Tk7 = {tkDistinct, tkEnum, tkObject, tkOut, tkPtr, tkRef, tkTuple, tkVar}
  Tk8 = {tkAccent, tkAddr, tkAnd, tkAs, tkAsm, tkBind, tkBlock, tkBracketLe, tkBreak, tkCase, tkCast, tkCharLit, tkComment, tkConst, tkContinue, tkConverter, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDefer, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExcept, tkExport, tkFinally, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkLet, tkMacro, tkMethod, tkMixin, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTemplate, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkUsing, tkVar, tkWhen, tkWhile, tkXor, tkYield}
  Tk9 = {tkAccent, tkAddr, tkAnd, tkAs, tkAsm, tkBind, tkBlock, tkBracketLe, tkBreak, tkCase, tkCast, tkCharLit, tkComment, tkConst, tkContinue, tkConverter, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDefer, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExcept, tkExport, tkFinally, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkLet, tkMacro, tkMethod, tkMixin, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkSemiColon, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTemplate, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkUsing, tkVar, tkWhen, tkWhile, tkXor, tkYield}
  Tk10 = {tkCharLit, tkCustomLit, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkRStrLit, tkStrLit, tkTripleStrLit, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk11 = {tkBracketDotLe, tkBracketDotRi, tkBracketLe, tkBracketRi, tkCurlyDotLe, tkCurlyDotRi, tkCurlyLe, tkCurlyRi, tkDot, tkDotDot, tkEquals, tkOpr, tkParDotLe, tkParDotRi, tkParLe, tkParRi}
  Tk12 = {tkAddr..tkYield, tkBracketDotLe, tkBracketDotRi, tkBracketLe, tkBracketRi, tkCharLit, tkCurlyDotLe, tkCurlyDotRi, tkCurlyLe, tkCurlyRi, tkCustomLit, tkDot, tkDotDot, tkEquals, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkOpr, tkParDotLe, tkParDotRi, tkParLe, tkParRi, tkRStrLit, tkStrLit, tkSymbol, tkTripleStrLit, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk13 = {tkAccent, tkAddr, tkStatic, tkSymbol, tkType}
  Tk14 = {tkDo, tkElif, tkElse, tkExcept, tkFinally, tkOf}
  Tk15 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBlock, tkBracketLe, tkCase, tkCast, tkCharLit, tkCurlyLe, tkCurlyRi, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkWhen, tkXor}
  Tk16 = {tkBlock, tkCase, tkConst, tkDiscard, tkExcept, tkFinally, tkFor, tkIf, tkInclude, tkLet, tkMixin, tkTry, tkVar, tkWhen, tkWhile}
  Tk17 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBlock, tkBracketLe, tkCase, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkParRi, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkWhen, tkXor}
  Tk18 = {tkDistinct, tkEnum, tkIterator, tkObject, tkOut, tkProc, tkPtr, tkRef, tkTuple, tkVar}
  Tk19 = {tkBlock, tkCase, tkFor, tkIf, tkTry, tkWhen}
  Tk20 = {tkAsm, tkBlock, tkCase, tkConst, tkConverter, tkDefer, tkExcept, tkFinally, tkFor, tkIf, tkLet, tkMacro, tkMethod, tkMixin, tkTemplate, tkTry, tkUsing, tkWhen, tkWhile}
  Tk21 = {tkAccent, tkAddr, tkAnd, tkAs, tkBind, tkBracketLe, tkBreak, tkCast, tkCharLit, tkComment, tkContinue, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExport, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkXor, tkYield}
  Tk22 = {tkAccent, tkAddr, tkAddr..tkYield, tkStatic, tkSymbol, tkType}
  Tk23 = {tkAccent, tkCase, tkComment, tkDiscard, tkNil, tkSymbol, tkWhen}
  Tk24 = {tkAccent, tkCase, tkDiscard, tkNil, tkSymbol, tkWhen}
  Tk25 = {tkOut, tkPtr, tkRef, tkStatic, tkType, tkVar}
  Tk26 = {tkAccent, tkAddr, tkOut, tkPtr, tkRef, tkStatic, tkSymbol, tkType, tkVar}
  Tk27 = {tkBreak, tkComment, tkContinue, tkCurlyDotLe, tkDiscard, tkExport, tkFrom, tkImport, tkInclude, tkRaise, tkReturn, tkYield}
  Tk28 = {tkAsm, tkBind, tkBlock, tkCase, tkDefer, tkFor, tkIf, tkMixin, tkStatic, tkTry, tkWhen, tkWhile}

proc canIdentOrLiteral*(p: Parser; mode: PrimaryMode): bool
proc canPrimarySuffix*(p: Parser; mode: PrimaryMode): bool
proc canTypeKAuxOperand*(p: Parser; mode: PrimaryMode): bool
proc canCommandParam*(p: Parser; mode: PrimaryMode): bool
proc canPrimary*(p: Parser; mode: PrimaryMode): bool
proc canGenericParamName*(p: Parser): bool
proc canIdentOrLiteral*(p: Parser; mode: PrimaryMode): bool =
  ((p.tok.kind in Tk1)) or (((p.tok.kind in {tkParLe})) and parIsTuple(p, mode)) or ((p.tok.kind in {tkParLe}))

proc canPrimarySuffix*(p: Parser; mode: PrimaryMode): bool =
  (((p.tok.kind in {tkParLe})) and noSpaceBefore(p)) or ((p.tok.kind in {tkDot})) or ((((p.tok.kind == tkOpr and isDotLike(p.tok)))) and dotLikeOps(p)) or (((p.tok.kind in {tkBracketLe})) and noSpaceBefore(p)) or (((p.tok.kind in {tkCurlyLe})) and noSpaceBefore(p)) or (((p.tok.kind in Tk2)) and commandStart(p) and commandAllowed(p, mode))

proc canTypeKAuxOperand*(p: Parser; mode: PrimaryMode): bool =
  (((p.tok.kind in Tk3 and indClass(p) in {icNoInd, icGt})) and isTypedefOperand(p, mode)) or (((p.tok.kind in Tk4 and indClass(p) in {icNoInd, icGt})) and typeOperandFollows(p))

proc canCommandParam*(p: Parser; mode: PrimaryMode): bool =
  (((p.tok.kind in Tk4)) and inTypeDesc(p, mode)) or ((p.tok.kind in Tk2))

proc canPrimary*(p: Parser; mode: PrimaryMode): bool =
  ((p.tok.kind in Tk5)) or (((p.tok.kind in Tk6)) and isSigilLike(p)) or (((p.tok.kind in Tk6)) and isUnary(p)) or ((p.tok.kind in {tkFunc, tkIterator, tkProc})) or ((p.tok.kind in {tkBind})) or ((p.tok.kind in Tk7)) or ((p.tok.kind in Tk6))

proc canGenericParamName*(p: Parser): bool =
  (((p.tok.kind in {tkAddr..tkYield})) and inOrOut(p)) or ((p.tok.kind in {tkAccent, tkSymbol}))

proc pModule*(p: var Parser)
proc pComma*(p: var Parser)
proc pSemicolon*(p: var Parser)
proc pColon*(p: var Parser)
proc pColcom*(p: var Parser)
proc pTrailComment*(p: var Parser)
proc pFlexComment*(p: var Parser)
proc pValidInd*(p: var Parser)
proc pOptSameInd*(p: var Parser)
proc pNotInd*(p: var Parser)
proc pOptInd*(p: var Parser)
proc pOptPar*(p: var Parser)
proc pOperator*(p: var Parser)
proc pPrefixOperator*(p: var Parser)
proc pOperatorB*(p: var Parser)
proc pPlainSymbol*(p: var Parser)
proc pSymbol*(p: var Parser)
proc pSymbolOrKeyword*(p: var Parser)
proc pLiteral*(p: var Parser)
proc pGeneralizedLit*(p: var Parser)
proc pExprColonEqExpr*(p: var Parser)
proc pExprEqExpr*(p: var Parser)
proc pExprList*(p: var Parser)
proc pOptionalExprList*(p: var Parser)
proc pExprColonEqExprList*(p: var Parser)
proc pQualifiedIdent*(p: var Parser)
proc pSetOrTableConstr*(p: var Parser)
proc pCastExpr*(p: var Parser)
proc pParKeyw*(p: var Parser)
proc pSemiStmtItem*(p: var Parser)
proc pSemiStmtList*(p: var Parser)
proc pPar*(p: var Parser)
proc pTupleConstr*(p: var Parser)
proc pArrayConstr*(p: var Parser)
proc pIdentOrLiteral*(p: var Parser; mode: PrimaryMode)
proc pPrimarySuffix*(p: var Parser; anchor: Mark; mode: PrimaryMode)
proc pPragma*(p: var Parser)
proc pIdentVis*(p: var Parser)
proc pIdentVisDot*(p: var Parser)
proc pIdentWithPragma*(p: var Parser)
proc pIdentWithPragmaDot*(p: var Parser)
proc pDeclColonEquals*(p: var Parser)
proc pIdentColonEquals*(p: var Parser)
proc pDeclColonEqualsDot*(p: var Parser)
proc pTupleTypeBracket*(p: var Parser)
proc pTupleType*(p: var Parser)
proc pTupleDecl*(p: var Parser)
proc pParamList*(p: var Parser)
proc pParamListArrow*(p: var Parser)
proc pParamListColon*(p: var Parser)
proc pDoBlock*(p: var Parser)
proc pRoutineExpr*(p: var Parser)
proc pRoutineType*(p: var Parser)
proc pRawTypeDesc*(p: var Parser)
proc pTypeDescKeyw*(p: var Parser; mode: PrimaryMode)
proc pTypeKAuxOperand*(p: var Parser; mode: PrimaryMode)
proc pTypeDescExpr*(p: var Parser)
proc pTypeDesc*(p: var Parser)
proc pForStmt*(p: var Parser)
proc pForExpr*(p: var Parser)
proc pExpr*(p: var Parser)
proc pSimplePrimary*(p: var Parser; mode: PrimaryMode)
proc pCommandParam*(p: var Parser; mode: PrimaryMode)
proc pPrimary*(p: var Parser; mode: PrimaryMode)
proc pSimpleExpr*(p: var Parser; limit: int, mode: PrimaryMode)
proc pPrimaryPragma*(p: var Parser; mode: PrimaryMode)
proc pExtraPostExprBlock*(p: var Parser)
proc pPostExprBlocks*(p: var Parser)
proc pExprStmt*(p: var Parser)
proc pImportStmt*(p: var Parser)
proc pExportStmt*(p: var Parser)
proc pIncludeStmt*(p: var Parser)
proc pFromStmt*(p: var Parser)
proc pOptExprBody*(p: var Parser)
proc pReturnStmt*(p: var Parser)
proc pRaiseStmt*(p: var Parser)
proc pYieldStmt*(p: var Parser)
proc pDiscardStmt*(p: var Parser)
proc pBreakStmt*(p: var Parser)
proc pContinueStmt*(p: var Parser)
proc pCondStmt*(p: var Parser)
proc pIfStmt*(p: var Parser)
proc pWhenStmt*(p: var Parser)
proc pCondExpr*(p: var Parser)
proc pIfExpr*(p: var Parser)
proc pWhenExpr*(p: var Parser)
proc pWhileStmt*(p: var Parser)
proc pOfBranch*(p: var Parser)
proc pOfBranches*(p: var Parser)
proc pCaseStmt*(p: var Parser)
proc pTryStmt*(p: var Parser)
proc pTryExpr*(p: var Parser)
proc pBlockStmt*(p: var Parser)
proc pBlockExpr*(p: var Parser)
proc pStaticStmt*(p: var Parser)
proc pDeferStmt*(p: var Parser)
proc pAsmStmt*(p: var Parser)
proc pGenericParamName*(p: var Parser)
proc pGenericParam*(p: var Parser)
proc pGenericParamList*(p: var Parser)
proc pPattern*(p: var Parser)
proc pIndAndComment*(p: var Parser)
proc pRoutineName*(p: var Parser)
proc pRoutine*(p: var Parser)
proc pCommentStmt*(p: var Parser)
proc pEnumDecl*(p: var Parser)
proc pObjectWhen*(p: var Parser)
proc pObjectBranch*(p: var Parser)
proc pObjectBranches*(p: var Parser)
proc pObjectCase*(p: var Parser)
proc pObjectPart*(p: var Parser)
proc pObjectDecl*(p: var Parser)
proc pConceptParam*(p: var Parser)
proc pConceptDecl*(p: var Parser)
proc pTypeDef*(p: var Parser)
proc pTypeDefValue*(p: var Parser)
proc pVarTupleLhs*(p: var Parser)
proc pVarTuple*(p: var Parser)
proc pVariable*(p: var Parser)
proc pConstant*(p: var Parser)
proc pBindStmt*(p: var Parser)
proc pMixinStmt*(p: var Parser)
proc pPragmaStmt*(p: var Parser)
proc pSimpleStmt*(p: var Parser)
proc pComplexOrSimpleStmt*(p: var Parser)
proc pStmt*(p: var Parser)
proc pSection_typeDef*(p: var Parser)
proc pSection_constant*(p: var Parser)
proc pSection_variable*(p: var Parser)

proc pModule*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk8):
    let m1 = mark(p)
    pComplexOrSimpleStmt p
    while (p.tok.kind in Tk8 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m2 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m2
      pComplexOrSimpleStmt p
    if ((p.tok.kind in Tk9)) and indClass(p) == icGt:
      error p, "invalid indentation in module"
    discardUnused m1
  wrap p, m0, "stmts"
  discardUnused m0

proc pComma*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkComma
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  discardUnused m0

proc pSemicolon*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkSemiColon
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  discardUnused m0

proc pColon*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkColon
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  discardUnused m0

proc pColcom*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkColon
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  discardUnused m0

proc pTrailComment*(p: var Parser) =
  let m0 = mark(p)
  checkInd p, {icNoInd}
  emitLeaf p            # COMMENT
  discardUnused m0

proc pFlexComment*(p: var Parser) =
  let m0 = mark(p)
  pValidInd p
  emitLeaf p            # COMMENT
  discardUnused m0

proc pValidInd*(p: var Parser) =
  let m0 = mark(p)
  let m3 = mark(p)
  checkInd p, {icNoInd, icGt}
  discardUnused m3
  discardUnused m0

proc pOptSameInd*(p: var Parser) =
  let m0 = mark(p)
  let m4 = mark(p)
  checkInd p, {icNoInd, icEq}
  discardUnused m4
  discardUnused m0

proc pNotInd*(p: var Parser) =
  let m0 = mark(p)
  let m5 = mark(p)
  checkInd p, {icNoInd, icLt, icEq}
  discardUnused m5
  discardUnused m0

proc pOptInd*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  pValidInd p
  discardUnused m0

proc pOptPar*(p: var Parser) =
  let m0 = mark(p)
  let m6 = mark(p)
  checkInd p, {icNoInd, icEq, icGt}
  discardUnused m6
  discardUnused m0

proc pOperator*(p: var Parser) =
  let m0 = mark(p)
  let m7 = mark(p)
  if (p.tok.kind in {tkOpr}):
    emitLeaf p            # OPR
  elif (p.tok.kind in {tkOr}):
    expect p, tkOr
  elif (p.tok.kind in {tkXor}):
    expect p, tkXor
  elif (p.tok.kind in {tkAnd}):
    expect p, tkAnd
  elif (p.tok.kind in {tkIs}):
    expect p, tkIs
  elif (p.tok.kind in {tkIsnot}):
    expect p, tkIsnot
  elif (p.tok.kind in {tkIn}):
    expect p, tkIn
  elif (p.tok.kind in {tkNotin}):
    expect p, tkNotin
  elif (p.tok.kind in {tkOf}):
    expect p, tkOf
  elif (p.tok.kind in {tkAs}):
    expect p, tkAs
  elif (p.tok.kind in {tkFrom}):
    expect p, tkFrom
  elif (p.tok.kind in {tkDiv}):
    expect p, tkDiv
  elif (p.tok.kind in {tkMod}):
    expect p, tkMod
  elif (p.tok.kind in {tkShl}):
    expect p, tkShl
  elif (p.tok.kind in {tkShr}):
    expect p, tkShr
  elif (p.tok.kind in {tkNot}):
    expect p, tkNot
  elif (p.tok.kind in {tkDotDot}):
    expect p, tkDotDot
  else:
    error p, "expected alternative"
  discardUnused m7
  discardUnused m0

proc pPrefixOperator*(p: var Parser) =
  let m0 = mark(p)
  pOperator p
  discardUnused m0

proc pOperatorB*(p: var Parser) =
  let m0 = mark(p)
  pOperator p
  discardUnused m0

proc pPlainSymbol*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent}):
    expect p, tkAccent
    let m9 = mark(p)
    if (p.tok.kind in {tkAddr..tkYield}):
      emitLeaf p            # KEYW
    elif (p.tok.kind in {tkSymbol}):
      emitLeaf p            # IDENT
    elif (p.tok.kind in Tk10):
      pLiteral p
    elif (p.tok.kind in Tk11):
      let m11 = mark(p)
      if (p.tok.kind in {tkOpr}):
        emitLeaf p            # OPR
      elif (p.tok.kind in {tkDot}):
        expect p, tkDot
      elif (p.tok.kind in {tkDotDot}):
        expect p, tkDotDot
      elif (p.tok.kind in {tkEquals}):
        expect p, tkEquals
      elif (p.tok.kind in {tkParLe}):
        expect p, tkParLe
      elif (p.tok.kind in {tkParRi}):
        expect p, tkParRi
      elif (p.tok.kind in {tkBracketLe}):
        expect p, tkBracketLe
      elif (p.tok.kind in {tkBracketRi}):
        expect p, tkBracketRi
      elif (p.tok.kind in {tkCurlyLe}):
        expect p, tkCurlyLe
      elif (p.tok.kind in {tkCurlyRi}):
        expect p, tkCurlyRi
      elif (p.tok.kind in {tkBracketDotLe}):
        expect p, tkBracketDotLe
      elif (p.tok.kind in {tkBracketDotRi}):
        expect p, tkBracketDotRi
      elif (p.tok.kind in {tkCurlyDotLe}):
        expect p, tkCurlyDotLe
      elif (p.tok.kind in {tkCurlyDotRi}):
        expect p, tkCurlyDotRi
      elif (p.tok.kind in {tkParDotLe}):
        expect p, tkParDotLe
      elif (p.tok.kind in {tkParDotRi}):
        expect p, tkParDotRi
      else:
        error p, "expected alternative"
      discardUnused m11
      while (p.tok.kind in Tk11):
        let m10 = mark(p)
        let m12 = mark(p)
        if (p.tok.kind in {tkOpr}):
          emitLeaf p            # OPR
        elif (p.tok.kind in {tkDot}):
          expect p, tkDot
        elif (p.tok.kind in {tkDotDot}):
          expect p, tkDotDot
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
        elif (p.tok.kind in {tkParLe}):
          expect p, tkParLe
        elif (p.tok.kind in {tkParRi}):
          expect p, tkParRi
        elif (p.tok.kind in {tkBracketLe}):
          expect p, tkBracketLe
        elif (p.tok.kind in {tkBracketRi}):
          expect p, tkBracketRi
        elif (p.tok.kind in {tkCurlyLe}):
          expect p, tkCurlyLe
        elif (p.tok.kind in {tkCurlyRi}):
          expect p, tkCurlyRi
        elif (p.tok.kind in {tkBracketDotLe}):
          expect p, tkBracketDotLe
        elif (p.tok.kind in {tkBracketDotRi}):
          expect p, tkBracketDotRi
        elif (p.tok.kind in {tkCurlyDotLe}):
          expect p, tkCurlyDotLe
        elif (p.tok.kind in {tkCurlyDotRi}):
          expect p, tkCurlyDotRi
        elif (p.tok.kind in {tkParDotLe}):
          expect p, tkParDotLe
        elif (p.tok.kind in {tkParDotRi}):
          expect p, tkParDotRi
        else:
          error p, "expected alternative"
        discardUnused m12
        discardUnused m10
    else:
      error p, "expected alternative"
    discardUnused m9
    while (p.tok.kind in Tk12):
      let m8 = mark(p)
      let m13 = mark(p)
      if (p.tok.kind in {tkAddr..tkYield}):
        emitLeaf p            # KEYW
      elif (p.tok.kind in {tkSymbol}):
        emitLeaf p            # IDENT
      elif (p.tok.kind in Tk10):
        pLiteral p
      elif (p.tok.kind in Tk11):
        let m15 = mark(p)
        if (p.tok.kind in {tkOpr}):
          emitLeaf p            # OPR
        elif (p.tok.kind in {tkDot}):
          expect p, tkDot
        elif (p.tok.kind in {tkDotDot}):
          expect p, tkDotDot
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
        elif (p.tok.kind in {tkParLe}):
          expect p, tkParLe
        elif (p.tok.kind in {tkParRi}):
          expect p, tkParRi
        elif (p.tok.kind in {tkBracketLe}):
          expect p, tkBracketLe
        elif (p.tok.kind in {tkBracketRi}):
          expect p, tkBracketRi
        elif (p.tok.kind in {tkCurlyLe}):
          expect p, tkCurlyLe
        elif (p.tok.kind in {tkCurlyRi}):
          expect p, tkCurlyRi
        elif (p.tok.kind in {tkBracketDotLe}):
          expect p, tkBracketDotLe
        elif (p.tok.kind in {tkBracketDotRi}):
          expect p, tkBracketDotRi
        elif (p.tok.kind in {tkCurlyDotLe}):
          expect p, tkCurlyDotLe
        elif (p.tok.kind in {tkCurlyDotRi}):
          expect p, tkCurlyDotRi
        elif (p.tok.kind in {tkParDotLe}):
          expect p, tkParDotLe
        elif (p.tok.kind in {tkParDotRi}):
          expect p, tkParDotRi
        else:
          error p, "expected alternative"
        discardUnused m15
        while (p.tok.kind in Tk11):
          let m14 = mark(p)
          let m16 = mark(p)
          if (p.tok.kind in {tkOpr}):
            emitLeaf p            # OPR
          elif (p.tok.kind in {tkDot}):
            expect p, tkDot
          elif (p.tok.kind in {tkDotDot}):
            expect p, tkDotDot
          elif (p.tok.kind in {tkEquals}):
            expect p, tkEquals
          elif (p.tok.kind in {tkParLe}):
            expect p, tkParLe
          elif (p.tok.kind in {tkParRi}):
            expect p, tkParRi
          elif (p.tok.kind in {tkBracketLe}):
            expect p, tkBracketLe
          elif (p.tok.kind in {tkBracketRi}):
            expect p, tkBracketRi
          elif (p.tok.kind in {tkCurlyLe}):
            expect p, tkCurlyLe
          elif (p.tok.kind in {tkCurlyRi}):
            expect p, tkCurlyRi
          elif (p.tok.kind in {tkBracketDotLe}):
            expect p, tkBracketDotLe
          elif (p.tok.kind in {tkBracketDotRi}):
            expect p, tkBracketDotRi
          elif (p.tok.kind in {tkCurlyDotLe}):
            expect p, tkCurlyDotLe
          elif (p.tok.kind in {tkCurlyDotRi}):
            expect p, tkCurlyDotRi
          elif (p.tok.kind in {tkParDotLe}):
            expect p, tkParDotLe
          elif (p.tok.kind in {tkParDotRi}):
            expect p, tkParDotRi
          else:
            error p, "expected alternative"
          discardUnused m16
          discardUnused m14
      else:
        error p, "expected alternative"
      discardUnused m13
      discardUnused m8
    expect p, tkAccent
    wrap p, m0, "quoted"
  elif (p.tok.kind in {tkSymbol}):
    emitLeaf p            # IDENT
  else:
    error p, "expected plainSymbol"
  discardUnused m0

proc pSymbol*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pPlainSymbol p
  elif (p.tok.kind in {tkAddr}):
    expect p, tkAddr
  elif (p.tok.kind in {tkType}):
    expect p, tkType
  elif (p.tok.kind in {tkStatic}):
    expect p, tkStatic
  else:
    error p, "expected symbol"
  discardUnused m0

proc pSymbolOrKeyword*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk13):
    pSymbol p
  elif (p.tok.kind in {tkAddr..tkYield}):
    emitLeaf p            # KEYW
  else:
    error p, "expected symbolOrKeyword"
  discardUnused m0

proc pLiteral*(p: var Parser) =
  let m0 = mark(p)
  let m17 = mark(p)
  if (p.tok.kind in {tkIntLit}):
    emitLeaf p            # INT_LIT
  elif (p.tok.kind in {tkInt8Lit}):
    emitLeaf p            # INT8_LIT
  elif (p.tok.kind in {tkInt16Lit}):
    emitLeaf p            # INT16_LIT
  elif (p.tok.kind in {tkInt32Lit}):
    emitLeaf p            # INT32_LIT
  elif (p.tok.kind in {tkInt64Lit}):
    emitLeaf p            # INT64_LIT
  elif (p.tok.kind in {tkUIntLit}):
    emitLeaf p            # UINT_LIT
  elif (p.tok.kind in {tkUInt8Lit}):
    emitLeaf p            # UINT8_LIT
  elif (p.tok.kind in {tkUInt16Lit}):
    emitLeaf p            # UINT16_LIT
  elif (p.tok.kind in {tkUInt32Lit}):
    emitLeaf p            # UINT32_LIT
  elif (p.tok.kind in {tkUInt64Lit}):
    emitLeaf p            # UINT64_LIT
  elif (p.tok.kind in {tkFloatLit}):
    emitLeaf p            # FLOAT_LIT
  elif (p.tok.kind in {tkFloat32Lit}):
    emitLeaf p            # FLOAT32_LIT
  elif (p.tok.kind in {tkFloat64Lit}):
    emitLeaf p            # FLOAT64_LIT
  elif (p.tok.kind in {tkFloat128Lit}):
    emitLeaf p            # FLOAT128_LIT
  elif (p.tok.kind in {tkStrLit}):
    emitLeaf p            # STR_LIT
  elif (p.tok.kind in {tkRStrLit}):
    emitLeaf p            # RSTR_LIT
  elif (p.tok.kind in {tkTripleStrLit}):
    emitLeaf p            # TRIPLESTR_LIT
  elif (p.tok.kind in {tkCharLit}):
    emitLeaf p            # CHAR_LIT
  elif (p.tok.kind in {tkCustomLit}):
    emitLeaf p            # CUSTOM_NUMERIC_LIT
  elif (p.tok.kind in {tkNil}):
    expect p, tkNil
  else:
    error p, "expected alternative"
  discardUnused m17
  discardUnused m0

proc pGeneralizedLit*(p: var Parser) =
  let m0 = mark(p)
  let m18 = mark(p)
  if (p.tok.kind in {tkGStrLit}):
    emitLeaf p            # GENERALIZED_STR_LIT
  elif (p.tok.kind in {tkGTripleStrLit}):
    emitLeaf p            # GENERALIZED_TRIPLESTR_LIT
  else:
    error p, "expected alternative"
  discardUnused m18
  discardUnused m0

proc pExprColonEqExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk2):
    pExpr p
    if (p.tok.kind in {tkColon}):
      expect p, tkColon
      pExpr p
      wrap p, m0, "kv"
    elif (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pExpr p
      wrap p, m0, "vv"
    elif (p.tok.kind in {tkDo}):
      if (p.tok.kind in {tkDo}):
        pDoBlock p
        while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
          let m19 = mark(p)
          pExtraPostExprBlock p
          discardUnused m19
  else:
    error p, "expected exprColonEqExpr"
  discardUnused m0

proc pExprEqExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk2):
    pExpr p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pExpr p
      wrap p, m0, "vv"
    elif (p.tok.kind in {tkDo}):
      if (p.tok.kind in {tkDo}):
        pDoBlock p
        while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
          let m20 = mark(p)
          pExtraPostExprBlock p
          discardUnused m20
  else:
    error p, "expected exprEqExpr"
  discardUnused m0

proc pExprList*(p: var Parser) =
  let m0 = mark(p)
  let m21 = mark(p)
  pExpr p
  while (p.tok.kind in {tkComma}):
    pComma p
    pExpr p
  discardUnused m21
  discardUnused m0

proc pOptionalExprList*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk2):
    let m22 = mark(p)
    pExpr p
    while (p.tok.kind in {tkComma}):
      pComma p
      pExpr p
    discardUnused m22
  discardUnused m0

proc pExprColonEqExprList*(p: var Parser) =
  let m0 = mark(p)
  pExprColonEqExpr p
  while (p.tok.kind in {tkComma}):
    let m23 = mark(p)
    pComma p
    if (p.tok.kind in Tk2):
      pExprColonEqExpr p
    discardUnused m23
  discardUnused m0

proc pQualifiedIdent*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk13):
    pSymbol p
    if (p.tok.kind in {tkDot}):
      expect p, tkDot
      pOptInd p
      pSymbolOrKeyword p
      wrap p, m0, "dot"
    else:
      discard
  else:
    error p, "expected qualifiedIdent"
  discardUnused m0

proc pSetOrTableConstr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkCurlyLe}):
    expect p, tkCurlyLe
    if (p.tok.kind in Tk15 and indClass(p) in {icNoInd, icGt}) or (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pOptInd p
      if (p.tok.kind in Tk2):
        pExprColonEqExprList p
      pOptPar p
      expect p, tkCurlyRi
      wrap p, m0, "curly"
    elif (p.tok.kind in {tkColon}):
      expect p, tkColon
      pOptPar p
      expect p, tkCurlyRi
      wrap p, m0, "tabconstr"
    else:
      error p, "expected setOrTableConstr"
  else:
    error p, "expected setOrTableConstr"
  discardUnused m0

proc pCastExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkCast}):
    expect p, tkCast
    if (p.tok.kind in {tkBracketLe}):
      expect p, tkBracketLe
      pOptInd p
      pTypeDesc p
      pOptPar p
      expect p, tkBracketRi
      expect p, tkParLe
      pOptInd p
      pExpr p
      pOptPar p
      expect p, tkParRi
      wrap p, m0, "cast"
    elif (p.tok.kind in {tkParLe}):
      expect p, tkParLe
      pOptInd p
      pExprColonEqExpr p
      pOptPar p
      expect p, tkParRi
      wrap p, m0, "cast"
    else:
      error p, "expected castExpr"
  else:
    error p, "expected castExpr"
  discardUnused m0

proc pParKeyw*(p: var Parser) =
  let m0 = mark(p)
  let m24 = mark(p)
  if (p.tok.kind in {tkDiscard}):
    expect p, tkDiscard
  elif (p.tok.kind in {tkInclude}):
    expect p, tkInclude
  elif (p.tok.kind in {tkIf}):
    expect p, tkIf
  elif (p.tok.kind in {tkWhile}):
    expect p, tkWhile
  elif (p.tok.kind in {tkCase}):
    expect p, tkCase
  elif (p.tok.kind in {tkTry}):
    expect p, tkTry
  elif (p.tok.kind in {tkFinally}):
    expect p, tkFinally
  elif (p.tok.kind in {tkExcept}):
    expect p, tkExcept
  elif (p.tok.kind in {tkFor}):
    expect p, tkFor
  elif (p.tok.kind in {tkBlock}):
    expect p, tkBlock
  elif (p.tok.kind in {tkConst}):
    expect p, tkConst
  elif (p.tok.kind in {tkLet}):
    expect p, tkLet
  elif (p.tok.kind in {tkWhen}):
    expect p, tkWhen
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
  elif (p.tok.kind in {tkMixin}):
    expect p, tkMixin
  else:
    error p, "expected alternative"
  discardUnused m24
  discardUnused m0

proc pSemiStmtItem*(p: var Parser) =
  let m0 = mark(p)
  let m25 = mark(p)
  if (p.tok.kind in {tkIf}):
    pIfExpr p
  elif (p.tok.kind in {tkWhen}):
    pWhenExpr p
  elif (p.tok.kind in Tk8):
    pComplexOrSimpleStmt p
  else:
    error p, "expected alternative"
  discardUnused m25
  discardUnused m0

proc pSemiStmtList*(p: var Parser) =
  let m0 = mark(p)
  pSemiStmtItem p
  while (p.tok.kind in Tk9):
    let m26 = mark(p)
    let m27 = mark(p)
    if (p.tok.kind in {tkSemiColon}):
      expect p, tkSemiColon
      if (p.tok.kind in Tk8):
        pSemiStmtItem p
    elif (p.tok.kind in Tk8):
      pSemiStmtItem p
    else:
      error p, "expected alternative"
    discardUnused m27
    discardUnused m26
  discardUnused m0

proc pPar*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe}):
    expect p, tkParLe
    if (p.tok.kind in Tk9 and indClass(p) in {icNoInd, icGt}):
      pOptInd p
      if (p.tok.kind in Tk16):
        pushIndAny p
        pSemiStmtList p
        popInd p
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "stmts"
      elif (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
        if (p.tok.kind in Tk8):
          pushIndAny p
          pSemiStmtList p
          popInd p
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "stmts"
      elif (p.tok.kind in {tkCurlyDotLe}):
        pPragmaStmt p
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "par"
      elif (p.tok.kind in Tk4):
        pSimpleExpr(p, -1, pmNormal)
        if (p.tok.kind in {tkDo}):
          pDoBlock p
          while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
            let m28 = mark(p)
            pExtraPostExprBlock p
            discardUnused m28
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
          pExpr p
          wrap p, m0, "asgn"
          if (p.tok.kind in {tkParRi} and indClass(p) in {icNoInd, icEq, icGt}):
            pOptPar p
            expect p, tkParRi
            wrap p, m0, "par"
          elif (p.tok.kind in {tkSemiColon}):
            expect p, tkSemiColon
            if (p.tok.kind in Tk8):
              pushIndAny p
              pSemiStmtList p
              popInd p
            pOptPar p
            expect p, tkParRi
            wrap p, m0, "stmts"
          else:
            error p, "expected par"
        elif (p.tok.kind in {tkSemiColon}):
          expect p, tkSemiColon
          if (p.tok.kind in Tk8):
            pushIndAny p
            pSemiStmtList p
            popInd p
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "stmts"
        elif (p.tok.kind in {tkColon}):
          expect p, tkColon
          pExpr p
          wrap p, m0, "kv"
          while (p.tok.kind in {tkColon}):
            let m29 = mark(p)
            expect p, tkColon
            pExpr p
            wrap p, m29, "kv"
            discardUnused m29
          while (p.tok.kind in {tkComma}):
            let m30 = mark(p)
            pComma p
            if (p.tok.kind in Tk2):
              pExprColonEqExpr p
            discardUnused m30
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "tup"
        elif (p.tok.kind in {tkComma}):
          pComma p
          while (p.tok.kind in Tk2):
            let m31 = mark(p)
            pExprColonEqExpr p
            if (p.tok.kind in {tkComma}):
              pComma p
            discardUnused m31
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "tup"
        elif (p.tok.kind in {tkParRi} and indClass(p) in {icNoInd, icEq, icGt}):
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        else:
          error p, "expected par"
      else:
        error p, "expected par"
    elif (p.tok.kind in {tkParRi} and indClass(p) in {icNoInd, icEq, icGt}):
      pOptPar p
      expect p, tkParRi
      wrap p, m0, "tup"
    else:
      error p, "expected par"
  else:
    error p, "expected par"
  discardUnused m0

proc pTupleConstr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe}):
    expect p, tkParLe
    if (p.tok.kind in Tk17 and indClass(p) in {icNoInd, icEq, icGt}) or (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
        pFlexComment p
      if (p.tok.kind in Tk17 and indClass(p) in {icNoInd, icEq, icGt}):
        pOptPar p
        if (p.tok.kind in {tkParRi}):
          expect p, tkParRi
          wrap p, m0, "par"
        elif (p.tok.kind in Tk2):
          pExprColonEqExpr p
          if (p.tok.kind in {tkParRi} and indClass(p) in {icNoInd, icEq, icGt}):
            pOptPar p
            expect p, tkParRi
            wrap p, m0, "par"
          elif (p.tok.kind in {tkComma}):
            pComma p
            while (p.tok.kind in Tk2):
              let m32 = mark(p)
              pExprColonEqExpr p
              if (p.tok.kind in {tkComma}):
                pComma p
              discardUnused m32
            pOptPar p
            expect p, tkParRi
            wrap p, m0, "tup"
          else:
            error p, "expected tupleConstr"
        else:
          error p, "expected tupleConstr"
      else:
        error p, "expected tupleConstr"
    else:
      error p, "expected tupleConstr"
  else:
    error p, "expected tupleConstr"
  discardUnused m0

proc pArrayConstr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pFlexComment p
  pOptPar p
  if (p.tok.kind in Tk2):
    pExprColonEqExprList p
  pOptPar p
  expect p, tkBracketRi
  wrap p, m0, "bracket"
  discardUnused m0

proc pIdentOrLiteral*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1):
    let m33 = mark(p)
    if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
      pGeneralizedLit p
    elif (p.tok.kind in Tk13):
      pSymbol p
    elif (p.tok.kind in Tk10):
      pLiteral p
    elif (p.tok.kind in {tkBracketLe}):
      pArrayConstr p
    elif (p.tok.kind in {tkCurlyLe}):
      pSetOrTableConstr p
    elif (p.tok.kind in {tkCast}):
      pCastExpr p
    else:
      error p, "expected alternative"
    discardUnused m33
  elif ((p.tok.kind in {tkParLe})) and parIsTuple(p, mode):
    pTupleConstr p
  elif (p.tok.kind in {tkParLe}):
    pPar p
  else:
    error p, "expected identOrLiteral"
  discardUnused m0

proc pPrimarySuffix*(p: var Parser; anchor: Mark; mode: PrimaryMode) =
  let m0 = mark(p)
  if ((p.tok.kind in {tkBracketLe, tkCurlyLe, tkParLe})) and noSpaceBefore(p):
    if (p.tok.kind in {tkParLe}):
      expect p, tkParLe
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
        pFlexComment p
      pOptPar p
      if (p.tok.kind in Tk2):
        pExprColonEqExprList p
      pOptPar p
      expect p, tkParRi
      wrap p, anchor, "call"
    elif (p.tok.kind in {tkBracketLe}):
      expect p, tkBracketLe
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
        pFlexComment p
      pOptPar p
      if (p.tok.kind in Tk2):
        pExprColonEqExprList p
      pOptPar p
      expect p, tkBracketRi
      wrap p, anchor, "at"
    elif (p.tok.kind in {tkCurlyLe}):
      expect p, tkCurlyLe
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
        pFlexComment p
      pOptPar p
      if (p.tok.kind in Tk2):
        pExprColonEqExprList p
      pOptPar p
      expect p, tkCurlyRi
      wrap p, anchor, "curlyat"
    else:
      error p, "expected primarySuffix"
  elif (p.tok.kind in {tkDot}):
    expect p, tkDot
    pOptInd p
    pSymbolOrKeyword p
    if (p.tok.kind in {tkBracketLeColon}):
      expect p, tkBracketLeColon
      pExprList p
      expect p, tkBracketRi
      if (p.tok.kind in {tkParLe}):
        expect p, tkParLe
        pExprColonEqExpr p
        expect p, tkParRi
    wrap p, anchor, "dot"
    if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
      pGeneralizedLit p
  elif (((p.tok.kind == tkOpr and isDotLike(p.tok)))) and dotLikeOps(p):
    emitLeaf p            # DOTLIKEOP
    pOptInd p
    pSymbolOrKeyword p
    wrap p, anchor, "dot"
    if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
      pGeneralizedLit p
  elif ((p.tok.kind in Tk2)) and commandStart(p) and commandAllowed(p, mode):
    pCommandParam(p, mode)
    wrap p, anchor, "cmd"
  else:
    error p, "expected primarySuffix"
  discardUnused m0

proc pPragma*(p: var Parser) =
  let m0 = mark(p)
  inc p.inPragma
  expect p, tkCurlyDotLe
  pOptInd p
  while (p.tok.kind in Tk2):
    let m34 = mark(p)
    pExprColonEqExpr p
    if (p.tok.kind in {tkComma}):
      pComma p
    discardUnused m34
  pOptPar p
  let m35 = mark(p)
  if (p.tok.kind in {tkCurlyDotRi}):
    expect p, tkCurlyDotRi
  elif (p.tok.kind in {tkCurlyRi}):
    expect p, tkCurlyRi
  else:
    error p, "expected alternative"
  discardUnused m35
  dec p.inPragma
  wrap p, m0, "pragmas"
  discardUnused m0

proc pIdentVis*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pPlainSymbol p
    if (p.tok.kind in {tkOpr}):
      emitLeaf p            # OPR
      wrap p, m0, "postfix"
    else:
      discard
  else:
    error p, "expected identVis"
  discardUnused m0

proc pIdentVisDot*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pPlainSymbol p
    if (p.tok.kind in {tkOpr}):
      emitLeaf p            # OPR
      wrap p, m0, "postfix"
    elif (p.tok.kind in {tkDot}):
      expect p, tkDot
      pOptInd p
      pSymbolOrKeyword p
      wrap p, m0, "dot"
    else:
      discard
  else:
    error p, "expected identVisDot"
  discardUnused m0

proc pIdentWithPragma*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pIdentVis p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
      wrap p, m0, "pragmax"
    else:
      discard
  else:
    error p, "expected identWithPragma"
  discardUnused m0

proc pIdentWithPragmaDot*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pIdentVisDot p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
      wrap p, m0, "pragmax"
    else:
      discard
  else:
    error p, "expected identWithPragmaDot"
  discardUnused m0

proc pDeclColonEquals*(p: var Parser) =
  let m0 = mark(p)
  pIdentWithPragma p
  while (p.tok.kind in {tkComma}):
    let m36 = mark(p)
    pComma p
    pIdentWithPragma p
    discardUnused m36
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  let m = m0
  fanOut m, p.section          # one (var|let|param|fld ...) per name
  discardUnused m0

proc pIdentColonEquals*(p: var Parser) =
  let m0 = mark(p)
  pPlainSymbol p
  while (p.tok.kind in {tkComma}):
    let m37 = mark(p)
    pComma p
    pPlainSymbol p
    discardUnused m37
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  let m = m0
  fanOut m, p.section
  discardUnused m0

proc pDeclColonEqualsDot*(p: var Parser) =
  let m0 = mark(p)
  pIdentWithPragmaDot p
  while (p.tok.kind in {tkComma}):
    let m38 = mark(p)
    pComma p
    pIdentWithPragmaDot p
    discardUnused m38
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  let m = m0
  fanOut m, p.section
  discardUnused m0

proc pTupleTypeBracket*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  pOptInd p
  while (p.tok.kind in {tkAccent, tkSymbol}):
    let m39 = mark(p)
    pIdentColonEquals p
    if (p.tok.kind in {tkComma, tkSemiColon}):
      let m40 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m40
    discardUnused m39
  pOptPar p
  expect p, tkBracketRi
  discardUnused m0

proc pTupleType*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTuple
  if (p.tok.kind in {tkBracketLe}):
    pTupleTypeBracket p
  wrap p, m0, "tuple"
  discardUnused m0

proc pTupleDecl*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkTuple}):
    expect p, tkTuple
    if (p.tok.kind in {tkBracketLe}):
      pTupleTypeBracket p
      wrap p, m0, "tuple"
    elif (p.tok.kind in {tkAccent, tkSymbol} and indClass(p) in {icGt}) or (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      if (p.tok.kind in {tkAccent, tkComment, tkSymbol} and indClass(p) in {icGt}):
        pushInd p
        if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq}):
          pOptSameInd p
          emitLeaf p            # COMMENT
        let m41 = mark(p)
        pIdentColonEquals p
        if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq, icGt}):
          pOptPar p
          emitLeaf p            # COMMENT
        while (p.tok.kind in {tkAccent, tkSymbol} and indClass(p) in {icEq}):
          checkInd p, {icEq}
          pIdentColonEquals p
          if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq, icGt}):
            pOptPar p
            emitLeaf p            # COMMENT
        if ((p.tok.kind in {tkAccent, tkSymbol})) and indClass(p) == icGt:
          error p, "invalid indentation in tupleDecl"
        discardUnused m41
        popInd p
      wrap p, m0, "tuple"
    else:
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      if (p.tok.kind in {tkAccent, tkComment, tkSymbol} and indClass(p) in {icGt}):
        pushInd p
        if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq}):
          pOptSameInd p
          emitLeaf p            # COMMENT
        let m42 = mark(p)
        pIdentColonEquals p
        if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq, icGt}):
          pOptPar p
          emitLeaf p            # COMMENT
        while (p.tok.kind in {tkAccent, tkSymbol} and indClass(p) in {icEq}):
          checkInd p, {icEq}
          pIdentColonEquals p
          if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq, icGt}):
            pOptPar p
            emitLeaf p            # COMMENT
        if ((p.tok.kind in {tkAccent, tkSymbol})) and indClass(p) == icGt:
          error p, "invalid indentation in tupleDecl"
        discardUnused m42
        popInd p
      wrap p, m0, "tuple"
  else:
    error p, "expected tupleDecl"
  discardUnused m0

proc pParamList*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkParLe
  pOptInd p
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pDeclColonEquals p
    while (p.tok.kind in {tkComma, tkSemiColon}):
      let m43 = mark(p)
      let m44 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m44
      if (p.tok.kind in {tkAccent, tkSymbol}):
        pDeclColonEquals p
      discardUnused m43
  pOptPar p
  expect p, tkParRi
  wrap p, m0, "params"
  discardUnused m0

proc pParamListArrow*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pParamList p
  if ((p.tok.kind == tkOpr and p.tok.s == "->") and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    expect p, tkOpr, "->"
    pOptInd p
    pTypeDesc p
  discardUnused m0

proc pParamListColon*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pParamList p
  if (p.tok.kind in {tkColon} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    expect p, tkColon
    pOptInd p
    pTypeDesc p
  discardUnused m0

proc pDoBlock*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDo
  pParamListArrow p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  pColcom p
  pStmt p
  wrap p, m0, "proc"
  discardUnused m0

proc pRoutineExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkProc}):
    expect p, tkProc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      pStmt p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkFunc}):
    expect p, tkFunc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      pStmt p
    wrap p, m0, "func"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      pStmt p
    wrap p, m0, "iterator"
  else:
    error p, "expected routineExpr"
  discardUnused m0

proc pRoutineType*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkProc}):
    expect p, tkProc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    wrap p, m0, "itertype"
  else:
    error p, "expected routineType"
  discardUnused m0

proc pRawTypeDesc*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkIterator, tkProc}):
    pRoutineType p
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  elif (p.tok.kind in Tk7):
    pTypeDescKeyw(p, pmTypeDesc)
  else:
    error p, "expected rawTypeDesc"
  discardUnused m0

proc pTypeDescKeyw*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  let m45 = mark(p)
  if (p.tok.kind in {tkTuple}):
    pTupleType p
  elif (p.tok.kind in {tkEnum}):
    expect p, tkEnum
    wrap p, m45, "enum"
  elif (p.tok.kind in {tkObject}):
    expect p, tkObject
    wrap p, m45, "object"
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
    if canTypeKAuxOperand(p, mode):
      pTypeKAuxOperand(p, mode)
    wrap p, m45, "mut"
  elif (p.tok.kind in {tkOut}):
    expect p, tkOut
    if canTypeKAuxOperand(p, mode):
      pTypeKAuxOperand(p, mode)
    wrap p, m45, "out"
  elif (p.tok.kind in {tkRef}):
    expect p, tkRef
    if canTypeKAuxOperand(p, mode):
      pTypeKAuxOperand(p, mode)
    wrap p, m45, "ref"
  elif (p.tok.kind in {tkPtr}):
    expect p, tkPtr
    if canTypeKAuxOperand(p, mode):
      pTypeKAuxOperand(p, mode)
    wrap p, m45, "ptr"
  elif (p.tok.kind in {tkDistinct}):
    expect p, tkDistinct
    if canTypeKAuxOperand(p, mode):
      pTypeKAuxOperand(p, mode)
    wrap p, m45, "distinct"
  else:
    error p, "expected alternative"
  discardUnused m45
  if (p.tok.kind in {tkNot}):
    expect p, tkNot
    pPrimary(p, pmTypeDesc)
    wrap p, m0, "infix"
  discardUnused m0

proc pTypeKAuxOperand*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if ((p.tok.kind in Tk3 and indClass(p) in {icNoInd, icGt})) and isTypedefOperand(p, mode):
    pValidInd p
    pTypeDefValue p
  elif ((p.tok.kind in Tk4 and indClass(p) in {icNoInd, icGt})) and typeOperandFollows(p):
    pValidInd p
    pPrimary(p, mode)
  else:
    error p, "expected typeKAuxOperand"
  discardUnused m0

proc pTypeDescExpr*(p: var Parser) =
  let m0 = mark(p)
  pSimpleExpr(p, -1, pmTypeDesc)
  if (p.tok.kind in {tkNot}):
    expect p, tkNot
    pPrimary(p, pmTypeDesc)
    wrap p, m0, "infix"
  discardUnused m0

proc pTypeDesc*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk18):
    pRawTypeDesc p
  else:
    pTypeDescExpr p
  discardUnused m0

proc pForStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkFor
  let m46 = mark(p)
  let m47 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTupleLhs p
  elif (p.tok.kind in {tkAccent, tkSymbol}):
    pIdentWithPragma p
  else:
    error p, "expected alternative"
  discardUnused m47
  while (p.tok.kind in {tkComma}):
    pComma p
    let m48 = mark(p)
    if (p.tok.kind in {tkParLe}):
      pVarTupleLhs p
    elif (p.tok.kind in {tkAccent, tkSymbol}):
      pIdentWithPragma p
    else:
      error p, "expected alternative"
    discardUnused m48
  discardUnused m46
  expect p, tkIn
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "for"
  discardUnused m0

proc pForExpr*(p: var Parser) =
  let m0 = mark(p)
  pForStmt p
  discardUnused m0

proc pExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk19):
    let m49 = mark(p)
    if (p.tok.kind in {tkBlock}):
      pBlockExpr p
    elif (p.tok.kind in {tkIf}):
      pIfExpr p
    elif (p.tok.kind in {tkWhen}):
      pWhenExpr p
    elif (p.tok.kind in {tkCase}):
      pCaseStmt p
    elif (p.tok.kind in {tkFor}):
      pForExpr p
    elif (p.tok.kind in {tkTry}):
      pTryExpr p
    else:
      error p, "expected alternative"
    discardUnused m49
  elif (p.tok.kind in Tk4):
    pSimpleExpr(p, -1, pmNormal)
  else:
    error p, "expected expr"
  discardUnused m0

proc pSimplePrimary*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  pIdentOrLiteral(p, mode)
  while (canPrimarySuffix(p, mode)) and suffixStart(p):
    let m50 = mark(p)
    pPrimarySuffix(p, m0, mode)
    discardUnused m50
  discardUnused m0

proc pCommandParam*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if ((p.tok.kind in Tk4)) and inTypeDesc(p, mode):
    pSimpleExpr(p, -1, mode)
  else:
    pExpr p
    if (p.tok.kind in {tkDo}):
      pDoBlock p
      while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
        let m51 = mark(p)
        pExtraPostExprBlock p
        discardUnused m51
  discardUnused m0

proc pPrimary*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if (p.tok.kind in Tk5):
    pSimplePrimary(p, mode)
  elif ((p.tok.kind in Tk6)) and isSigilLike(p):
    pPrefixOperator p
    let m52 = mark(p)
    if (p.tok.kind in Tk5):
      pSimplePrimary(p, mode)
    else:
      pPrimary(p, pmNormal)
    discardUnused m52
    wrap p, m0, "prefix"
  elif ((p.tok.kind in Tk6)) and isUnary(p):
    pOperatorB p
    pPrimary(p, mode)
    wrap p, m0, "prefix"
  elif (p.tok.kind in {tkFunc, tkIterator, tkProc}):
    pRoutineExpr p
  elif (p.tok.kind in {tkBind}):
    expect p, tkBind
    pOptInd p
    pPrimary(p, pmNormal)
    wrap p, m0, "bind"
  elif (p.tok.kind in Tk7):
    pTypeDescKeyw(p, mode)
  elif (p.tok.kind in Tk6):
    pPrefixOperator p
    pPrimary(p, mode)
    wrap p, m0, "prefix"
  else:
    error p, "expected primary"
  discardUnused m0

proc pSimpleExpr*(p: var Parser; limit: int, mode: PrimaryMode) =
  let m0 = mark(p)
  pPrimaryPragma(p, mode)
  var prec = getPrecedence(p)
  while prec >= limit and indClass(p) == icNoInd:
    let assoc = (if isRightAssoc(p): 0 else: 1)
    insertLeafAt p, m0, p.tok.s
    getTok p
    pSimpleExpr(p, prec + assoc, mode)
    wrap p, m0, "infix"
    prec = getPrecedence(p)
  discardUnused m0

proc pPrimaryPragma*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  pPrimary(p, mode)
  if ((p.tok.kind in {tkCurlyDotLe} and indClass(p) in {icNoInd, icGt})) and pragmaOnPrimary(p, mode):
    pValidInd p
    pPragma p
    wrap p, m0, "pragmax"
  discardUnused m0

proc pExtraPostExprBlock*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk14 and indClass(p) in {icEq}):
    checkInd p, {icEq}
    if (p.tok.kind in {tkDo}):
      pDoBlock p
    elif (p.tok.kind in {tkOf}):
      expect p, tkOf
      pExprList p
      expect p, tkColon
      pStmt p
      wrap p, m0, "of"
    elif (p.tok.kind in {tkElif}):
      expect p, tkElif
      pExpr p
      expect p, tkColon
      pStmt p
      wrap p, m0, "elif"
    elif (p.tok.kind in {tkExcept}):
      expect p, tkExcept
      pOptionalExprList p
      expect p, tkColon
      pStmt p
      wrap p, m0, "except"
    elif (p.tok.kind in {tkFinally}):
      expect p, tkFinally
      expect p, tkColon
      pStmt p
      wrap p, m0, "fin"
    elif (p.tok.kind in {tkElse}):
      expect p, tkElse
      expect p, tkColon
      pStmt p
      wrap p, m0, "else"
    else:
      error p, "expected extraPostExprBlock"
  else:
    error p, "expected extraPostExprBlock"
  discardUnused m0

proc pPostExprBlocks*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    if (p.tok.kind in {tkDo}):
      pDoBlock p
      while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
        let m53 = mark(p)
        pExtraPostExprBlock p
        discardUnused m53
    elif (p.tok.kind in {tkColon}):
      expect p, tkColon
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
        pTrailComment p
      let m54 = mark(p)
      if (p.tok.kind in Tk14 and indClass(p) in {icEq}):
        pExtraPostExprBlock p
      elif (p.tok.kind in Tk20 and indClass(p) in {icGt}) or (p.tok.kind in Tk21):
        pStmt p
      else:
        error p, "expected alternative"
      discardUnused m54
      while (p.tok.kind in Tk14 and indClass(p) in {icEq}):
        let m55 = mark(p)
        pExtraPostExprBlock p
        discardUnused m55
    else:
      error p, "expected postExprBlocks"
  else:
    error p, "expected postExprBlocks"
  discardUnused m0

proc pExprStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk4):
    pSimpleExpr(p, -1, pmTrySimple)
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pOptInd p
      pExpr p
      if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
        pPostExprBlocks p
      wrap p, m0, "asgn"
    elif (p.tok.kind in Tk2 and indClass(p) in {icNoInd}):
      checkInd p, {icNoInd}
      let m56 = mark(p)
      pExprEqExpr p
      while (p.tok.kind in {tkComma}):
        pComma p
        pExprEqExpr p
      discardUnused m56
      if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
        pPostExprBlocks p
      wrap p, m0, "cmd"
    elif (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
      if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
        pPostExprBlocks p
  else:
    error p, "expected exprStmt"
  discardUnused m0

proc pImportStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkImport}):
    expect p, tkImport
    if (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}) or (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pOptInd p
      if (p.tok.kind in Tk2):
        pExpr p
        if (p.tok.kind in {tkComma}):
          while (p.tok.kind in {tkComma}):
            let m57 = mark(p)
            pComma p
            pExpr p
            discardUnused m57
          wrap p, m0, "import"
        elif (p.tok.kind in {tkExcept}):
          expect p, tkExcept
          pOptInd p
          let m58 = mark(p)
          pExpr p
          while (p.tok.kind in {tkComma}):
            pComma p
            pExpr p
          discardUnused m58
          wrap p, m0, "importexcept"
        else:
          while (p.tok.kind in {tkComma}):
            let m59 = mark(p)
            pComma p
            pExpr p
            discardUnused m59
          wrap p, m0, "import"
      else:
        error p, "expected importStmt"
    else:
      error p, "expected importStmt"
  else:
    error p, "expected importStmt"
  discardUnused m0

proc pExportStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkExport}):
    expect p, tkExport
    if (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}) or (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pOptInd p
      if (p.tok.kind in Tk2):
        pExpr p
        if (p.tok.kind in {tkComma}):
          while (p.tok.kind in {tkComma}):
            let m60 = mark(p)
            pComma p
            pExpr p
            discardUnused m60
          wrap p, m0, "export"
        elif (p.tok.kind in {tkExcept}):
          expect p, tkExcept
          pOptInd p
          let m61 = mark(p)
          pExpr p
          while (p.tok.kind in {tkComma}):
            pComma p
            pExpr p
          discardUnused m61
          wrap p, m0, "exportexcept"
        else:
          while (p.tok.kind in {tkComma}):
            let m62 = mark(p)
            pComma p
            pExpr p
            discardUnused m62
          wrap p, m0, "export"
      else:
        error p, "expected exportStmt"
    else:
      error p, "expected exportStmt"
  else:
    error p, "expected exportStmt"
  discardUnused m0

proc pIncludeStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkInclude
  pOptInd p
  let m63 = mark(p)
  pExpr p
  while (p.tok.kind in {tkComma}):
    pComma p
    pExpr p
  discardUnused m63
  wrap p, m0, "include"
  discardUnused m0

proc pFromStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkFrom
  pExpr p
  expect p, tkImport
  pOptInd p
  pExpr p
  while (p.tok.kind in {tkComma}):
    let m64 = mark(p)
    pComma p
    pExpr p
    discardUnused m64
  wrap p, m0, "fromimport"
  discardUnused m0

proc pOptExprBody*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  elif (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pValidInd p
    pExpr p
    if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
      pPostExprBlocks p
  else:
    error p, "expected optExprBody"
  discardUnused m0

proc pReturnStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkReturn
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "ret"
  discardUnused m0

proc pRaiseStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkRaise
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "raise"
  discardUnused m0

proc pYieldStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkYield
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "yld"
  discardUnused m0

proc pDiscardStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDiscard
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "discard"
  discardUnused m0

proc pBreakStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBreak
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "break"
  discardUnused m0

proc pContinueStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkContinue
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk2 and indClass(p) in {icNoInd, icGt}):
    pOptExprBody p
  wrap p, m0, "continue"
  discardUnused m0

proc pCondStmt*(p: var Parser) =
  let m0 = mark(p)
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "elif"
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  while (p.tok.kind in {tkElif} and indClass(p) in {icNoInd, icEq}):
    let m65 = mark(p)
    pOptSameInd p
    expect p, tkElif
    pExpr p
    pColcom p
    pStmt p
    wrap p, m65, "elif"
    discardUnused m65
  if (p.tok.kind in {tkElse} and indClass(p) in {icNoInd, icEq}):
    pOptSameInd p
    expect p, tkElse
    pColcom p
    pStmt p
    wrap p, m0, "else"
  discardUnused m0

proc pIfStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkIf
  pCondStmt p
  wrap p, m0, "if"
  discardUnused m0

proc pWhenStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pCondStmt p
  wrap p, m0, "when"
  discardUnused m0

proc pCondExpr*(p: var Parser) =
  let m0 = mark(p)
  pOptInd p
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "elif"
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  while (p.tok.kind in {tkElif}):
    let m66 = mark(p)
    expect p, tkElif
    pOptInd p
    pExpr p
    pColcom p
    pStmt p
    wrap p, m66, "elif"
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
    discardUnused m66
  if (p.tok.kind in {tkElse}):
    expect p, tkElse
    pColcom p
    pStmt p
    wrap p, m0, "else"
  discardUnused m0

proc pIfExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkIf
  pCondExpr p
  wrap p, m0, "if"
  discardUnused m0

proc pWhenExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pCondExpr p
  wrap p, m0, "when"
  discardUnused m0

proc pWhileStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhile
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "while"
  discardUnused m0

proc pOfBranch*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkOf
  pExprList p
  pColcom p
  pStmt p
  wrap p, m0, "of"
  discardUnused m0

proc pOfBranches*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkOf}):
    pOfBranch p
    while (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
      let m67 = mark(p)
      checkInd p, {icEq}
      pOfBranch p
      discardUnused m67
    while (p.tok.kind in {tkElif} and indClass(p) in {icEq}):
      let m68 = mark(p)
      checkInd p, {icEq}
      expect p, tkElif
      pExpr p
      pColcom p
      pStmt p
      wrap p, m68, "elif"
      discardUnused m68
    if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      expect p, tkElse
      pColcom p
      pStmt p
      wrap p, m0, "else"
  elif (p.tok.kind in {tkElif}):
    expect p, tkElif
    pExpr p
    pColcom p
    pStmt p
    wrap p, m0, "elif"
    while (p.tok.kind in {tkElif}):
      let m69 = mark(p)
      expect p, tkElif
      pExpr p
      pColcom p
      pStmt p
      wrap p, m69, "elif"
      discardUnused m69
    if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      expect p, tkElse
      pColcom p
      pStmt p
      wrap p, m0, "else"
  elif (p.tok.kind in {tkElse}):
    expect p, tkElse
    pColcom p
    pStmt p
    wrap p, m0, "else"
  else:
    error p, "expected ofBranches"
  discardUnused m0

proc pCaseStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCase
  pExpr p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  let m70 = mark(p)
  if (p.tok.kind in {tkElif, tkElse, tkOf} and indClass(p) in {icGt}):
    pushInd p
    pOfBranches p
    popInd p
  elif (p.tok.kind in {tkElif, tkElse, tkOf} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    pOfBranches p
  else:
    error p, "expected alternative"
  discardUnused m70
  wrap p, m0, "case"
  discardUnused m0

proc pTryStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTry
  pColcom p
  pStmt p
  while (p.tok.kind in {tkExcept} and indClass(p) in {icNoInd, icEq}):
    let m71 = mark(p)
    pOptSameInd p
    expect p, tkExcept
    pOptionalExprList p
    pColcom p
    pStmt p
    wrap p, m71, "except"
    discardUnused m71
  if (p.tok.kind in {tkFinally} and indClass(p) in {icNoInd, icEq}):
    pOptSameInd p
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  wrap p, m0, "try"
  discardUnused m0

proc pTryExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTry
  pColcom p
  pStmt p
  while (p.tok.kind in {tkExcept}):
    let m72 = mark(p)
    expect p, tkExcept
    pOptionalExprList p
    pColcom p
    pStmt p
    wrap p, m72, "except"
    discardUnused m72
  if (p.tok.kind in {tkFinally}):
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  wrap p, m0, "try"
  discardUnused m0

proc pBlockStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBlock
  if (p.tok.kind in Tk13):
    pSymbol p
  pColcom p
  pStmt p
  wrap p, m0, "block"
  discardUnused m0

proc pBlockExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBlock
  if (p.tok.kind in Tk13):
    pSymbol p
  pColcom p
  pStmt p
  wrap p, m0, "block"
  discardUnused m0

proc pStaticStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkStatic
  pColcom p
  pStmt p
  wrap p, m0, "staticstmt"
  discardUnused m0

proc pDeferStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDefer
  pColcom p
  pStmt p
  wrap p, m0, "defer"
  discardUnused m0

proc pAsmStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkAsm
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  let m73 = mark(p)
  if (p.tok.kind in {tkStrLit}):
    emitLeaf p            # STR_LIT
  elif (p.tok.kind in {tkRStrLit}):
    emitLeaf p            # RSTR_LIT
  elif (p.tok.kind in {tkTripleStrLit}):
    emitLeaf p            # TRIPLESTR_LIT
  else:
    error p, "expected alternative"
  discardUnused m73
  wrap p, m0, "asm"
  discardUnused m0

proc pGenericParamName*(p: var Parser) =
  let m0 = mark(p)
  if ((p.tok.kind in {tkAddr..tkYield})) and inOrOut(p):
    emitLeaf p            # KEYW
    pPlainSymbol p
    wrap p, m0, "prefix"
  elif (p.tok.kind in {tkAccent, tkSymbol}):
    pPlainSymbol p
  else:
    error p, "expected genericParamName"
  discardUnused m0

proc pGenericParam*(p: var Parser) =
  let m0 = mark(p)
  pGenericParamName p
  while (p.tok.kind in {tkComma}):
    let m74 = mark(p)
    pComma p
    if canGenericParamName(p):
      pGenericParamName p
    discardUnused m74
  if (p.tok.kind in {tkColon}):
    pColon p
    pExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  wrap p, m0, "typevar"
  discardUnused m0

proc pGenericParamList*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  pOptInd p
  if (p.tok.kind in {tkAccent, tkAddr..tkYield, tkSymbol}):
    pGenericParam p
    while (p.tok.kind in {tkComma, tkSemiColon}):
      let m75 = mark(p)
      let m76 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m76
      if (p.tok.kind in {tkAccent, tkAddr..tkYield, tkSymbol}):
        pGenericParam p
      discardUnused m75
  pOptPar p
  expect p, tkBracketRi
  wrap p, m0, "typevars"
  discardUnused m0

proc pPattern*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCurlyLe
  pStmt p
  expect p, tkCurlyRi
  discardUnused m0

proc pIndAndComment*(p: var Parser) =
  let m0 = mark(p)
  let m77 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      pFlexComment p
  elif (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
  discardUnused m77
  discardUnused m0

proc pRoutineName*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk22):
    pSymbolOrKeyword p
    if (p.tok.kind in {tkOpr}):
      emitLeaf p            # OPR
      wrap p, m0, "postfix"
    else:
      discard
  else:
    error p, "expected routineName"
  discardUnused m0

proc pRoutine*(p: var Parser) =
  let m0 = mark(p)
  pOptInd p
  if (p.tok.kind in Tk22):
    pRoutineName p
    if (p.tok.kind in {tkCurlyLe}):
      pPattern p
    if (p.tok.kind in {tkBracketLe}):
      pGenericParamList p
  pParamListColon p
  if (p.tok.kind in {tkCurlyDotLe} and indClass(p) in {icNoInd, icGt}):
    pValidInd p
    pPragma p
  if (p.tok.kind in {tkEquals} and indClass(p) in {icNoInd, icGt}):
    pValidInd p
    expect p, tkEquals
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
    pStmt p
  pIndAndComment p
  discardUnused m0

proc pCommentStmt*(p: var Parser) =
  let m0 = mark(p)
  emitLeaf p            # COMMENT
  wrap p, m0, "comment"
  discardUnused m0

proc pEnumDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkEnum
  pOptInd p
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pFlexComment p
  pValidInd p
  pSymbol p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pFlexComment p
  while (p.tok.kind in Tk13 and indClass(p) in {icNoInd, icGt}):
    let m78 = mark(p)
    pValidInd p
    pSymbol p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pOptInd p
      pExpr p
    if (p.tok.kind in {tkComma}):
      pComma p
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      pFlexComment p
    discardUnused m78
  wrap p, m0, "enum"
  discardUnused m0

proc pObjectWhen*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pExpr p
  pColcom p
  pObjectPart p
  wrap p, m0, "elif"
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pFlexComment p
  while (p.tok.kind in {tkElif}):
    let m79 = mark(p)
    expect p, tkElif
    pExpr p
    pColcom p
    pObjectPart p
    wrap p, m79, "elif"
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      pFlexComment p
    discardUnused m79
  if (p.tok.kind in {tkElse}):
    expect p, tkElse
    pColcom p
    pObjectPart p
    wrap p, m0, "else"
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
      pFlexComment p
  wrap p, m0, "when"
  discardUnused m0

proc pObjectBranch*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkOf
  pExprList p
  pColcom p
  pObjectPart p
  wrap p, m0, "of"
  discardUnused m0

proc pObjectBranches*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkOf}):
    pObjectBranch p
    while (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
      let m80 = mark(p)
      checkInd p, {icEq}
      pObjectBranch p
      discardUnused m80
    if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      expect p, tkElse
      pColcom p
      pObjectPart p
      wrap p, m0, "else"
  elif (p.tok.kind in {tkElse}):
    expect p, tkElse
    pColcom p
    pObjectPart p
    wrap p, m0, "else"
  else:
    error p, "expected objectBranches"
  discardUnused m0

proc pObjectCase*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCase
  if (p.tok.kind in {tkAccent, tkCurlyDotLe, tkSymbol}):
    let m81 = mark(p)
    if (p.tok.kind in {tkAccent, tkSymbol}):
      pDeclColonEquals p
    elif (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    else:
      error p, "expected alternative"
    discardUnused m81
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pFlexComment p
  let m82 = mark(p)
  if (p.tok.kind in {tkElse, tkOf} and indClass(p) in {icGt}):
    pushInd p
    pObjectBranches p
    popInd p
  elif (p.tok.kind in {tkElse, tkOf} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    pObjectBranches p
  else:
    error p, "expected alternative"
  discardUnused m82
  wrap p, m0, "case"
  discardUnused m0

proc pObjectPart*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk23 and indClass(p) in {icGt}):
    pushInd p
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq}):
      pOptSameInd p
      emitLeaf p            # COMMENT
    let m83 = mark(p)
    pObjectPart p
    while (p.tok.kind in Tk24 and indClass(p) in {icEq}):
      checkInd p, {icEq}
      pObjectPart p
    if ((p.tok.kind in Tk24)) and indClass(p) == icGt:
      error p, "invalid indentation in objectPart"
    discardUnused m83
    popInd p
    wrap p, m0, "stmts"
  elif (p.tok.kind in Tk24 and indClass(p) in {icNoInd, icEq}):
    pOptSameInd p
    if (p.tok.kind in {tkWhen}):
      pObjectWhen p
    elif (p.tok.kind in {tkCase}):
      pObjectCase p
    elif (p.tok.kind in {tkNil}):
      expect p, tkNil
    elif (p.tok.kind in {tkDiscard}):
      expect p, tkDiscard
    elif (p.tok.kind in {tkAccent, tkSymbol}):
      pDeclColonEquals p
      if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icEq, icGt}):
        pOptPar p
        emitLeaf p            # COMMENT
    else:
      error p, "expected objectPart"
  else:
    discard
  discardUnused m0

proc pObjectDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkObject
  if (p.tok.kind in {tkOf} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    expect p, tkOf
    pTypeDesc p
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  if (p.tok.kind in Tk23 and indClass(p) in {icGt}):
    checkInd p, {icGt}
    pObjectPart p
  wrap p, m0, "object"
  discardUnused m0

proc pConceptParam*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk25):
    let m84 = mark(p)
    if (p.tok.kind in {tkVar}):
      expect p, tkVar
    elif (p.tok.kind in {tkOut}):
      expect p, tkOut
    elif (p.tok.kind in {tkPtr}):
      expect p, tkPtr
    elif (p.tok.kind in {tkRef}):
      expect p, tkRef
    elif (p.tok.kind in {tkStatic}):
      expect p, tkStatic
    elif (p.tok.kind in {tkType}):
      expect p, tkType
    else:
      error p, "expected alternative"
    discardUnused m84
  pSymbol p
  discardUnused m0

proc pConceptDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkConcept
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  if (p.tok.kind in Tk26 and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    if (p.tok.kind in Tk26):
      let m85 = mark(p)
      pConceptParam p
      while (p.tok.kind in {tkComma}):
        expect p, tkComma
        pConceptParam p
      discardUnused m85
  if (p.tok.kind in {tkCurlyDotLe} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pPragma p
  if (p.tok.kind in {tkOf} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    expect p, tkOf
    if (p.tok.kind in Tk4):
      let m86 = mark(p)
      pTypeDesc p
      while (p.tok.kind in {tkComma}):
        expect p, tkComma
        pTypeDesc p
      discardUnused m86
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  if (p.tok.kind in Tk8 and indClass(p) in {icGt}):
    checkInd p, {icGt}
    pStmt p
  wrap p, m0, "concept"
  discardUnused m0

proc pTypeDef*(p: var Parser) =
  let m0 = mark(p)
  pIdentVisDot p
  if (p.tok.kind in {tkBracketLe}):
    pGenericParamList p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pTypeDefValue p
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd, icGt}):
    pIndAndComment p
  wrap p, m0, "type"
  discardUnused m0

proc pTypeDefValue*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkConcept, tkEnum, tkObject, tkTuple}):
    let m87 = mark(p)
    if (p.tok.kind in {tkTuple}):
      pTupleDecl p
    elif (p.tok.kind in {tkEnum}):
      pEnumDecl p
    elif (p.tok.kind in {tkObject}):
      pObjectDecl p
    elif (p.tok.kind in {tkConcept}):
      pConceptDecl p
    else:
      error p, "expected alternative"
    discardUnused m87
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  else:
    pSimpleExpr(p, -1, pmTypeDef)
    while (p.tok.kind in {tkComma}):
      let m88 = mark(p)
      pComma p
      pExprEqExpr p
      discardUnused m88
    if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
      pPostExprBlocks p
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  discardUnused m0

proc pVarTupleLhs*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkParLe
  pOptInd p
  let m89 = mark(p)
  if (p.tok.kind in {tkAccent, tkSymbol}):
    pIdentWithPragmaDot p
  elif (p.tok.kind in {tkParLe}):
    pVarTupleLhs p
  else:
    error p, "expected alternative"
  discardUnused m89
  while (p.tok.kind in {tkComma}):
    let m90 = mark(p)
    pComma p
    if (p.tok.kind in {tkAccent, tkParLe, tkSymbol}):
      let m91 = mark(p)
      if (p.tok.kind in {tkAccent, tkSymbol}):
        pIdentWithPragmaDot p
      elif (p.tok.kind in {tkParLe}):
        pVarTupleLhs p
      else:
        error p, "expected alternative"
      discardUnused m91
    discardUnused m90
  pOptPar p
  expect p, tkParRi
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  wrap p, m0, "unpacktup"
  discardUnused m0

proc pVarTuple*(p: var Parser) =
  let m0 = mark(p)
  pVarTupleLhs p
  expect p, tkEquals
  pOptInd p
  pExpr p
  wrap p, m0, "unpackdecl"
  discardUnused m0

proc pVariable*(p: var Parser) =
  let m0 = mark(p)
  let m92 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTuple p
  elif (p.tok.kind in {tkAccent, tkSymbol}):
    pDeclColonEqualsDot p
  else:
    error p, "expected alternative"
  discardUnused m92
  if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
    pPostExprBlocks p
  pIndAndComment p
  discardUnused m0

proc pConstant*(p: var Parser) =
  let m0 = mark(p)
  let m93 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTupleLhs p
  elif (p.tok.kind in {tkAccent, tkSymbol}):
    pIdentWithPragma p
    if (p.tok.kind in {tkColon}):
      pColon p
      pTypeDesc p
  else:
    error p, "expected alternative"
  discardUnused m93
  expect p, tkEquals
  pOptInd p
  pExpr p
  if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
    pPostExprBlocks p
  pIndAndComment p
  discardUnused m0

proc pBindStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBind
  pOptInd p
  let m94 = mark(p)
  pQualifiedIdent p
  while (p.tok.kind in {tkComma}):
    pComma p
    pQualifiedIdent p
  discardUnused m94
  wrap p, m0, "bind"
  discardUnused m0

proc pMixinStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkMixin
  pOptInd p
  let m95 = mark(p)
  pQualifiedIdent p
  while (p.tok.kind in {tkComma}):
    pComma p
    pQualifiedIdent p
  discardUnused m95
  wrap p, m0, "mixin"
  discardUnused m0

proc pPragmaStmt*(p: var Parser) =
  let m0 = mark(p)
  pPragma p
  if (p.tok.kind in {tkColon} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    expect p, tkColon
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
    pStmt p
  discardUnused m0

proc pSimpleStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk27):
    let m96 = mark(p)
    if (p.tok.kind in {tkReturn}):
      pReturnStmt p
    elif (p.tok.kind in {tkRaise}):
      pRaiseStmt p
    elif (p.tok.kind in {tkYield}):
      pYieldStmt p
    elif (p.tok.kind in {tkDiscard}):
      pDiscardStmt p
    elif (p.tok.kind in {tkBreak}):
      pBreakStmt p
    elif (p.tok.kind in {tkContinue}):
      pContinueStmt p
    elif (p.tok.kind in {tkCurlyDotLe}):
      pPragmaStmt p
    elif (p.tok.kind in {tkImport}):
      pImportStmt p
    elif (p.tok.kind in {tkExport}):
      pExportStmt p
    elif (p.tok.kind in {tkFrom}):
      pFromStmt p
    elif (p.tok.kind in {tkInclude}):
      pIncludeStmt p
    elif (p.tok.kind in {tkComment}):
      pCommentStmt p
    else:
      error p, "expected alternative"
    discardUnused m96
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
  else:
    pExprStmt p
    if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
      pTrailComment p
  discardUnused m0

proc pComplexOrSimpleStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk28):
    let m97 = mark(p)
    if (p.tok.kind in {tkIf}):
      pIfStmt p
    elif (p.tok.kind in {tkWhen}):
      pWhenStmt p
    elif (p.tok.kind in {tkWhile}):
      pWhileStmt p
    elif (p.tok.kind in {tkTry}):
      pTryStmt p
    elif (p.tok.kind in {tkFor}):
      pForStmt p
    elif (p.tok.kind in {tkBlock}):
      pBlockStmt p
    elif (p.tok.kind in {tkStatic}):
      pStaticStmt p
    elif (p.tok.kind in {tkDefer}):
      pDeferStmt p
    elif (p.tok.kind in {tkAsm}):
      pAsmStmt p
    elif (p.tok.kind in {tkBind}):
      pBindStmt p
    elif (p.tok.kind in {tkMixin}):
      pMixinStmt p
    elif (p.tok.kind in {tkCase}):
      pCaseStmt p
    else:
      error p, "expected alternative"
    discardUnused m97
  elif (p.tok.kind in {tkExcept}):
    expect p, tkExcept
    pColcom p
    pStmt p
    wrap p, m0, "except"
  elif (p.tok.kind in {tkFinally}):
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  elif (p.tok.kind in {tkProc}):
    expect p, tkProc
    pRoutine p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkMethod}):
    expect p, tkMethod
    pRoutine p
    wrap p, m0, "method"
  elif (p.tok.kind in {tkFunc}):
    expect p, tkFunc
    pRoutine p
    wrap p, m0, "func"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pRoutine p
    wrap p, m0, "iterator"
  elif (p.tok.kind in {tkMacro}):
    expect p, tkMacro
    pRoutine p
    wrap p, m0, "macro"
  elif (p.tok.kind in {tkTemplate}):
    expect p, tkTemplate
    pRoutine p
    wrap p, m0, "template"
  elif (p.tok.kind in {tkConverter}):
    expect p, tkConverter
    pRoutine p
    wrap p, m0, "converter"
  elif (p.tok.kind in {tkType}):
    expect p, tkType
    if (p.tok.kind in {tkAccent, tkComment, tkSymbol} and indClass(p) in {icNoInd, icGt}):
      pSection_typeDef p
    elif (p.tok.kind in {tkParLe}):
      expect p, tkParLe
      pPrimary(p, pmTypeDesc)
      expect p, tkParRi
      wrap p, m0, "typeof"
      var prec98 = getPrecedence(p)
      while prec98 >= -1 and indClass(p) == icNoInd:
        let assoc98 = (if isRightAssoc(p): 0 else: 1)
        insertLeafAt p, m0, p.tok.s
        getTok p
        pSimpleExpr(p, prec98 + assoc98, pmNormal)
        wrap p, m0, "infix"
        prec98 = getPrecedence(p)
      if (p.tok.kind in {tkColon, tkDo} and indClass(p) in {icNoInd}):
        pPostExprBlocks p
    else:
      error p, "expected complexOrSimpleStmt"
  elif (p.tok.kind in {tkConst}):
    expect p, tkConst
    pSection_constant p
  elif (p.tok.kind in {tkLet}):
    expect p, tkLet
    pSection_variable p
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
    pSection_variable p
  elif (p.tok.kind in {tkUsing}):
    expect p, tkUsing
    pSection_variable p
  else:
    pSimpleStmt p
  discardUnused m0

proc pStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk8 and indClass(p) in {icGt}):
    pushInd p
    pComplexOrSimpleStmt p
    while (p.tok.kind in Tk8 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m99 = mark(p)
      let m100 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m100
      if (p.tok.kind in Tk8):
        pComplexOrSimpleStmt p
      discardUnused m99
    popInd p
  elif (p.tok.kind in Tk21 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    let m101 = mark(p)
    pSimpleStmt p
    while (p.tok.kind in {tkSemiColon}):
      expect p, tkSemiColon
      pSimpleStmt p
    discardUnused m101
  else:
    error p, "expected stmt"
  discardUnused m0

proc pSection_typeDef*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  let m102 = mark(p)
  if (p.tok.kind in {tkAccent, tkComment, tkSymbol} and indClass(p) in {icGt}):
    pushInd p
    let m103 = mark(p)
    let m104 = mark(p)
    if (p.tok.kind in {tkAccent, tkSymbol}):
      pTypeDef p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m104
    while (p.tok.kind in {tkAccent, tkComment, tkSymbol} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m105 = mark(p)
      if (p.tok.kind in {tkAccent, tkSymbol}):
        pTypeDef p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m105
    if ((p.tok.kind in {tkAccent, tkComment, tkSymbol})) and indClass(p) == icGt:
      error p, "invalid indentation in section_typeDef"
    discardUnused m103
    popInd p
  elif (p.tok.kind in {tkAccent, tkSymbol} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pTypeDef p
  else:
    error p, "expected alternative"
  discardUnused m102
  discardUnused m0

proc pSection_constant*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  let m106 = mark(p)
  if (p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol} and indClass(p) in {icGt}):
    pushInd p
    let m107 = mark(p)
    let m108 = mark(p)
    if (p.tok.kind in {tkAccent, tkParLe, tkSymbol}):
      pConstant p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m108
    while (p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m109 = mark(p)
      if (p.tok.kind in {tkAccent, tkParLe, tkSymbol}):
        pConstant p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m109
    if ((p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol})) and indClass(p) == icGt:
      error p, "invalid indentation in section_constant"
    discardUnused m107
    popInd p
  elif (p.tok.kind in {tkAccent, tkParLe, tkSymbol} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pConstant p
  else:
    error p, "expected alternative"
  discardUnused m106
  discardUnused m0

proc pSection_variable*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icNoInd}):
    pTrailComment p
  let m110 = mark(p)
  if (p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol} and indClass(p) in {icGt}):
    pushInd p
    let m111 = mark(p)
    let m112 = mark(p)
    if (p.tok.kind in {tkAccent, tkParLe, tkSymbol}):
      pVariable p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m112
    while (p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m113 = mark(p)
      if (p.tok.kind in {tkAccent, tkParLe, tkSymbol}):
        pVariable p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m113
    if ((p.tok.kind in {tkAccent, tkComment, tkParLe, tkSymbol})) and indClass(p) == icGt:
      error p, "invalid indentation in section_variable"
    discardUnused m111
    popInd p
  elif (p.tok.kind in {tkAccent, tkParLe, tkSymbol} and indClass(p) in {icNoInd}):
    checkInd p, {icNoInd}
    pVariable p
  else:
    error p, "expected alternative"
  discardUnused m110
  discardUnused m0

