## GENERATED by src/nifler2/tools/gramcheck.nim -- do not edit.
## One proc per rule; the dispatch is an if-chain over
## (token kind, indentation class).

import parserrt
export parserrt

const
  Tk1 = {tkAccent, tkAddr, tkAnd, tkAs, tkBlock, tkBracketLe, tkCase, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkWhen, tkXor}
  Tk2 = {tkAccent, tkAddr, tkAnd, tkAs, tkBracketLe, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkXor}
  Tk3 = {tkAccent, tkAddr, tkBracketLe, tkCast, tkCharLit, tkCurlyLe, tkCustomLit, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkGStrLit, tkGTripleStrLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkParLe, tkRStrLit, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk4 = {tkAnd, tkAs, tkDiv, tkDotDot, tkFrom, tkIn, tkIs, tkIsnot, tkMod, tkNot, tkNotin, tkOf, tkOpr, tkOr, tkShl, tkShr, tkXor}
  Tk5 = {tkDistinct, tkEnum, tkObject, tkOut, tkPtr, tkRef, tkTuple, tkVar}
  Tk6 = {tkAccent, tkAddr, tkAnd, tkAs, tkAsm, tkBind, tkBlock, tkBracketLe, tkBreak, tkCase, tkCast, tkCharLit, tkComment, tkConst, tkContinue, tkConverter, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDefer, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExcept, tkExport, tkFinally, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkLet, tkMacro, tkMethod, tkMixin, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTemplate, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkUsing, tkVar, tkWhen, tkWhile, tkXor, tkYield}
  Tk7 = {tkAccent, tkAddr, tkAnd, tkAs, tkAsm, tkBind, tkBlock, tkBracketLe, tkBreak, tkCase, tkCast, tkCharLit, tkComment, tkConst, tkContinue, tkConverter, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDefer, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExcept, tkExport, tkFinally, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkLet, tkMacro, tkMethod, tkMixin, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkSemiColon, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTemplate, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkUsing, tkVar, tkWhen, tkWhile, tkXor, tkYield}
  Tk8 = {tkCharLit, tkCustomLit, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkNil, tkRStrLit, tkStrLit, tkTripleStrLit, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit}
  Tk9 = {tkAnd, tkAs, tkBracketLe, tkBracketRi, tkCurlyLe, tkCurlyRi, tkDiv, tkDotDot, tkEquals, tkFrom, tkIn, tkIs, tkIsnot, tkMod, tkNot, tkNotin, tkOf, tkOpr, tkOr, tkParLe, tkParRi, tkShl, tkShr, tkXor}
  Tk10 = {tkAddr..tkYield, tkAnd, tkAs, tkBracketLe, tkBracketRi, tkCharLit, tkCurlyLe, tkCurlyRi, tkCustomLit, tkDiv, tkDotDot, tkEquals, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkMod, tkNil, tkNot, tkNotin, tkOf, tkOpr, tkOr, tkParLe, tkParRi, tkRStrLit, tkShl, tkShr, tkStrLit, tkSymbol, tkTripleStrLit, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkXor}
  Tk11 = {tkAccent, tkAddr, tkStatic, tkSymbol, tkType}
  Tk12 = {tkDo, tkElif, tkElse, tkExcept, tkFinally, tkOf}
  Tk13 = {tkAccent, tkAddr, tkAnd, tkAs, tkBlock, tkBracketLe, tkCase, tkCast, tkCharLit, tkCurlyLe, tkCurlyRi, tkCustomLit, tkDistinct, tkDiv, tkDotDot, tkEnum, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkIn, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRef, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkWhen, tkXor}
  Tk14 = {tkAccent, tkAddr, tkAnd, tkAs, tkAsm, tkBind, tkBlock, tkBracketLe, tkBreak, tkCase, tkCast, tkCharLit, tkConst, tkContinue, tkConverter, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDefer, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExcept, tkExport, tkFinally, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFor, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkIf, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkLet, tkMacro, tkMethod, tkMixin, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkSemiColon, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTemplate, tkTripleStrLit, tkTry, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkUsing, tkVar, tkWhen, tkWhile, tkXor, tkYield}
  Tk15 = {tkDistinct, tkEnum, tkIterator, tkObject, tkOut, tkProc, tkPtr, tkRef, tkTuple, tkVar}
  Tk16 = {tkBlock, tkCase, tkFor, tkIf, tkTry, tkWhen}
  Tk17 = {tkAsm, tkBind, tkBlock, tkCase, tkConst, tkConverter, tkDefer, tkExcept, tkFinally, tkFor, tkIf, tkLet, tkMacro, tkMethod, tkMixin, tkTemplate, tkTry, tkUsing, tkWhen, tkWhile}
  Tk18 = {tkAccent, tkAddr, tkAnd, tkAs, tkBracketLe, tkBreak, tkCast, tkCharLit, tkComment, tkContinue, tkCurlyDotLe, tkCurlyLe, tkCustomLit, tkDiscard, tkDistinct, tkDiv, tkDotDot, tkEnum, tkExport, tkFloat128Lit, tkFloat32Lit, tkFloat64Lit, tkFloatLit, tkFrom, tkFunc, tkGStrLit, tkGTripleStrLit, tkImport, tkIn, tkInclude, tkInt16Lit, tkInt32Lit, tkInt64Lit, tkInt8Lit, tkIntLit, tkIs, tkIsnot, tkIterator, tkMod, tkNil, tkNot, tkNotin, tkObject, tkOf, tkOpr, tkOr, tkOut, tkParLe, tkProc, tkPtr, tkRStrLit, tkRaise, tkRef, tkReturn, tkShl, tkShr, tkStatic, tkStrLit, tkSymbol, tkTripleStrLit, tkTuple, tkType, tkUInt16Lit, tkUInt32Lit, tkUInt64Lit, tkUInt8Lit, tkUIntLit, tkVar, tkXor, tkYield}
  Tk19 = {tkAccent, tkAddr, tkCurlyDotLe, tkStatic, tkSymbol, tkType}
  Tk20 = {tkAccent, tkAddr, tkCase, tkDiscard, tkNil, tkStatic, tkSymbol, tkType, tkWhen}
  Tk21 = {tkOut, tkPtr, tkRef, tkStatic, tkType, tkVar}
  Tk22 = {tkAccent, tkAddr, tkOut, tkPtr, tkRef, tkStatic, tkSymbol, tkType, tkVar}
  Tk23 = {tkConcept, tkDistinct, tkEnum, tkObject, tkPtr, tkRef, tkTuple}
  Tk24 = {tkBreak, tkComment, tkContinue, tkCurlyDotLe, tkDiscard, tkExport, tkFrom, tkImport, tkInclude, tkRaise, tkReturn, tkYield}
  Tk25 = {tkAsm, tkBind, tkBlock, tkCase, tkDefer, tkFor, tkIf, tkMixin, tkStatic, tkTry, tkWhen, tkWhile}
  Tk26 = {tkAccent, tkAddr, tkComment, tkStatic, tkSymbol, tkType}
  Tk27 = {tkAccent, tkAddr, tkComment, tkParLe, tkStatic, tkSymbol, tkType}
  Tk28 = {tkAccent, tkAddr, tkParLe, tkStatic, tkSymbol, tkType}

proc canPrimarySuffix*(p: Parser; mode: PrimaryMode): bool
proc canCommandParam*(p: Parser; mode: PrimaryMode): bool
proc canPrimary*(p: Parser; mode: PrimaryMode): bool
proc canPrimarySuffix*(p: Parser; mode: PrimaryMode): bool =
  (((p.tok.kind in {tkParLe})) and noSpaceBefore(p)) or ((p.tok.kind in {tkDot})) or ((((p.tok.kind == tkOpr and isDotLike(p.tok)))) and dotLikeOps(p)) or (((p.tok.kind in {tkBracketLe})) and noSpaceBefore(p)) or (((p.tok.kind in {tkCurlyLe})) and noSpaceBefore(p)) or (((p.tok.kind in Tk1)) and commandStart(p) and commandAllowed(p, mode))

proc canCommandParam*(p: Parser; mode: PrimaryMode): bool =
  (((p.tok.kind in Tk2)) and inTypeDesc(p, mode)) or ((p.tok.kind in Tk1))

proc canPrimary*(p: Parser; mode: PrimaryMode): bool =
  ((p.tok.kind in Tk3)) or (((p.tok.kind in Tk4)) and isSigilLike(p)) or (((p.tok.kind in Tk4)) and isUnary(p)) or ((p.tok.kind in {tkFunc, tkIterator, tkProc})) or ((p.tok.kind in Tk5)) or ((p.tok.kind in Tk4))

proc pModule*(p: var Parser)
proc pComma*(p: var Parser)
proc pSemicolon*(p: var Parser)
proc pColon*(p: var Parser)
proc pColcom*(p: var Parser)
proc pValidInd*(p: var Parser)
proc pOptSameInd*(p: var Parser)
proc pNotInd*(p: var Parser)
proc pOptInd*(p: var Parser)
proc pOptPar*(p: var Parser)
proc pOperator*(p: var Parser)
proc pPrefixOperator*(p: var Parser)
proc pOperatorB*(p: var Parser)
proc pSymbol*(p: var Parser)
proc pSymbolOrKeyword*(p: var Parser)
proc pLiteral*(p: var Parser)
proc pGeneralizedLit*(p: var Parser)
proc pExprColonEqExpr*(p: var Parser)
proc pExprEqExpr*(p: var Parser)
proc pExprList*(p: var Parser)
proc pOptionalExprList*(p: var Parser)
proc pExprColonEqExprList*(p: var Parser)
proc pQualifiedIdent*(p: var Parser)
proc pSetOrTableConstr*(p: var Parser)
proc pCastExpr*(p: var Parser)
proc pParKeyw*(p: var Parser)
proc pPar*(p: var Parser)
proc pTupleConstr*(p: var Parser)
proc pArrayConstr*(p: var Parser)
proc pIdentOrLiteral*(p: var Parser)
proc pPrimarySuffix*(p: var Parser; anchor: Mark; mode: PrimaryMode)
proc pPragma*(p: var Parser)
proc pIdentVis*(p: var Parser)
proc pIdentVisDot*(p: var Parser)
proc pIdentWithPragma*(p: var Parser)
proc pIdentWithPragmaDot*(p: var Parser)
proc pDeclColonEquals*(p: var Parser)
proc pIdentColonEquals*(p: var Parser)
proc pTupleTypeBracket*(p: var Parser)
proc pTupleType*(p: var Parser)
proc pTupleDecl*(p: var Parser)
proc pParamList*(p: var Parser)
proc pParamListArrow*(p: var Parser)
proc pParamListColon*(p: var Parser)
proc pDoBlock*(p: var Parser)
proc pRoutineExpr*(p: var Parser)
proc pRoutineType*(p: var Parser)
proc pRawTypeDesc*(p: var Parser)
proc pTypeDescKeyw*(p: var Parser)
proc pTypeDescExpr*(p: var Parser)
proc pTypeDesc*(p: var Parser)
proc pForStmt*(p: var Parser)
proc pForExpr*(p: var Parser)
proc pExpr*(p: var Parser)
proc pSimplePrimary*(p: var Parser; mode: PrimaryMode)
proc pCommandParam*(p: var Parser; mode: PrimaryMode)
proc pPrimary*(p: var Parser; mode: PrimaryMode)
proc pSimpleExpr*(p: var Parser; limit: int, mode: PrimaryMode)
proc pPrimaryPragma*(p: var Parser; mode: PrimaryMode)
proc pExtraPostExprBlock*(p: var Parser)
proc pPostExprBlocks*(p: var Parser)
proc pExprStmt*(p: var Parser)
proc pImportStmt*(p: var Parser)
proc pExportStmt*(p: var Parser)
proc pIncludeStmt*(p: var Parser)
proc pFromStmt*(p: var Parser)
proc pReturnStmt*(p: var Parser)
proc pRaiseStmt*(p: var Parser)
proc pYieldStmt*(p: var Parser)
proc pDiscardStmt*(p: var Parser)
proc pBreakStmt*(p: var Parser)
proc pContinueStmt*(p: var Parser)
proc pCondStmt*(p: var Parser)
proc pIfStmt*(p: var Parser)
proc pWhenStmt*(p: var Parser)
proc pCondExpr*(p: var Parser)
proc pIfExpr*(p: var Parser)
proc pWhenExpr*(p: var Parser)
proc pWhileStmt*(p: var Parser)
proc pOfBranch*(p: var Parser)
proc pOfBranches*(p: var Parser)
proc pCaseStmt*(p: var Parser)
proc pTryStmt*(p: var Parser)
proc pTryExpr*(p: var Parser)
proc pBlockStmt*(p: var Parser)
proc pBlockExpr*(p: var Parser)
proc pStaticStmt*(p: var Parser)
proc pDeferStmt*(p: var Parser)
proc pAsmStmt*(p: var Parser)
proc pGenericParam*(p: var Parser)
proc pGenericParamList*(p: var Parser)
proc pPattern*(p: var Parser)
proc pIndAndComment*(p: var Parser)
proc pRoutine*(p: var Parser)
proc pCommentStmt*(p: var Parser)
proc pEnumDecl*(p: var Parser)
proc pObjectWhen*(p: var Parser)
proc pObjectBranch*(p: var Parser)
proc pObjectBranches*(p: var Parser)
proc pObjectCase*(p: var Parser)
proc pObjectPart*(p: var Parser)
proc pObjectDecl*(p: var Parser)
proc pConceptParam*(p: var Parser)
proc pConceptDecl*(p: var Parser)
proc pTypeDef*(p: var Parser)
proc pTypeDefValue*(p: var Parser)
proc pVarTupleLhs*(p: var Parser)
proc pVarTuple*(p: var Parser)
proc pColonBody*(p: var Parser)
proc pVariable*(p: var Parser)
proc pConstant*(p: var Parser)
proc pBindStmt*(p: var Parser)
proc pMixinStmt*(p: var Parser)
proc pPragmaStmt*(p: var Parser)
proc pSimpleStmt*(p: var Parser)
proc pComplexOrSimpleStmt*(p: var Parser)
proc pStmt*(p: var Parser)
proc pSection_typeDef*(p: var Parser)
proc pSection_constant*(p: var Parser)
proc pSection_variable*(p: var Parser)

proc pModule*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk6):
    let m1 = mark(p)
    pComplexOrSimpleStmt p
    while (p.tok.kind in Tk6 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m2 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m2
      pComplexOrSimpleStmt p
    if ((p.tok.kind in Tk7)) and indClass(p) == icGt:
      error p, "invalid indentation in module"
    discardUnused m1
  wrap p, m0, "stmts"
  discardUnused m0

proc pComma*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkComma
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  discardUnused m0

proc pSemicolon*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkSemiColon
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  discardUnused m0

proc pColon*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkColon
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  discardUnused m0

proc pColcom*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkColon
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  discardUnused m0

proc pValidInd*(p: var Parser) =
  let m0 = mark(p)
  let m3 = mark(p)
  checkInd p, {icNoInd, icGt}
  discardUnused m3
  discardUnused m0

proc pOptSameInd*(p: var Parser) =
  let m0 = mark(p)
  let m4 = mark(p)
  checkInd p, {icNoInd, icEq}
  discardUnused m4
  discardUnused m0

proc pNotInd*(p: var Parser) =
  let m0 = mark(p)
  let m5 = mark(p)
  checkInd p, {icNoInd, icLt, icEq}
  discardUnused m5
  discardUnused m0

proc pOptInd*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  pValidInd p
  discardUnused m0

proc pOptPar*(p: var Parser) =
  let m0 = mark(p)
  let m6 = mark(p)
  checkInd p, {icNoInd, icEq, icGt}
  discardUnused m6
  discardUnused m0

proc pOperator*(p: var Parser) =
  let m0 = mark(p)
  let m7 = mark(p)
  if (p.tok.kind in {tkOpr}):
    emitLeaf p            # OPR
  elif (p.tok.kind in {tkOr}):
    expect p, tkOr
  elif (p.tok.kind in {tkXor}):
    expect p, tkXor
  elif (p.tok.kind in {tkAnd}):
    expect p, tkAnd
  elif (p.tok.kind in {tkIs}):
    expect p, tkIs
  elif (p.tok.kind in {tkIsnot}):
    expect p, tkIsnot
  elif (p.tok.kind in {tkIn}):
    expect p, tkIn
  elif (p.tok.kind in {tkNotin}):
    expect p, tkNotin
  elif (p.tok.kind in {tkOf}):
    expect p, tkOf
  elif (p.tok.kind in {tkAs}):
    expect p, tkAs
  elif (p.tok.kind in {tkFrom}):
    expect p, tkFrom
  elif (p.tok.kind in {tkDiv}):
    expect p, tkDiv
  elif (p.tok.kind in {tkMod}):
    expect p, tkMod
  elif (p.tok.kind in {tkShl}):
    expect p, tkShl
  elif (p.tok.kind in {tkShr}):
    expect p, tkShr
  elif (p.tok.kind in {tkNot}):
    expect p, tkNot
  elif (p.tok.kind in {tkDotDot}):
    expect p, tkDotDot
  else:
    error p, "expected alternative"
  discardUnused m7
  discardUnused m0

proc pPrefixOperator*(p: var Parser) =
  let m0 = mark(p)
  pOperator p
  discardUnused m0

proc pOperatorB*(p: var Parser) =
  let m0 = mark(p)
  pOperator p
  discardUnused m0

proc pSymbol*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkAccent}):
    expect p, tkAccent
    let m9 = mark(p)
    if (p.tok.kind in {tkAddr..tkYield}):
      emitLeaf p            # KEYW
    elif (p.tok.kind in {tkSymbol}):
      emitLeaf p            # IDENT
    elif (p.tok.kind in Tk8):
      pLiteral p
    elif (p.tok.kind in Tk9):
      let m11 = mark(p)
      if (p.tok.kind in Tk4):
        pOperator p
      elif (p.tok.kind in {tkParLe}):
        expect p, tkParLe
      elif (p.tok.kind in {tkParRi}):
        expect p, tkParRi
      elif (p.tok.kind in {tkBracketLe}):
        expect p, tkBracketLe
      elif (p.tok.kind in {tkBracketRi}):
        expect p, tkBracketRi
      elif (p.tok.kind in {tkCurlyLe}):
        expect p, tkCurlyLe
      elif (p.tok.kind in {tkCurlyRi}):
        expect p, tkCurlyRi
      elif (p.tok.kind in {tkEquals}):
        expect p, tkEquals
      else:
        error p, "expected alternative"
      discardUnused m11
      while (p.tok.kind in Tk9):
        let m10 = mark(p)
        let m12 = mark(p)
        if (p.tok.kind in Tk4):
          pOperator p
        elif (p.tok.kind in {tkParLe}):
          expect p, tkParLe
        elif (p.tok.kind in {tkParRi}):
          expect p, tkParRi
        elif (p.tok.kind in {tkBracketLe}):
          expect p, tkBracketLe
        elif (p.tok.kind in {tkBracketRi}):
          expect p, tkBracketRi
        elif (p.tok.kind in {tkCurlyLe}):
          expect p, tkCurlyLe
        elif (p.tok.kind in {tkCurlyRi}):
          expect p, tkCurlyRi
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
        else:
          error p, "expected alternative"
        discardUnused m12
        discardUnused m10
    else:
      error p, "expected alternative"
    discardUnused m9
    while (p.tok.kind in Tk10):
      let m8 = mark(p)
      let m13 = mark(p)
      if (p.tok.kind in {tkAddr..tkYield}):
        emitLeaf p            # KEYW
      elif (p.tok.kind in {tkSymbol}):
        emitLeaf p            # IDENT
      elif (p.tok.kind in Tk8):
        pLiteral p
      elif (p.tok.kind in Tk9):
        let m15 = mark(p)
        if (p.tok.kind in Tk4):
          pOperator p
        elif (p.tok.kind in {tkParLe}):
          expect p, tkParLe
        elif (p.tok.kind in {tkParRi}):
          expect p, tkParRi
        elif (p.tok.kind in {tkBracketLe}):
          expect p, tkBracketLe
        elif (p.tok.kind in {tkBracketRi}):
          expect p, tkBracketRi
        elif (p.tok.kind in {tkCurlyLe}):
          expect p, tkCurlyLe
        elif (p.tok.kind in {tkCurlyRi}):
          expect p, tkCurlyRi
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
        else:
          error p, "expected alternative"
        discardUnused m15
        while (p.tok.kind in Tk9):
          let m14 = mark(p)
          let m16 = mark(p)
          if (p.tok.kind in Tk4):
            pOperator p
          elif (p.tok.kind in {tkParLe}):
            expect p, tkParLe
          elif (p.tok.kind in {tkParRi}):
            expect p, tkParRi
          elif (p.tok.kind in {tkBracketLe}):
            expect p, tkBracketLe
          elif (p.tok.kind in {tkBracketRi}):
            expect p, tkBracketRi
          elif (p.tok.kind in {tkCurlyLe}):
            expect p, tkCurlyLe
          elif (p.tok.kind in {tkCurlyRi}):
            expect p, tkCurlyRi
          elif (p.tok.kind in {tkEquals}):
            expect p, tkEquals
          else:
            error p, "expected alternative"
          discardUnused m16
          discardUnused m14
      else:
        error p, "expected alternative"
      discardUnused m13
      discardUnused m8
    expect p, tkAccent
    wrap p, m0, "quoted"
  elif (p.tok.kind in {tkSymbol}):
    emitLeaf p            # IDENT
  elif (p.tok.kind in {tkAddr}):
    expect p, tkAddr
  elif (p.tok.kind in {tkType}):
    expect p, tkType
  elif (p.tok.kind in {tkStatic}):
    expect p, tkStatic
  else:
    error p, "expected symbol"
  discardUnused m0

proc pSymbolOrKeyword*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pSymbol p
  elif (p.tok.kind in {tkAddr..tkYield}):
    emitLeaf p            # KEYW
  else:
    error p, "expected symbolOrKeyword"
  discardUnused m0

proc pLiteral*(p: var Parser) =
  let m0 = mark(p)
  let m17 = mark(p)
  if (p.tok.kind in {tkIntLit}):
    emitLeaf p            # INT_LIT
  elif (p.tok.kind in {tkInt8Lit}):
    emitLeaf p            # INT8_LIT
  elif (p.tok.kind in {tkInt16Lit}):
    emitLeaf p            # INT16_LIT
  elif (p.tok.kind in {tkInt32Lit}):
    emitLeaf p            # INT32_LIT
  elif (p.tok.kind in {tkInt64Lit}):
    emitLeaf p            # INT64_LIT
  elif (p.tok.kind in {tkUIntLit}):
    emitLeaf p            # UINT_LIT
  elif (p.tok.kind in {tkUInt8Lit}):
    emitLeaf p            # UINT8_LIT
  elif (p.tok.kind in {tkUInt16Lit}):
    emitLeaf p            # UINT16_LIT
  elif (p.tok.kind in {tkUInt32Lit}):
    emitLeaf p            # UINT32_LIT
  elif (p.tok.kind in {tkUInt64Lit}):
    emitLeaf p            # UINT64_LIT
  elif (p.tok.kind in {tkFloatLit}):
    emitLeaf p            # FLOAT_LIT
  elif (p.tok.kind in {tkFloat32Lit}):
    emitLeaf p            # FLOAT32_LIT
  elif (p.tok.kind in {tkFloat64Lit}):
    emitLeaf p            # FLOAT64_LIT
  elif (p.tok.kind in {tkFloat128Lit}):
    emitLeaf p            # FLOAT128_LIT
  elif (p.tok.kind in {tkStrLit}):
    emitLeaf p            # STR_LIT
  elif (p.tok.kind in {tkRStrLit}):
    emitLeaf p            # RSTR_LIT
  elif (p.tok.kind in {tkTripleStrLit}):
    emitLeaf p            # TRIPLESTR_LIT
  elif (p.tok.kind in {tkCharLit}):
    emitLeaf p            # CHAR_LIT
  elif (p.tok.kind in {tkCustomLit}):
    emitLeaf p            # CUSTOM_NUMERIC_LIT
  elif (p.tok.kind in {tkNil}):
    expect p, tkNil
  else:
    error p, "expected alternative"
  discardUnused m17
  discardUnused m0

proc pGeneralizedLit*(p: var Parser) =
  let m0 = mark(p)
  let m18 = mark(p)
  if (p.tok.kind in {tkGStrLit}):
    emitLeaf p            # GENERALIZED_STR_LIT
  elif (p.tok.kind in {tkGTripleStrLit}):
    emitLeaf p            # GENERALIZED_TRIPLESTR_LIT
  else:
    error p, "expected alternative"
  discardUnused m18
  discardUnused m0

proc pExprColonEqExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1):
    pExpr p
    if (p.tok.kind in {tkColon}):
      expect p, tkColon
      pExpr p
      wrap p, m0, "kv"
    elif (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pExpr p
      wrap p, m0, "vv"
    elif (p.tok.kind in {tkDo}):
      if (p.tok.kind in {tkDo}):
        pDoBlock p
        while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
          let m19 = mark(p)
          pExtraPostExprBlock p
          discardUnused m19
  else:
    error p, "expected exprColonEqExpr"
  discardUnused m0

proc pExprEqExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1):
    pExpr p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pExpr p
      wrap p, m0, "vv"
    elif (p.tok.kind in {tkDo}):
      if (p.tok.kind in {tkDo}):
        pDoBlock p
        while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
          let m20 = mark(p)
          pExtraPostExprBlock p
          discardUnused m20
  else:
    error p, "expected exprEqExpr"
  discardUnused m0

proc pExprList*(p: var Parser) =
  let m0 = mark(p)
  let m21 = mark(p)
  pExpr p
  while (p.tok.kind in {tkComma}):
    pComma p
    pExpr p
  discardUnused m21
  discardUnused m0

proc pOptionalExprList*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk1):
    let m22 = mark(p)
    pExpr p
    while (p.tok.kind in {tkComma}):
      pComma p
      pExpr p
    discardUnused m22
  discardUnused m0

proc pExprColonEqExprList*(p: var Parser) =
  let m0 = mark(p)
  pExprColonEqExpr p
  while (p.tok.kind in {tkComma}):
    let m23 = mark(p)
    pComma p
    pExprColonEqExpr p
    discardUnused m23
  if (p.tok.kind in {tkComma}):
    pComma p
  discardUnused m0

proc pQualifiedIdent*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pSymbol p
    if (p.tok.kind in {tkDot}):
      expect p, tkDot
      pOptInd p
      pSymbolOrKeyword p
      wrap p, m0, "dot"
    else:
      discard
  else:
    error p, "expected qualifiedIdent"
  discardUnused m0

proc pSetOrTableConstr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkCurlyLe}):
    expect p, tkCurlyLe
    if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk13 and indClass(p) in {icNoInd, icGt}):
      pOptInd p
      if (p.tok.kind in Tk1):
        pExprColonEqExprList p
      pOptPar p
      expect p, tkCurlyRi
      wrap p, m0, "curly"
    elif (p.tok.kind in {tkColon}):
      expect p, tkColon
      pOptPar p
      expect p, tkCurlyRi
      wrap p, m0, "tabconstr"
    else:
      error p, "expected setOrTableConstr"
  else:
    error p, "expected setOrTableConstr"
  discardUnused m0

proc pCastExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCast
  expect p, tkBracketLe
  pOptInd p
  pTypeDesc p
  pOptPar p
  expect p, tkBracketRi
  expect p, tkParLe
  pOptInd p
  pExpr p
  pOptPar p
  expect p, tkParRi
  wrap p, m0, "cast"
  discardUnused m0

proc pParKeyw*(p: var Parser) =
  let m0 = mark(p)
  let m24 = mark(p)
  if (p.tok.kind in {tkDiscard}):
    expect p, tkDiscard
  elif (p.tok.kind in {tkInclude}):
    expect p, tkInclude
  elif (p.tok.kind in {tkIf}):
    expect p, tkIf
  elif (p.tok.kind in {tkWhile}):
    expect p, tkWhile
  elif (p.tok.kind in {tkCase}):
    expect p, tkCase
  elif (p.tok.kind in {tkTry}):
    expect p, tkTry
  elif (p.tok.kind in {tkFinally}):
    expect p, tkFinally
  elif (p.tok.kind in {tkExcept}):
    expect p, tkExcept
  elif (p.tok.kind in {tkFor}):
    expect p, tkFor
  elif (p.tok.kind in {tkBlock}):
    expect p, tkBlock
  elif (p.tok.kind in {tkConst}):
    expect p, tkConst
  elif (p.tok.kind in {tkLet}):
    expect p, tkLet
  elif (p.tok.kind in {tkWhen}):
    expect p, tkWhen
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
  elif (p.tok.kind in {tkMixin}):
    expect p, tkMixin
  else:
    error p, "expected alternative"
  discardUnused m24
  discardUnused m0

proc pPar*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe}):
    expect p, tkParLe
    if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk14 and indClass(p) in {icNoInd, icGt}):
      pOptInd p
      if (p.tok.kind in Tk6):
        let m25 = mark(p)
        let m26 = mark(p)
        if (p.tok.kind in {tkIf}):
          pIfExpr p
        elif (p.tok.kind in Tk6):
          pComplexOrSimpleStmt p
        else:
          error p, "expected alternative"
        discardUnused m26
        while (p.tok.kind in {tkSemiColon}):
          expect p, tkSemiColon
          let m27 = mark(p)
          if (p.tok.kind in {tkIf}):
            pIfExpr p
          elif (p.tok.kind in Tk6):
            pComplexOrSimpleStmt p
          else:
            error p, "expected alternative"
          discardUnused m27
        discardUnused m25
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "stmts"
      elif (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
        let m28 = mark(p)
        let m29 = mark(p)
        if (p.tok.kind in {tkIf}):
          pIfExpr p
        elif (p.tok.kind in Tk6):
          pComplexOrSimpleStmt p
        else:
          error p, "expected alternative"
        discardUnused m29
        while (p.tok.kind in {tkSemiColon}):
          expect p, tkSemiColon
          let m30 = mark(p)
          if (p.tok.kind in {tkIf}):
            pIfExpr p
          elif (p.tok.kind in Tk6):
            pComplexOrSimpleStmt p
          else:
            error p, "expected alternative"
          discardUnused m30
        discardUnused m28
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "stmts"
      elif (p.tok.kind in {tkCurlyDotLe}):
        pPragmaStmt p
        pOptPar p
        expect p, tkParRi
        wrap p, m0, "par"
      elif (p.tok.kind in Tk2):
        pSimpleExpr(p, -1, pmNormal)
        if (p.tok.kind in {tkDo}):
          pDoBlock p
          while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
            let m31 = mark(p)
            pExtraPostExprBlock p
            discardUnused m31
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        elif (p.tok.kind in {tkEquals}):
          expect p, tkEquals
          pExpr p
          if (p.tok.kind in {tkSemiColon}):
            expect p, tkSemiColon
            let m32 = mark(p)
            let m33 = mark(p)
            if (p.tok.kind in {tkIf}):
              pIfExpr p
            elif (p.tok.kind in Tk6):
              pComplexOrSimpleStmt p
            else:
              error p, "expected alternative"
            discardUnused m33
            while (p.tok.kind in {tkSemiColon}):
              expect p, tkSemiColon
              let m34 = mark(p)
              if (p.tok.kind in {tkIf}):
                pIfExpr p
              elif (p.tok.kind in Tk6):
                pComplexOrSimpleStmt p
              else:
                error p, "expected alternative"
              discardUnused m34
            discardUnused m32
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        elif (p.tok.kind in {tkColon}):
          expect p, tkColon
          pExpr p
          if (p.tok.kind in {tkComma}):
            expect p, tkComma
            let m35 = mark(p)
            pExprColonEqExpr p
            while (p.tok.kind in {tkComma}):
              expect p, tkComma
              pExprColonEqExpr p
            discardUnused m35
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        elif (p.tok.kind in {tkParRi} and indClass(p) in {icNoInd, icEq, icGt}):
          pOptPar p
          expect p, tkParRi
          wrap p, m0, "par"
        else:
          error p, "expected par"
      else:
        error p, "expected par"
    else:
      error p, "expected par"
  else:
    error p, "expected par"
  discardUnused m0

proc pTupleConstr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkParLe
  pOptInd p
  while (p.tok.kind in Tk1):
    let m36 = mark(p)
    pExprColonEqExpr p
    if (p.tok.kind in {tkComma}):
      pComma p
    discardUnused m36
  pOptPar p
  expect p, tkParRi
  wrap p, m0, "tup"
  discardUnused m0

proc pArrayConstr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  pOptInd p
  while (p.tok.kind in Tk1):
    let m37 = mark(p)
    pExprColonEqExpr p
    if (p.tok.kind in {tkComma}):
      pComma p
    discardUnused m37
  pOptPar p
  expect p, tkBracketRi
  wrap p, m0, "bracket"
  discardUnused m0

proc pIdentOrLiteral*(p: var Parser) =
  let m0 = mark(p)
  let m38 = mark(p)
  if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
    pGeneralizedLit p
  elif (p.tok.kind in Tk11):
    pSymbol p
  elif (p.tok.kind in Tk8):
    pLiteral p
  elif (p.tok.kind in {tkParLe}):
    pPar p
  elif (p.tok.kind in {tkBracketLe}):
    pArrayConstr p
  elif (p.tok.kind in {tkCurlyLe}):
    pSetOrTableConstr p
  elif (p.tok.kind in {tkParLe}):
    pTupleConstr p
  elif (p.tok.kind in {tkCast}):
    pCastExpr p
  else:
    error p, "expected alternative"
  discardUnused m38
  discardUnused m0

proc pPrimarySuffix*(p: var Parser; anchor: Mark; mode: PrimaryMode) =
  let m0 = mark(p)
  if ((p.tok.kind in {tkBracketLe, tkCurlyLe, tkParLe})) and noSpaceBefore(p):
    if (p.tok.kind in {tkParLe}):
      expect p, tkParLe
      while (p.tok.kind in Tk1):
        let m39 = mark(p)
        pExprColonEqExpr p
        if (p.tok.kind in {tkComma}):
          pComma p
        discardUnused m39
      expect p, tkParRi
      wrap p, anchor, "call"
    elif (p.tok.kind in {tkBracketLe}):
      expect p, tkBracketLe
      pOptInd p
      pExprColonEqExprList p
      pOptPar p
      expect p, tkBracketRi
      wrap p, anchor, "at"
    elif (p.tok.kind in {tkCurlyLe}):
      expect p, tkCurlyLe
      pOptInd p
      pExprColonEqExprList p
      pOptPar p
      expect p, tkCurlyRi
      wrap p, anchor, "curlyat"
    else:
      error p, "expected primarySuffix"
  elif (p.tok.kind in {tkDot}):
    expect p, tkDot
    pOptInd p
    pSymbolOrKeyword p
    if (p.tok.kind in {tkBracketLeColon}):
      expect p, tkBracketLeColon
      pExprList p
      expect p, tkBracketRi
      if (p.tok.kind in {tkParLe}):
        expect p, tkParLe
        pExprColonEqExpr p
        expect p, tkParRi
    wrap p, anchor, "dot"
    if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
      pGeneralizedLit p
  elif (((p.tok.kind == tkOpr and isDotLike(p.tok)))) and dotLikeOps(p):
    emitLeaf p            # DOTLIKEOP
    pOptInd p
    pSymbolOrKeyword p
    wrap p, anchor, "dot"
    if (p.tok.kind in {tkGStrLit, tkGTripleStrLit}):
      pGeneralizedLit p
  elif ((p.tok.kind in Tk1)) and commandStart(p) and commandAllowed(p, mode):
    pCommandParam(p, mode)
    wrap p, anchor, "cmd"
  else:
    error p, "expected primarySuffix"
  discardUnused m0

proc pPragma*(p: var Parser) =
  let m0 = mark(p)
  inc p.inPragma
  expect p, tkCurlyDotLe
  pOptInd p
  while (p.tok.kind in Tk1):
    let m40 = mark(p)
    pExprColonEqExpr p
    if (p.tok.kind in {tkComma}):
      pComma p
    discardUnused m40
  pOptPar p
  let m41 = mark(p)
  if (p.tok.kind in {tkCurlyDotRi}):
    expect p, tkCurlyDotRi
  elif (p.tok.kind in {tkCurlyRi}):
    expect p, tkCurlyRi
  else:
    error p, "expected alternative"
  discardUnused m41
  dec p.inPragma
  wrap p, m0, "pragmas"
  discardUnused m0

proc pIdentVis*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pSymbol p
    if (p.tok.kind in {tkOpr}):
      emitLeaf p            # OPR
      wrap p, m0, "postfix"
    else:
      discard
  else:
    error p, "expected identVis"
  discardUnused m0

proc pIdentVisDot*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pSymbol p
    if (p.tok.kind in {tkOpr}):
      emitLeaf p            # OPR
      wrap p, m0, "postfix"
    elif (p.tok.kind in {tkDot}):
      expect p, tkDot
      pOptInd p
      pSymbolOrKeyword p
      wrap p, m0, "dot"
    else:
      discard
  else:
    error p, "expected identVisDot"
  discardUnused m0

proc pIdentWithPragma*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pIdentVis p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
      wrap p, m0, "pragmax"
    else:
      discard
  else:
    error p, "expected identWithPragma"
  discardUnused m0

proc pIdentWithPragmaDot*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk11):
    pIdentVisDot p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
      wrap p, m0, "pragmax"
    else:
      discard
  else:
    error p, "expected identWithPragmaDot"
  discardUnused m0

proc pDeclColonEquals*(p: var Parser) =
  let m0 = mark(p)
  pIdentWithPragma p
  while (p.tok.kind in {tkComma}):
    let m42 = mark(p)
    pComma p
    pIdentWithPragma p
    discardUnused m42
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  let m = m0
  fanOut m, p.section          # one (var|let|param|fld ...) per name
  discardUnused m0

proc pIdentColonEquals*(p: var Parser) =
  let m0 = mark(p)
  emitLeaf p            # IDENT
  while (p.tok.kind in {tkComma}):
    let m43 = mark(p)
    pComma p
    emitLeaf p            # IDENT
    discardUnused m43
  if (p.tok.kind in {tkComma}):
    pComma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  let m = m0
  fanOut m, p.section
  discardUnused m0

proc pTupleTypeBracket*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  pOptInd p
  while (p.tok.kind in {tkSymbol}):
    let m44 = mark(p)
    pIdentColonEquals p
    if (p.tok.kind in {tkComma, tkSemiColon}):
      let m45 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m45
    discardUnused m44
  pOptPar p
  expect p, tkBracketRi
  discardUnused m0

proc pTupleType*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTuple
  pTupleTypeBracket p
  wrap p, m0, "tuple"
  discardUnused m0

proc pTupleDecl*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkTuple}):
    expect p, tkTuple
    if (p.tok.kind in {tkBracketLe}):
      pTupleTypeBracket p
      wrap p, m0, "tuple"
    elif (p.tok.kind in {tkSymbol} and indClass(p) in {icGt}) or (p.tok.kind in {tkComment}):
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      if (p.tok.kind in {tkSymbol} and indClass(p) in {icGt}):
        pushInd p
        let m46 = mark(p)
        pIdentColonEquals p
        while (p.tok.kind in {tkSymbol} and indClass(p) in {icEq}):
          checkInd p, {icEq}
          pIdentColonEquals p
        if ((p.tok.kind in {tkSymbol})) and indClass(p) == icGt:
          error p, "invalid indentation in tupleDecl"
        discardUnused m46
        popInd p
      wrap p, m0, "tuple"
    else:
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      if (p.tok.kind in {tkSymbol} and indClass(p) in {icGt}):
        pushInd p
        let m47 = mark(p)
        pIdentColonEquals p
        while (p.tok.kind in {tkSymbol} and indClass(p) in {icEq}):
          checkInd p, {icEq}
          pIdentColonEquals p
        if ((p.tok.kind in {tkSymbol})) and indClass(p) == icGt:
          error p, "invalid indentation in tupleDecl"
        discardUnused m47
        popInd p
      wrap p, m0, "tuple"
  else:
    error p, "expected tupleDecl"
  discardUnused m0

proc pParamList*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkParLe
  if (p.tok.kind in Tk11):
    let m48 = mark(p)
    pDeclColonEquals p
    while (p.tok.kind in {tkComma, tkSemiColon}):
      let m49 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m49
      pDeclColonEquals p
    discardUnused m48
  expect p, tkParRi
  wrap p, m0, "params"
  discardUnused m0

proc pParamListArrow*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pParamList p
  if ((p.tok.kind == tkOpr and p.tok.s == "->")):
    expect p, tkOpr, "->"
    pOptInd p
    pTypeDesc p
  discardUnused m0

proc pParamListColon*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pParamList p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDesc p
  discardUnused m0

proc pDoBlock*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDo
  pParamListArrow p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  pColcom p
  pStmt p
  wrap p, m0, "proc"
  discardUnused m0

proc pRoutineExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkProc}):
    expect p, tkProc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      pStmt p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkFunc}):
    expect p, tkFunc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      pStmt p
    wrap p, m0, "func"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      pStmt p
    wrap p, m0, "iterator"
  else:
    error p, "expected routineExpr"
  discardUnused m0

proc pRoutineType*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkProc}):
    expect p, tkProc
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pParamListColon p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    wrap p, m0, "itertype"
  else:
    error p, "expected routineType"
  discardUnused m0

proc pRawTypeDesc*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkIterator, tkProc}):
    pRoutineType p
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  elif (p.tok.kind in Tk5):
    pTypeDescKeyw p
  else:
    error p, "expected rawTypeDesc"
  discardUnused m0

proc pTypeDescKeyw*(p: var Parser) =
  let m0 = mark(p)
  let m50 = mark(p)
  if (p.tok.kind in {tkTuple}):
    pTupleType p
  elif (p.tok.kind in {tkEnum}):
    expect p, tkEnum
    wrap p, m50, "enum"
  elif (p.tok.kind in {tkObject}):
    expect p, tkObject
    wrap p, m50, "object"
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
    if (p.tok.kind in Tk2):
      pTypeDesc p
    wrap p, m50, "mut"
  elif (p.tok.kind in {tkOut}):
    expect p, tkOut
    if (p.tok.kind in Tk2):
      pTypeDesc p
    wrap p, m50, "out"
  elif (p.tok.kind in {tkRef}):
    expect p, tkRef
    if (p.tok.kind in Tk2):
      pTypeDesc p
    wrap p, m50, "ref"
  elif (p.tok.kind in {tkPtr}):
    expect p, tkPtr
    if (p.tok.kind in Tk2):
      pTypeDesc p
    wrap p, m50, "ptr"
  elif (p.tok.kind in {tkDistinct}):
    expect p, tkDistinct
    if (p.tok.kind in Tk2):
      pTypeDesc p
    wrap p, m50, "distinct"
  else:
    error p, "expected alternative"
  discardUnused m50
  if (p.tok.kind in {tkNot}):
    expect p, tkNot
    pPrimary(p, pmTypeDesc)
    wrap p, m0, "infix"
  discardUnused m0

proc pTypeDescExpr*(p: var Parser) =
  let m0 = mark(p)
  let m51 = mark(p)
  if (p.tok.kind in {tkIterator, tkProc}):
    pRoutineType p
  elif (p.tok.kind in Tk2):
    pSimpleExpr(p, -1, pmTypeDesc)
  else:
    error p, "expected alternative"
  discardUnused m51
  if (p.tok.kind in {tkNot}):
    expect p, tkNot
    pPrimary(p, pmTypeDesc)
    wrap p, m0, "infix"
  discardUnused m0

proc pTypeDesc*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk15):
    pRawTypeDesc p
  else:
    pTypeDescExpr p
  discardUnused m0

proc pForStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkFor
  let m52 = mark(p)
  let m53 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTuple p
  elif (p.tok.kind in Tk11):
    pIdentWithPragma p
  else:
    error p, "expected alternative"
  discardUnused m53
  while (p.tok.kind in {tkComma}):
    pComma p
    let m54 = mark(p)
    if (p.tok.kind in {tkParLe}):
      pVarTuple p
    elif (p.tok.kind in Tk11):
      pIdentWithPragma p
    else:
      error p, "expected alternative"
    discardUnused m54
  discardUnused m52
  expect p, tkIn
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "for"
  discardUnused m0

proc pForExpr*(p: var Parser) =
  let m0 = mark(p)
  pForStmt p
  discardUnused m0

proc pExpr*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk16):
    let m55 = mark(p)
    if (p.tok.kind in {tkBlock}):
      pBlockExpr p
    elif (p.tok.kind in {tkIf}):
      pIfExpr p
    elif (p.tok.kind in {tkWhen}):
      pWhenExpr p
    elif (p.tok.kind in {tkCase}):
      pCaseStmt p
    elif (p.tok.kind in {tkFor}):
      pForExpr p
    elif (p.tok.kind in {tkTry}):
      pTryExpr p
    else:
      error p, "expected alternative"
    discardUnused m55
  elif (p.tok.kind in Tk2):
    pSimpleExpr(p, -1, pmNormal)
  else:
    error p, "expected expr"
  discardUnused m0

proc pSimplePrimary*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  pIdentOrLiteral p
  while (canPrimarySuffix(p, mode)) and suffixStart(p):
    let m56 = mark(p)
    pPrimarySuffix(p, m0, mode)
    discardUnused m56
  discardUnused m0

proc pCommandParam*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if ((p.tok.kind in Tk2)) and inTypeDesc(p, mode):
    pSimpleExpr(p, -1, mode)
  else:
    pExpr p
    if (p.tok.kind in {tkDo}):
      pDoBlock p
      while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
        let m57 = mark(p)
        pExtraPostExprBlock p
        discardUnused m57
  discardUnused m0

proc pPrimary*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  if (p.tok.kind in Tk3):
    pSimplePrimary(p, mode)
  elif ((p.tok.kind in Tk4)) and isSigilLike(p):
    pPrefixOperator p
    pSimplePrimary(p, mode)
    wrap p, m0, "prefix"
  elif ((p.tok.kind in Tk4)) and isUnary(p):
    pOperatorB p
    pPrimary(p, mode)
    wrap p, m0, "prefix"
  elif (p.tok.kind in {tkFunc, tkIterator, tkProc}):
    pRoutineExpr p
  elif (p.tok.kind in Tk5):
    pTypeDescKeyw p
  elif (p.tok.kind in Tk4):
    pPrefixOperator p
    pPrimary(p, mode)
    wrap p, m0, "prefix"
  else:
    error p, "expected primary"
  discardUnused m0

proc pSimpleExpr*(p: var Parser; limit: int, mode: PrimaryMode) =
  let m0 = mark(p)
  pPrimaryPragma(p, mode)
  var prec = getPrecedence(p)
  while prec >= limit and indClass(p) == icNoInd:
    let assoc = (if isRightAssoc(p): 0 else: 1)
    insertLeafAt p, m0, p.tok.s
    getTok p
    pSimpleExpr(p, prec + assoc, mode)
    wrap p, m0, "infix"
    prec = getPrecedence(p)
  discardUnused m0

proc pPrimaryPragma*(p: var Parser; mode: PrimaryMode) =
  let m0 = mark(p)
  pPrimary(p, mode)
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
    wrap p, m0, "pragmax"
  discardUnused m0

proc pExtraPostExprBlock*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk12 and indClass(p) in {icEq}):
    checkInd p, {icEq}
    if (p.tok.kind in {tkDo}):
      pDoBlock p
    elif (p.tok.kind in {tkOf}):
      expect p, tkOf
      pExprList p
      expect p, tkColon
      pStmt p
      wrap p, m0, "of"
    elif (p.tok.kind in {tkElif}):
      expect p, tkElif
      pExpr p
      expect p, tkColon
      pStmt p
      wrap p, m0, "elif"
    elif (p.tok.kind in {tkExcept}):
      expect p, tkExcept
      pOptionalExprList p
      expect p, tkColon
      pStmt p
      wrap p, m0, "except"
    elif (p.tok.kind in {tkFinally}):
      expect p, tkFinally
      expect p, tkColon
      pStmt p
      wrap p, m0, "fin"
    elif (p.tok.kind in {tkElse}):
      expect p, tkElse
      expect p, tkColon
      pStmt p
      wrap p, m0, "else"
    else:
      error p, "expected extraPostExprBlock"
  else:
    error p, "expected extraPostExprBlock"
  discardUnused m0

proc pPostExprBlocks*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkDo}):
    pDoBlock p
    while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
      let m58 = mark(p)
      pExtraPostExprBlock p
      discardUnused m58
  elif (p.tok.kind in {tkColon}):
    expect p, tkColon
    let m59 = mark(p)
    if (p.tok.kind in Tk12 and indClass(p) in {icEq}):
      pExtraPostExprBlock p
    elif (p.tok.kind in Tk17 and indClass(p) in {icGt}) or (p.tok.kind in Tk18):
      pStmt p
    else:
      error p, "expected alternative"
    discardUnused m59
    while (p.tok.kind in Tk12 and indClass(p) in {icEq}):
      let m60 = mark(p)
      pExtraPostExprBlock p
      discardUnused m60
  else:
    error p, "expected postExprBlocks"
  discardUnused m0

proc pExprStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk2):
    pSimpleExpr(p, -1, pmTrySimple)
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pOptInd p
      pExpr p
      if (p.tok.kind in {tkColon, tkDo}):
        pPostExprBlocks p
      wrap p, m0, "asgn"
    elif (p.tok.kind in Tk1 and indClass(p) in {icNoInd}):
      checkInd p, {icNoInd}
      let m61 = mark(p)
      pExprEqExpr p
      while (p.tok.kind in {tkComma}):
        pComma p
        pExprEqExpr p
      discardUnused m61
      if (p.tok.kind in {tkColon, tkDo}):
        pPostExprBlocks p
      wrap p, m0, "cmd"
    elif (p.tok.kind in {tkColon, tkDo}):
      if (p.tok.kind in {tkColon, tkDo}):
        pPostExprBlocks p
  else:
    error p, "expected exprStmt"
  discardUnused m0

proc pImportStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkImport}):
    expect p, tkImport
    if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
      pOptInd p
      if (p.tok.kind in Tk1):
        pExpr p
        if (p.tok.kind in {tkComma}):
          while (p.tok.kind in {tkComma}):
            let m62 = mark(p)
            pComma p
            pExpr p
            discardUnused m62
          wrap p, m0, "import"
        elif (p.tok.kind in {tkExcept}):
          expect p, tkExcept
          pOptInd p
          let m63 = mark(p)
          pExpr p
          while (p.tok.kind in {tkComma}):
            pComma p
            pExpr p
          discardUnused m63
          wrap p, m0, "importexcept"
        else:
          while (p.tok.kind in {tkComma}):
            let m64 = mark(p)
            pComma p
            pExpr p
            discardUnused m64
          wrap p, m0, "import"
      else:
        error p, "expected importStmt"
    else:
      error p, "expected importStmt"
  else:
    error p, "expected importStmt"
  discardUnused m0

proc pExportStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkExport}):
    expect p, tkExport
    if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
      pOptInd p
      if (p.tok.kind in Tk1):
        pExpr p
        if (p.tok.kind in {tkComma}):
          while (p.tok.kind in {tkComma}):
            let m65 = mark(p)
            pComma p
            pExpr p
            discardUnused m65
          wrap p, m0, "export"
        elif (p.tok.kind in {tkExcept}):
          expect p, tkExcept
          pOptInd p
          let m66 = mark(p)
          pExpr p
          while (p.tok.kind in {tkComma}):
            pComma p
            pExpr p
          discardUnused m66
          wrap p, m0, "exportexcept"
        else:
          while (p.tok.kind in {tkComma}):
            let m67 = mark(p)
            pComma p
            pExpr p
            discardUnused m67
          wrap p, m0, "export"
      else:
        error p, "expected exportStmt"
    else:
      error p, "expected exportStmt"
  else:
    error p, "expected exportStmt"
  discardUnused m0

proc pIncludeStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkInclude
  pOptInd p
  let m68 = mark(p)
  pExpr p
  while (p.tok.kind in {tkComma}):
    pComma p
    pExpr p
  discardUnused m68
  wrap p, m0, "include"
  discardUnused m0

proc pFromStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkFrom
  pExpr p
  expect p, tkImport
  pOptInd p
  pExpr p
  while (p.tok.kind in {tkComma}):
    let m69 = mark(p)
    pComma p
    pExpr p
    discardUnused m69
  wrap p, m0, "fromimport"
  discardUnused m0

proc pReturnStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkReturn
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "ret"
  discardUnused m0

proc pRaiseStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkRaise
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "raise"
  discardUnused m0

proc pYieldStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkYield
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "yld"
  discardUnused m0

proc pDiscardStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDiscard
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "discard"
  discardUnused m0

proc pBreakStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBreak
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "break"
  discardUnused m0

proc pContinueStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkContinue
  if (p.tok.kind in {tkComment}) or (p.tok.kind in Tk1 and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    pExpr p
  wrap p, m0, "continue"
  discardUnused m0

proc pCondStmt*(p: var Parser) =
  let m0 = mark(p)
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "elif"
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  while (p.tok.kind in {tkElif} and indClass(p) in {icEq}):
    let m70 = mark(p)
    checkInd p, {icEq}
    expect p, tkElif
    pExpr p
    pColcom p
    pStmt p
    wrap p, m70, "elif"
    discardUnused m70
  if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    expect p, tkElse
    pColcom p
    pStmt p
    wrap p, m0, "else"
  discardUnused m0

proc pIfStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkIf
  pCondStmt p
  wrap p, m0, "if"
  discardUnused m0

proc pWhenStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pCondStmt p
  wrap p, m0, "when"
  discardUnused m0

proc pCondExpr*(p: var Parser) =
  let m0 = mark(p)
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "elif"
  pOptInd p
  while (p.tok.kind in {tkElif}):
    let m71 = mark(p)
    expect p, tkElif
    pExpr p
    pColcom p
    pStmt p
    wrap p, m71, "elif"
    pOptInd p
    discardUnused m71
  expect p, tkElse
  pColcom p
  pStmt p
  wrap p, m0, "else"
  discardUnused m0

proc pIfExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkIf
  pCondExpr p
  wrap p, m0, "if"
  discardUnused m0

proc pWhenExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pCondExpr p
  wrap p, m0, "when"
  discardUnused m0

proc pWhileStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhile
  pExpr p
  pColcom p
  pStmt p
  wrap p, m0, "while"
  discardUnused m0

proc pOfBranch*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkOf
  pExprList p
  pColcom p
  pStmt p
  wrap p, m0, "of"
  discardUnused m0

proc pOfBranches*(p: var Parser) =
  let m0 = mark(p)
  pOfBranch p
  while (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
    let m72 = mark(p)
    checkInd p, {icEq}
    pOfBranch p
    discardUnused m72
  while (p.tok.kind in {tkElif} and indClass(p) in {icEq}):
    let m73 = mark(p)
    checkInd p, {icEq}
    expect p, tkElif
    pExpr p
    pColcom p
    pStmt p
    wrap p, m73, "elif"
    discardUnused m73
  if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    expect p, tkElse
    pColcom p
    pStmt p
    wrap p, m0, "else"
  discardUnused m0

proc pCaseStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCase
  pExpr p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  let m74 = mark(p)
  if (p.tok.kind in {tkOf} and indClass(p) in {icGt}):
    pushInd p
    pOfBranches p
    popInd p
  elif (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    pOfBranches p
  else:
    error p, "expected alternative"
  discardUnused m74
  wrap p, m0, "case"
  discardUnused m0

proc pTryStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTry
  pColcom p
  pStmt p
  while (p.tok.kind in {tkExcept} and indClass(p) in {icNoInd, icEq}):
    let m75 = mark(p)
    pOptSameInd p
    expect p, tkExcept
    pOptionalExprList p
    pColcom p
    pStmt p
    wrap p, m75, "except"
    discardUnused m75
  if (p.tok.kind in {tkFinally} and indClass(p) in {icNoInd, icEq}):
    pOptSameInd p
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  wrap p, m0, "try"
  discardUnused m0

proc pTryExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkTry
  pColcom p
  pStmt p
  while (p.tok.kind in {tkComment}) or (p.tok.kind in {tkExcept} and indClass(p) in {icNoInd, icGt}):
    let m76 = mark(p)
    pOptInd p
    expect p, tkExcept
    pOptionalExprList p
    pColcom p
    pStmt p
    wrap p, m76, "except"
    discardUnused m76
  if (p.tok.kind in {tkComment}) or (p.tok.kind in {tkFinally} and indClass(p) in {icNoInd, icGt}):
    pOptInd p
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  wrap p, m0, "try"
  discardUnused m0

proc pBlockStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBlock
  if (p.tok.kind in Tk11):
    pSymbol p
  pColcom p
  pStmt p
  wrap p, m0, "block"
  discardUnused m0

proc pBlockExpr*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBlock
  if (p.tok.kind in Tk11):
    pSymbol p
  pColcom p
  pStmt p
  wrap p, m0, "block"
  discardUnused m0

proc pStaticStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkStatic
  pColcom p
  pStmt p
  wrap p, m0, "staticstmt"
  discardUnused m0

proc pDeferStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkDefer
  pColcom p
  pStmt p
  wrap p, m0, "defer"
  discardUnused m0

proc pAsmStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkAsm
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  let m77 = mark(p)
  if (p.tok.kind in {tkStrLit}):
    emitLeaf p            # STR_LIT
  elif (p.tok.kind in {tkRStrLit}):
    emitLeaf p            # RSTR_LIT
  elif (p.tok.kind in {tkTripleStrLit}):
    emitLeaf p            # TRIPLESTR_LIT
  else:
    error p, "expected alternative"
  discardUnused m77
  wrap p, m0, "asm"
  discardUnused m0

proc pGenericParam*(p: var Parser) =
  let m0 = mark(p)
  pSymbol p
  while (p.tok.kind in {tkComma}):
    let m78 = mark(p)
    pComma p
    pSymbol p
    discardUnused m78
  if (p.tok.kind in {tkColon}):
    pColon p
    pExpr p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
  wrap p, m0, "typevar"
  discardUnused m0

proc pGenericParamList*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBracketLe
  pOptInd p
  if (p.tok.kind in Tk11):
    let m79 = mark(p)
    pGenericParam p
    while (p.tok.kind in {tkComma, tkSemiColon}):
      let m80 = mark(p)
      if (p.tok.kind in {tkComma}):
        pComma p
      elif (p.tok.kind in {tkSemiColon}):
        pSemicolon p
      else:
        error p, "expected alternative"
      discardUnused m80
      pGenericParam p
    discardUnused m79
  pOptPar p
  expect p, tkBracketRi
  wrap p, m0, "typevars"
  discardUnused m0

proc pPattern*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCurlyLe
  pStmt p
  expect p, tkCurlyRi
  discardUnused m0

proc pIndAndComment*(p: var Parser) =
  let m0 = mark(p)
  let m81 = mark(p)
  if (p.tok.kind in {tkComment} and indClass(p) in {icGt}):
    if (p.tok.kind in {tkComment} and indClass(p) in {icGt}):
      checkInd p, {icGt}
      emitLeaf p            # COMMENT
  elif (p.tok.kind in {tkComment}):
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
  discardUnused m81
  discardUnused m0

proc pRoutine*(p: var Parser) =
  let m0 = mark(p)
  pOptInd p
  pIdentVis p
  if (p.tok.kind in {tkCurlyLe}):
    pPattern p
  if (p.tok.kind in {tkBracketLe}):
    pGenericParamList p
  pParamListColon p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    pStmt p
  pIndAndComment p
  discardUnused m0

proc pCommentStmt*(p: var Parser) =
  let m0 = mark(p)
  emitLeaf p            # COMMENT
  wrap p, m0, "comment"
  discardUnused m0

proc pEnumDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkEnum
  pOptInd p
  pValidInd p
  pSymbol p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pExpr p
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
  if (p.tok.kind in {tkComma}):
    pComma p
  while (p.tok.kind in Tk11 and indClass(p) in {icNoInd, icGt}):
    let m82 = mark(p)
    pValidInd p
    pSymbol p
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    if (p.tok.kind in {tkEquals}):
      expect p, tkEquals
      pOptInd p
      pExpr p
      if (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
    if (p.tok.kind in {tkComma}):
      pComma p
    discardUnused m82
  wrap p, m0, "enum"
  discardUnused m0

proc pObjectWhen*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkWhen
  pExpr p
  pColcom p
  pObjectPart p
  wrap p, m0, "elif"
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  while (p.tok.kind in {tkElif}):
    let m83 = mark(p)
    expect p, tkElif
    pExpr p
    pColcom p
    pObjectPart p
    wrap p, m83, "elif"
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    discardUnused m83
  if (p.tok.kind in {tkElse}):
    expect p, tkElse
    pColcom p
    pObjectPart p
    wrap p, m0, "else"
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
  wrap p, m0, "when"
  discardUnused m0

proc pObjectBranch*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkOf
  pExprList p
  pColcom p
  pObjectPart p
  wrap p, m0, "of"
  discardUnused m0

proc pObjectBranches*(p: var Parser) =
  let m0 = mark(p)
  pObjectBranch p
  while (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
    let m84 = mark(p)
    checkInd p, {icEq}
    pObjectBranch p
    discardUnused m84
  while (p.tok.kind in {tkElif} and indClass(p) in {icEq}):
    let m85 = mark(p)
    checkInd p, {icEq}
    expect p, tkElif
    pExpr p
    pColcom p
    pObjectPart p
    wrap p, m85, "elif"
    discardUnused m85
  if (p.tok.kind in {tkElse} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    expect p, tkElse
    pColcom p
    pObjectPart p
    wrap p, m0, "else"
  discardUnused m0

proc pObjectCase*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkCase
  if (p.tok.kind in Tk19):
    let m86 = mark(p)
    if (p.tok.kind in Tk11):
      pDeclColonEquals p
    elif (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
    else:
      error p, "expected alternative"
    discardUnused m86
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  let m87 = mark(p)
  if (p.tok.kind in {tkOf} and indClass(p) in {icGt}):
    pushInd p
    pObjectBranches p
    popInd p
  elif (p.tok.kind in {tkOf} and indClass(p) in {icEq}):
    checkInd p, {icEq}
    pObjectBranches p
  else:
    error p, "expected alternative"
  discardUnused m87
  wrap p, m0, "case"
  discardUnused m0

proc pObjectPart*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk20 and indClass(p) in {icGt}):
    pushInd p
    let m88 = mark(p)
    pObjectPart p
    while (p.tok.kind in Tk20 and indClass(p) in {icEq}):
      checkInd p, {icEq}
      pObjectPart p
    if ((p.tok.kind in Tk20)) and indClass(p) == icGt:
      error p, "invalid indentation in objectPart"
    discardUnused m88
    popInd p
    wrap p, m0, "stmts"
  elif (p.tok.kind in Tk20 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    if (p.tok.kind in {tkWhen}):
      pObjectWhen p
    elif (p.tok.kind in {tkCase}):
      pObjectCase p
    elif (p.tok.kind in {tkNil}):
      expect p, tkNil
    elif (p.tok.kind in {tkDiscard}):
      expect p, tkDiscard
    elif (p.tok.kind in Tk11):
      pDeclColonEquals p
    else:
      error p, "expected objectPart"
  else:
    error p, "expected objectPart"
  discardUnused m0

proc pObjectDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkObject
  if (p.tok.kind in {tkOf}):
    expect p, tkOf
    pTypeDesc p
  if (p.tok.kind in {tkComment}):
    emitLeaf p            # COMMENT
  pObjectPart p
  wrap p, m0, "object"
  discardUnused m0

proc pConceptParam*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk21):
    let m89 = mark(p)
    if (p.tok.kind in {tkVar}):
      expect p, tkVar
    elif (p.tok.kind in {tkOut}):
      expect p, tkOut
    elif (p.tok.kind in {tkPtr}):
      expect p, tkPtr
    elif (p.tok.kind in {tkRef}):
      expect p, tkRef
    elif (p.tok.kind in {tkStatic}):
      expect p, tkStatic
    elif (p.tok.kind in {tkType}):
      expect p, tkType
    else:
      error p, "expected alternative"
    discardUnused m89
  pSymbol p
  discardUnused m0

proc pConceptDecl*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkConcept
  if (p.tok.kind in Tk22):
    if (p.tok.kind in Tk22):
      let m90 = mark(p)
      pConceptParam p
      while (p.tok.kind in {tkComma}):
        expect p, tkComma
        pConceptParam p
      discardUnused m90
    if (p.tok.kind in {tkCurlyDotLe}):
      pPragma p
  if (p.tok.kind in {tkOf}):
    expect p, tkOf
    if (p.tok.kind in Tk2):
      let m91 = mark(p)
      pTypeDesc p
      while (p.tok.kind in {tkComma}):
        expect p, tkComma
        pTypeDesc p
      discardUnused m91
  pStmt p
  wrap p, m0, "concept"
  discardUnused m0

proc pTypeDef*(p: var Parser) =
  let m0 = mark(p)
  pIdentVisDot p
  if (p.tok.kind in {tkBracketLe}):
    pGenericParamList p
  if (p.tok.kind in {tkCurlyDotLe}):
    pPragma p
  if (p.tok.kind in {tkEquals}):
    expect p, tkEquals
    pOptInd p
    pTypeDefValue p
  if (p.tok.kind in {tkComment}):
    pIndAndComment p
  wrap p, m0, "type"
  discardUnused m0

proc pTypeDefValue*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk23):
    let m92 = mark(p)
    if (p.tok.kind in {tkTuple}):
      pTupleDecl p
    elif (p.tok.kind in {tkEnum}):
      pEnumDecl p
    elif (p.tok.kind in {tkObject}):
      pObjectDecl p
    elif (p.tok.kind in {tkConcept}):
      pConceptDecl p
    elif (p.tok.kind in {tkRef}):
      expect p, tkRef
      let m93 = mark(p)
      if (p.tok.kind in {tkTuple}):
        pTupleDecl p
      elif (p.tok.kind in {tkObject}):
        pObjectDecl p
      else:
        error p, "expected alternative"
      discardUnused m93
      wrap p, m92, "ref"
    elif (p.tok.kind in {tkPtr}):
      expect p, tkPtr
      let m94 = mark(p)
      if (p.tok.kind in {tkTuple}):
        pTupleDecl p
      elif (p.tok.kind in {tkObject}):
        pObjectDecl p
      else:
        error p, "expected alternative"
      discardUnused m94
      wrap p, m92, "ptr"
    elif (p.tok.kind in {tkDistinct}):
      expect p, tkDistinct
      let m95 = mark(p)
      if (p.tok.kind in {tkTuple}):
        pTupleDecl p
      elif (p.tok.kind in {tkObject}):
        pObjectDecl p
      else:
        error p, "expected alternative"
      discardUnused m95
      wrap p, m92, "distinct"
    else:
      error p, "expected alternative"
    discardUnused m92
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  else:
    pSimpleExpr(p, -1, pmTypeDef)
    if (p.tok.kind in Tk1):
      let m96 = mark(p)
      pExprEqExpr p
      while (p.tok.kind in {tkComma}):
        pComma p
        pExprEqExpr p
      discardUnused m96
      if (p.tok.kind in {tkColon, tkDo}):
        pPostExprBlocks p
    if (p.tok.kind in {tkNot}):
      expect p, tkNot
      pPrimary(p, pmTypeDesc)
      wrap p, m0, "infix"
  discardUnused m0

proc pVarTupleLhs*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkParLe
  pOptInd p
  let m97 = mark(p)
  let m98 = mark(p)
  if (p.tok.kind in Tk11):
    pIdentWithPragma p
  elif (p.tok.kind in {tkParLe}):
    pVarTupleLhs p
  else:
    error p, "expected alternative"
  discardUnused m98
  while (p.tok.kind in {tkComma}):
    pComma p
    let m99 = mark(p)
    if (p.tok.kind in Tk11):
      pIdentWithPragma p
    elif (p.tok.kind in {tkParLe}):
      pVarTupleLhs p
    else:
      error p, "expected alternative"
    discardUnused m99
  discardUnused m97
  pOptPar p
  expect p, tkParRi
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    pOptInd p
    pTypeDescExpr p
  wrap p, m0, "unpacktup"
  discardUnused m0

proc pVarTuple*(p: var Parser) =
  let m0 = mark(p)
  pVarTupleLhs p
  expect p, tkEquals
  pOptInd p
  pExpr p
  wrap p, m0, "unpackdecl"
  discardUnused m0

proc pColonBody*(p: var Parser) =
  let m0 = mark(p)
  pColcom p
  pStmt p
  if (p.tok.kind in {tkColon, tkDo}):
    pPostExprBlocks p
  discardUnused m0

proc pVariable*(p: var Parser) =
  let m0 = mark(p)
  let m100 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTuple p
  elif (p.tok.kind in {tkSymbol}):
    pIdentColonEquals p
  else:
    error p, "expected alternative"
  discardUnused m100
  if (p.tok.kind in {tkColon}):
    pColonBody p
  pIndAndComment p
  discardUnused m0

proc pConstant*(p: var Parser) =
  let m0 = mark(p)
  let m101 = mark(p)
  if (p.tok.kind in {tkParLe}):
    pVarTuple p
  elif (p.tok.kind in Tk11):
    pIdentWithPragma p
  else:
    error p, "expected alternative"
  discardUnused m101
  if (p.tok.kind in {tkColon}):
    pColon p
    pTypeDesc p
  expect p, tkEquals
  pOptInd p
  pExpr p
  pIndAndComment p
  discardUnused m0

proc pBindStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkBind
  pOptInd p
  let m102 = mark(p)
  pQualifiedIdent p
  while (p.tok.kind in {tkComma}):
    pComma p
    pQualifiedIdent p
  discardUnused m102
  wrap p, m0, "bind"
  discardUnused m0

proc pMixinStmt*(p: var Parser) =
  let m0 = mark(p)
  expect p, tkMixin
  pOptInd p
  let m103 = mark(p)
  pQualifiedIdent p
  while (p.tok.kind in {tkComma}):
    pComma p
    pQualifiedIdent p
  discardUnused m103
  wrap p, m0, "mixin"
  discardUnused m0

proc pPragmaStmt*(p: var Parser) =
  let m0 = mark(p)
  pPragma p
  if (p.tok.kind in {tkColon}):
    expect p, tkColon
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    pStmt p
  discardUnused m0

proc pSimpleStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk24):
    let m104 = mark(p)
    if (p.tok.kind in {tkReturn}):
      pReturnStmt p
    elif (p.tok.kind in {tkRaise}):
      pRaiseStmt p
    elif (p.tok.kind in {tkYield}):
      pYieldStmt p
    elif (p.tok.kind in {tkDiscard}):
      pDiscardStmt p
    elif (p.tok.kind in {tkBreak}):
      pBreakStmt p
    elif (p.tok.kind in {tkContinue}):
      pContinueStmt p
    elif (p.tok.kind in {tkCurlyDotLe}):
      pPragmaStmt p
    elif (p.tok.kind in {tkImport}):
      pImportStmt p
    elif (p.tok.kind in {tkExport}):
      pExportStmt p
    elif (p.tok.kind in {tkFrom}):
      pFromStmt p
    elif (p.tok.kind in {tkInclude}):
      pIncludeStmt p
    elif (p.tok.kind in {tkComment}):
      pCommentStmt p
    else:
      error p, "expected alternative"
    discardUnused m104
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
  else:
    pExprStmt p
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
  discardUnused m0

proc pComplexOrSimpleStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk25):
    let m105 = mark(p)
    if (p.tok.kind in {tkIf}):
      pIfStmt p
    elif (p.tok.kind in {tkWhen}):
      pWhenStmt p
    elif (p.tok.kind in {tkWhile}):
      pWhileStmt p
    elif (p.tok.kind in {tkTry}):
      pTryStmt p
    elif (p.tok.kind in {tkFor}):
      pForStmt p
    elif (p.tok.kind in {tkBlock}):
      pBlockStmt p
    elif (p.tok.kind in {tkStatic}):
      pStaticStmt p
    elif (p.tok.kind in {tkDefer}):
      pDeferStmt p
    elif (p.tok.kind in {tkAsm}):
      pAsmStmt p
    elif (p.tok.kind in {tkBind}):
      pBindStmt p
    elif (p.tok.kind in {tkMixin}):
      pMixinStmt p
    elif (p.tok.kind in {tkCase}):
      pCaseStmt p
    else:
      error p, "expected alternative"
    discardUnused m105
  elif (p.tok.kind in {tkExcept}):
    expect p, tkExcept
    pColcom p
    pStmt p
    wrap p, m0, "except"
  elif (p.tok.kind in {tkFinally}):
    expect p, tkFinally
    pColcom p
    pStmt p
    wrap p, m0, "fin"
  elif (p.tok.kind in {tkProc}):
    expect p, tkProc
    pRoutine p
    wrap p, m0, "proc"
  elif (p.tok.kind in {tkMethod}):
    expect p, tkMethod
    pRoutine p
    wrap p, m0, "method"
  elif (p.tok.kind in {tkFunc}):
    expect p, tkFunc
    pRoutine p
    wrap p, m0, "func"
  elif (p.tok.kind in {tkIterator}):
    expect p, tkIterator
    pRoutine p
    wrap p, m0, "iterator"
  elif (p.tok.kind in {tkMacro}):
    expect p, tkMacro
    pRoutine p
    wrap p, m0, "macro"
  elif (p.tok.kind in {tkTemplate}):
    expect p, tkTemplate
    pRoutine p
    wrap p, m0, "template"
  elif (p.tok.kind in {tkConverter}):
    expect p, tkConverter
    pRoutine p
    wrap p, m0, "converter"
  elif (p.tok.kind in {tkType}):
    expect p, tkType
    pSection_typeDef p
  elif (p.tok.kind in {tkConst}):
    expect p, tkConst
    pSection_constant p
  elif (p.tok.kind in {tkLet}):
    expect p, tkLet
    pSection_variable p
  elif (p.tok.kind in {tkVar}):
    expect p, tkVar
    pSection_variable p
  elif (p.tok.kind in {tkUsing}):
    expect p, tkUsing
    pSection_variable p
  else:
    pSimpleStmt p
  discardUnused m0

proc pStmt*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk6 and indClass(p) in {icGt}):
    pushInd p
    let m106 = mark(p)
    pComplexOrSimpleStmt p
    while (p.tok.kind in Tk6 and indClass(p) in {icEq}) or (p.tok.kind in {tkSemiColon}):
      let m107 = mark(p)
      if (p.tok.kind in {tkSemiColon}):
        expect p, tkSemiColon
      else:
        checkInd p, {icEq}
      discardUnused m107
      pComplexOrSimpleStmt p
    if ((p.tok.kind in Tk7)) and indClass(p) == icGt:
      error p, "invalid indentation in stmt"
    discardUnused m106
    popInd p
  elif (p.tok.kind in Tk18 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    let m108 = mark(p)
    pSimpleStmt p
    while (p.tok.kind in {tkSemiColon}):
      expect p, tkSemiColon
      pSimpleStmt p
    discardUnused m108
  else:
    error p, "expected stmt"
  discardUnused m0

proc pSection_typeDef*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk26 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    pTypeDef p
  elif (p.tok.kind in Tk26 and indClass(p) in {icGt}):
    pushInd p
    let m109 = mark(p)
    let m110 = mark(p)
    if (p.tok.kind in Tk11):
      pTypeDef p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m110
    while (p.tok.kind in Tk26 and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m111 = mark(p)
      if (p.tok.kind in Tk11):
        pTypeDef p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m111
    if ((p.tok.kind in Tk26)) and indClass(p) == icGt:
      error p, "invalid indentation in section_typeDef"
    discardUnused m109
    popInd p
  else:
    error p, "expected section_typeDef"
  discardUnused m0

proc pSection_constant*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in Tk27 and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    pConstant p
  elif (p.tok.kind in Tk27 and indClass(p) in {icGt}):
    pushInd p
    let m112 = mark(p)
    let m113 = mark(p)
    if (p.tok.kind in Tk28):
      pConstant p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m113
    while (p.tok.kind in Tk27 and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m114 = mark(p)
      if (p.tok.kind in Tk28):
        pConstant p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m114
    if ((p.tok.kind in Tk27)) and indClass(p) == icGt:
      error p, "invalid indentation in section_constant"
    discardUnused m112
    popInd p
  else:
    error p, "expected section_constant"
  discardUnused m0

proc pSection_variable*(p: var Parser) =
  let m0 = mark(p)
  if (p.tok.kind in {tkComment, tkParLe, tkSymbol} and indClass(p) in {icNoInd, icLt, icEq}):
    pNotInd p
    if (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    pVariable p
  elif (p.tok.kind in {tkComment, tkParLe, tkSymbol} and indClass(p) in {icGt}):
    pushInd p
    let m115 = mark(p)
    let m116 = mark(p)
    if (p.tok.kind in {tkParLe, tkSymbol}):
      pVariable p
    elif (p.tok.kind in {tkComment}):
      emitLeaf p            # COMMENT
    else:
      error p, "expected alternative"
    discardUnused m116
    while (p.tok.kind in {tkComment, tkParLe, tkSymbol} and indClass(p) in {icEq}):
      checkInd p, {icEq}
      let m117 = mark(p)
      if (p.tok.kind in {tkParLe, tkSymbol}):
        pVariable p
      elif (p.tok.kind in {tkComment}):
        emitLeaf p            # COMMENT
      else:
        error p, "expected alternative"
      discardUnused m117
    if ((p.tok.kind in {tkComment, tkParLe, tkSymbol})) and indClass(p) == icGt:
      error p, "invalid indentation in section_variable"
    discardUnused m115
    popInd p
  else:
    error p, "expected section_variable"
  discardUnused m0

