# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

type
  CallConv* = enum
    NoCallConv
    Cdecl = (104, "cdecl")  ## `cdecl` calling convention
    Stdcall = (105, "stdcall")  ## `stdcall` calling convention
    Safecall = (106, "safecall")  ## `safecall` calling convention
    Syscall = (107, "syscall")  ## `syscall` calling convention
    Fastcall = (108, "fastcall")  ## `fastcall` calling convention
    Thiscall = (109, "thiscall")  ## `thiscall` calling convention
    Noconv = (110, "noconv")  ## no explicit calling convention
    Member = (111, "member")  ## `member` calling convention
