# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  FinalIrKind* = enum
    NoVTag
    StoreV = (ord(StoreTagId), "store")  ## `asgn` with reversed operands that reflects evaluation order
    ContinueV = (ord(ContinueTagId), "continue")  ## `continue` statement
    LabV = (ord(LabTagId), "lab")  ## label, target of a `jmp` instruction. Also a **Nimony** statement: `xelim` lowers short-circuit `and`/`or` chains to the flat `(if c (jmp L))` / `(lab L)` form (the two-target condition compiler, see `doc/final_ir.md`), which needs a merge label that is not an enclosing region's end — something `(block)`/`(break)` cannot express without one wrapper per merge
    JmpV = (ord(JmpTagId), "jmp")  ## jump/goto instruction. In Nimony IR it is **forward-only and scoped**: it may leave enclosing constructs but never enter one, and it never crosses a scope that owns destructible locals
    IteV = (ord(IteTagId), "ite")  ## if-then-else followed by `join` information followed by an optional label
    ItecV = (ord(ItecTagId), "itec")  ## if-then-else (that was a `case`)
    LoopV = (ord(LoopTagId), "loop")  ## `loop` components are (before-cond, cond, loop-body, after)
    VV = (ord(VTagId), "v")  ## `versioned` locations
    EtupatV = (ord(EtupatTagId), "etupat")  ## tupat expression for error handling
    UnknownV = (ord(UnknownTagId), "unknown")  ## location's contents is unknown at this point
    JtrueV = (ord(JtrueTagId), "jtrue")  ## set variables v1, v2, ... to `(true)`; hint this should become a jump
    MflagV = (ord(MflagTagId), "mflag")  ## declare a new **materialized** control flow flag `D` of type `bool` initialized to `false`
    VflagV = (ord(VflagTagId), "vflag")  ## declare a new **virtual** control flow flag `D` of type `bool` initialized to `false`
    KillV = (ord(KillTagId), "kill")  ## some.var is about to disappear (scope exit)
    AssumeV = (ord(AssumeTagId), "assume")  ## `assume` pragma/annotation
    AssertV = (ord(AssertTagId), "assert")  ## `assert` pragma/annotation

proc rawTagIsFinalIrKind*(raw: TagEnum): bool {.inline.} =
  raw in {StoreTagId, ContinueTagId, LabTagId, JmpTagId, IteTagId, ItecTagId, LoopTagId, VTagId, EtupatTagId, UnknownTagId, JtrueTagId, MflagTagId, VflagTagId, KillTagId, AssumeTagId, AssertTagId}

