# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  NifIndexKind* = enum
    NoIndexTag
    KvIdx = (28, "kv")  ## key-value pair
    VvIdx = (29, "vv")  ## value-value pair (used for explicitly named arguments in function calls)
    GvarIdx = (51, "gvar")  ## global variable declaration
    TvarIdx = (52, "tvar")  ## thread local variable declaration
    VarIdx = (53, "var")  ## variable declaration
    ConstIdx = (55, "const")  ## const variable declaration
    GletIdx = (57, "glet")  ## global let variable declaration
    TletIdx = (58, "tlet")  ## thread local let variable declaration
    LetIdx = (59, "let")  ## let variable declaration
    CursorIdx = (60, "cursor")  ## cursor variable declaration
    ProcIdx = (64, "proc")  ## proc declaration
    FuncIdx = (65, "func")  ## function declaration
    IteratorIdx = (66, "iterator")  ## iterator declaration
    ConverterIdx = (67, "converter")  ## converter declaration
    MethodIdx = (68, "method")  ## method declaration
    MacroIdx = (69, "macro")  ## macro declaration
    TemplateIdx = (70, "template")  ## template declaration
    TypeIdx = (71, "type")  ## type declaration
    InlineIdx = (123, "inline")  ## `inline` proc annotation
    ExportIdx = (143, "export")  ## `export` statement
    FromexportIdx = (144, "fromexport")  ## specific exported symbols from a module
    ExportexceptIdx = (145, "exportexcept")  ## `exportexcept` statement
    BuildIdx = (204, "build")  ## `build` pragma
    DestroyIdx = (250, "destroy")
    DupIdx = (251, "dup")
    CopyIdx = (252, "copy")
    WasmovedIdx = (253, "wasmoved")
    SinkhIdx = (254, "sinkh")
    TraceIdx = (255, "trace")
    IndexIdx = (263, "index")  ## index section
    PublicIdx = (264, "public")  ## public section
    PrivateIdx = (265, "private")  ## private section

proc rawTagIsNifIndexKind*(raw: TagEnum): bool {.inline.} =
  raw in {KvTagId, VvTagId, GvarTagId, TvarTagId, VarTagId, ConstTagId, GletTagId, TletTagId, LetTagId, CursorTagId, ProcTagId, FuncTagId, IteratorTagId, ConverterTagId, MethodTagId, MacroTagId, TemplateTagId, TypeTagId, InlineTagId, ExportTagId, FromexportTagId, ExportexceptTagId, BuildTagId, DestroyTagId, DupTagId, CopyTagId, WasmovedTagId, SinkhTagId, TraceTagId, IndexTagId, PublicTagId, PrivateTagId}

