# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  NifIndexKind* = enum
    NoIndexTag
    KvIdx = (ord(KvTagId), "kv")  ## key-value pair; optional INTLIT indicates field is in an inherited object
    VvIdx = (ord(VvTagId), "vv")  ## value-value pair (used for explicitly named arguments in function calls)
    GvarIdx = (ord(GvarTagId), "gvar")  ## global variable declaration
    TvarIdx = (ord(TvarTagId), "tvar")  ## thread local variable declaration
    VarIdx = (ord(VarTagId), "var")  ## variable declaration; type slot may be omitted when inferred from initializer
    ConstIdx = (ord(ConstTagId), "const")  ## const variable declaration
    GletIdx = (ord(GletTagId), "glet")  ## global let variable declaration
    TletIdx = (ord(TletTagId), "tlet")  ## thread local let variable declaration
    LetIdx = (ord(LetTagId), "let")  ## let variable declaration; type is optional when used in `(unpackflat …)`
    CursorIdx = (ord(CursorTagId), "cursor")  ## cursor variable declaration
    ProcIdx = (ord(ProcTagId), "proc")  ## proc declaration
    FuncIdx = (ord(FuncTagId), "func")  ## function declaration
    IteratorIdx = (ord(IteratorTagId), "iterator")  ## iterator declaration
    ConverterIdx = (ord(ConverterTagId), "converter")  ## converter declaration
    MethodIdx = (ord(MethodTagId), "method")  ## method declaration
    MacroIdx = (ord(MacroTagId), "macro")  ## macro declaration
    TemplateIdx = (ord(TemplateTagId), "template")  ## template declaration
    TypeIdx = (ord(TypeTagId), "type")  ## type declaration
    InlineIdx = (ord(InlineTagId), "inline")  ## `inline` proc annotation
    ExportIdx = (ord(ExportTagId), "export")  ## `export` statement
    FromexportIdx = (ord(FromexportTagId), "fromexport")  ## specific exported symbols from a module
    ExportexceptIdx = (ord(ExportexceptTagId), "exportexcept")  ## `exportexcept` statement
    BuildIdx = (ord(BuildTagId), "build")  ## `build` pragma
    IndexIdx = (ord(IndexTagId), "index")  ## index section
    BundleIdx = (ord(BundleTagId), "bundle")  ## `bundle` pragma: a custom linker command override `(builder, tool[, args])`; the `tool` is built on demand by `builder` and replaces the final link step, consuming the project's link manifest
    DependencyIdx = (ord(DependencyTagId), "dependency")  ## the files a compile-time computation read, so that a later build knows to redo it. Two producers: a *plugin* emits it as a leading TOP-LEVEL tree beside its output (a sibling of it, not a child), next to `(unusedname …)` — `plugins.dependsOn(path)` — and `slurp`/`staticRead` records the file it folded. `semos.runPlugin` peels it off the plugin output (it never reaches the sem tree) and `semmain.writeNewDepsFile` collects both sources into the module's `.s.deps.nif`, whence `deps.nim` lists them as extra inputs of the next build's `nimsem` node. Paths are absolute. Files only: naming a *directory* tracks add/remove of its direct entries and nothing else, because that is all a directory mtime says

proc rawTagIsNifIndexKind*(raw: TagEnum): bool {.inline.} =
  raw in {KvTagId, VvTagId, GvarTagId, TvarTagId, VarTagId, ConstTagId, GletTagId, TletTagId, LetTagId, CursorTagId, ProcTagId, FuncTagId, IteratorTagId, ConverterTagId, MethodTagId, MacroTagId, TemplateTagId, TypeTagId, InlineTagId, ExportTagId, FromexportTagId, ExportexceptTagId, BuildTagId, IndexTagId, BundleTagId, DependencyTagId}

