# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  NimonyExpr* = enum
    NoExpr
    ErrX = (ord(ErrTagId), "err")  ## indicates an error
    SufX = (ord(SufTagId), "suf")  ## literal with suffix annotation
    AtX = (ord(AtTagId), "at")  ## array indexing operation (typed Nimony form vs untyped Leng form); also used for generic proc/type instantiation `(at callee T1 T2 ...)` where an argument may also be a constant *value* bound to a `staticTypevar`. In a **type** slot the head is normally a type symbol, but it is a *template* symbol when the node is a deferred plugin call (see `(deferexpansion)`): a pass that walks types must not assume the head names a type
    DerefX = (ord(DerefTagId), "deref")  ## pointer deref operation
    DotX = (ord(DotTagId), "dot")  ## object field selection; optional integer is the inheritance depth of the field; optional trailing `STRLIT` is an *access token* carrying the suffix of the module the access was written in. When present, re-checks at expansion/serialization sites judge the private-field access against that module instead of against the module they are running in, so a template body keeps its author's visibility wherever it is expanded. The reserved value `"*"` means "already validated, originating module no longer comparable" and is used by `exprexec`, whose sub-compile runs under a synthesized module suffix. Emitted by sem whenever it resolves a non-exported field.
    PatX = (ord(PatTagId), "pat")  ## pointer indexing operation
    ParX = (ord(ParTagId), "par")  ## syntactic parenthesis
    AddrX = (ord(AddrTagId), "addr")  ## address of operation
    NilX = (ord(NilTagId), "nil")  ## nil pointer value; `T` is the pointer type it stands for. `nil` is the one type-polymorphic literal, so the frontend types every `ptr`/`ref`/`pointer`/`cstring` one (`derefs.nim`) and `T` survives into Leng; only a `nil` a later pass synthesizes is bare. A closure `nil` carries the proc type plus `X`, a nil environment
    InfX = (ord(InfTagId), "inf")  ## positive infinity floating point value
    NeginfX = (ord(NeginfTagId), "neginf")  ## negative infinity floating point value
    NanX = (ord(NanTagId), "nan")  ## NaN floating point value
    FalseX = (ord(FalseTagId), "false")  ## boolean `false` value
    TrueX = (ord(TrueTagId), "true")  ## boolean `true` value
    AndX = (ord(AndTagId), "and")  ## boolean `and` operation; `Y+` form is also used for concept parent lists with more than two parents
    OrX = (ord(OrTagId), "or")  ## boolean `or` operation
    XorX = (ord(XorTagId), "xor")  ## boolean `xor` operation
    NotX = (ord(NotTagId), "not")  ## boolean `not` operation
    NegX = (ord(NegTagId), "neg")  ## negation operation
    SizeofX = (ord(SizeofTagId), "sizeof")  ## `sizeof` operation
    AlignofX = (ord(AlignofTagId), "alignof")  ## `alignof` operation
    OffsetofX = (ord(OffsetofTagId), "offsetof")  ## `offsetof` operation
    OconstrX = (ord(OconstrTagId), "oconstr")  ## object constructor. **Total**: it names every field of `T` — inherited ones included, in any order — so a consumer may store exactly the fields listed and zero nothing, which is what the native back end does. Sem fills in whatever the source omitted (`buildDefaultObjConstr`); a hexer pass that synthesizes a constructor for a type it invented owes the same and gets its defaults from `hexer/defaultvalues`. A `(union)` type is the exception: its members share storage, so only the active one is named
    AconstrX = (ord(AconstrTagId), "aconstr")  ## array constructor
    BracketX = (ord(BracketTagId), "bracket")  ## untyped array constructor
    CurlyX = (ord(CurlyTagId), "curly")  ## untyped set constructor
    CurlyatX = (ord(CurlyatTagId), "curlyat")  ## curly expression `a{i}`
    KvX = (ord(KvTagId), "kv")  ## key-value pair; optional INTLIT indicates field is in an inherited object
    OvfX = (ord(OvfTagId), "ovf")  ## access overflow flag
    AddX = (ord(AddTagId), "add")
    SubX = (ord(SubTagId), "sub")
    MulX = (ord(MulTagId), "mul")
    DivX = (ord(DivTagId), "div")
    ModX = (ord(ModTagId), "mod")
    ShrX = (ord(ShrTagId), "shr")
    ShlX = (ord(ShlTagId), "shl")
    BitandX = (ord(BitandTagId), "bitand")
    BitorX = (ord(BitorTagId), "bitor")
    BitxorX = (ord(BitxorTagId), "bitxor")
    BitnotX = (ord(BitnotTagId), "bitnot")
    EqX = (ord(EqTagId), "eq")
    NeqX = (ord(NeqTagId), "neq")
    LeX = (ord(LeTagId), "le")
    LtX = (ord(LtTagId), "lt")
    CastX = (ord(CastTagId), "cast")  ## `cast` operation (typed cast expression, or `{.cast(pragma).}` pragma form)
    ConvX = (ord(ConvTagId), "conv")  ## type conversion
    CallX = (ord(CallTagId), "call")  ## call operation
    CmdX = (ord(CmdTagId), "cmd")  ## command operation
    CchoiceX = (ord(CchoiceTagId), "cchoice")  ## closed choice
    OchoiceX = (ord(OchoiceTagId), "ochoice")  ## open choice
    PragmaxX = (ord(PragmaxTagId), "pragmax")  ## pragma expressions
    QuotedX = (ord(QuotedTagId), "quoted")  ## name in backticks
    HderefX = (ord(HderefTagId), "hderef")  ## hidden pointer deref operation
    DdotX = (ord(DdotTagId), "ddot")  ## deref dot: expression, field symbol, field index; optional trailing `STRLIT` is the same *access token* described on `(dot ...)` — names the module the private-field access was written in, which is what a re-check judges it against.
    HaddrX = (ord(HaddrTagId), "haddr")  ## hidden address: an address the COMPILER took to bind a location, not one the user asked for. `derefs.nim` inserts it wherever a `var`/`out` parameter needs the argument's location. It survives into Leng — where `(addr X)` is the user's `addr` — because the two mean different things to a consumer: `(addr x)` says "x's address is a value now", so x must have one, while `(haddr x)` says only "the callee wants x's *location*". An `(instr …)` operand slot whose row is `inout` can therefore bind the local's home directly instead of forcing it to memory. Everywhere else it lowers exactly like `(addr X)`
    NewrefX = (ord(NewrefTagId), "newref")  ## Nim's `new` magic proc that allocates a `ref T`; optional initializer expression
    NewobjX = (ord(NewobjTagId), "newobj")  ## new object constructor
    TupX = (ord(TupTagId), "tup")  ## untyped tuple constructor
    TupconstrX = (ord(TupconstrTagId), "tupconstr")  ## tuple constructor
    SetconstrX = (ord(SetconstrTagId), "setconstr")  ## set constructor
    TabconstrX = (ord(TabconstrTagId), "tabconstr")  ## table constructor
    AshrX = (ord(AshrTagId), "ashr")
    BaseobjX = (ord(BaseobjTagId), "baseobj")  ## object conversion to base type
    HconvX = (ord(HconvTagId), "hconv")  ## hidden basic type conversion
    DconvX = (ord(DconvTagId), "dconv")  ## conversion between `distinct` types
    CallstrlitX = (ord(CallstrlitTagId), "callstrlit")
    InfixX = (ord(InfixTagId), "infix")  ## infix call form kept verbatim inside unsem'd bodies: operator followed by two or more operands (extra args come from default parameters, e.g. `s $ 80` → `` `$`(s, 80, defaultReplacement) ``)
    PrefixX = (ord(PrefixTagId), "prefix")  ## prefix call form kept verbatim inside unsem'd bodies: operator followed by single operand
    HcallX = (ord(HcallTagId), "hcall")  ## hidden converter call
    CompilesX = (ord(CompilesTagId), "compiles")
    DeclaredX = (ord(DeclaredTagId), "declared")
    DefinedX = (ord(DefinedTagId), "defined")
    AstToStrX = (ord(AstToStrTagId), "astToStr")  ## converts AST to string
    BindSymX = (ord(BindSymTagId), "bindSym")  ## hygienic symbol reference inside a macro body: at sem time, resolves the string-literal argument in the macro's *definition* scope and replaces the call with a `(call newSymNode "<full-sym-name>")` so the plugin emits a NIF Symbol token that bypasses call-site lookup
    BindSymNameX = (ord(BindSymNameTagId), "bindSymName")  ## plugin-side cousin of `bindSym`: at sem time, resolves the string-literal argument in the surrounding module's *definition* scope and replaces the call with a `StringLit` carrying the fully-qualified symbol name. Plugin authors feed the resulting string to `addSymUse(builder, name)` so the emitted NIF contains a resolved `Symbol` token.
    InstanceofX = (ord(InstanceofTagId), "instanceof")  ## only-fans operator for object privilege checking
    ProccallX = (ord(ProccallTagId), "proccall")  ## like the `call` tag but always a static call (no dynamic method) dispatch
    HighX = (ord(HighTagId), "high")
    LowX = (ord(LowTagId), "low")
    TypeofX = (ord(TypeofTagId), "typeof")  ## `typeof` operation for accessing the type of an expression
    UnpackX = (ord(UnpackTagId), "unpack")  ## magic varargs expansion — see *Tuple Unpacking* section below
    FieldsX = (ord(FieldsTagId), "fields")  ## fields iterator
    FieldpairsX = (ord(FieldpairsTagId), "fieldpairs")  ## fieldPairs iterator
    EnumtostrX = (ord(EnumtostrTagId), "enumtostr")
    IsmainmoduleX = (ord(IsmainmoduleTagId), "ismainmodule")
    DefaultobjX = (ord(DefaultobjTagId), "defaultobj")
    DefaulttupX = (ord(DefaulttupTagId), "defaulttup")
    DefaultdistinctX = (ord(DefaultdistinctTagId), "defaultdistinct")
    DelayX = (ord(DelayTagId), "delay")  ## `delay(fn args)` builtin for delayed continuation creation
    Delay0X = (ord(Delay0TagId), "delay0")  ## `delay()` no-arg: capture current coroutine's own continuation
    SuspendX = (ord(SuspendTagId), "suspend")  ## `suspend()` magic proc: parks the coroutine and returns Continuation(nil, env)
    ExprX = (ord(ExprTagId), "expr")
    DoX = (ord(DoTagId), "do")  ## `do` expression
    ArratX = (ord(ArratTagId), "arrat")  ## two optional exprs: `high` boundary and the `low` boundary (if != 0)
    TupatX = (ord(TupatTagId), "tupat")
    PlussetX = (ord(PlussetTagId), "plusset")
    MinussetX = (ord(MinussetTagId), "minusset")
    MulsetX = (ord(MulsetTagId), "mulset")
    XorsetX = (ord(XorsetTagId), "xorset")
    EqsetX = (ord(EqsetTagId), "eqset")
    LesetX = (ord(LesetTagId), "leset")
    LtsetX = (ord(LtsetTagId), "ltset")
    InsetX = (ord(InsetTagId), "inset")
    CardX = (ord(CardTagId), "card")
    EmoveX = (ord(EmoveTagId), "emove")
    DestroyX = (ord(DestroyTagId), "destroy")
    DupX = (ord(DupTagId), "dup")
    CopyX = (ord(CopyTagId), "copy")
    WasmovedX = (ord(WasmovedTagId), "wasmoved")
    SinkhX = (ord(SinkhTagId), "sinkh")
    TraceX = (ord(TraceTagId), "trace")
    InternalTypeNameX = (ord(InternalTypeNameTagId), "internalTypeName")  ## returns compiler's internal type name
    InternalFieldPairsX = (ord(InternalFieldPairsTagId), "internalFieldPairs")  ## variant of fieldPairs iterator returns compiler's internal field name
    FailedX = (ord(FailedTagId), "failed")  ## used to access the hidden failure flag for raising calls
    IsX = (ord(IsTagId), "is")  ## `is` operator
    EnvpX = (ord(EnvpTagId), "envp")  ## `envp.Y` field access to hidden `env` parameter which is of type `T`
    ToClosureX = (ord(ToClosureTagId), "toClosure")  ## converts non closure proc to closure proc

proc rawTagIsNimonyExpr*(raw: TagEnum): bool {.inline.} =
  raw in {ErrTagId, SufTagId, AtTagId, DerefTagId, DotTagId, PatTagId, ParTagId, AddrTagId, NilTagId, InfTagId, NeginfTagId, NanTagId, FalseTagId, TrueTagId, AndTagId, OrTagId, XorTagId, NotTagId, NegTagId, SizeofTagId, AlignofTagId, OffsetofTagId, OconstrTagId, AconstrTagId, BracketTagId, CurlyTagId, CurlyatTagId, KvTagId, OvfTagId, AddTagId, SubTagId, MulTagId, DivTagId, ModTagId, ShrTagId, ShlTagId, BitandTagId, BitorTagId, BitxorTagId, BitnotTagId, EqTagId, NeqTagId, LeTagId, LtTagId, CastTagId, ConvTagId, CallTagId, CmdTagId, CchoiceTagId, OchoiceTagId, PragmaxTagId, QuotedTagId, HderefTagId, DdotTagId, HaddrTagId, NewrefTagId, NewobjTagId, TupTagId, TupconstrTagId, SetconstrTagId, TabconstrTagId, AshrTagId, BaseobjTagId, HconvTagId, DconvTagId, CallstrlitTagId, InfixTagId, PrefixTagId, HcallTagId, CompilesTagId, DeclaredTagId, DefinedTagId, AstToStrTagId, BindSymTagId, BindSymNameTagId, InstanceofTagId, ProccallTagId, HighTagId, LowTagId, TypeofTagId, UnpackTagId, FieldsTagId, FieldpairsTagId, EnumtostrTagId, IsmainmoduleTagId, DefaultobjTagId, DefaulttupTagId, DefaultdistinctTagId, DelayTagId, Delay0TagId, SuspendTagId, ExprTagId, DoTagId, ArratTagId, TupatTagId, PlussetTagId, MinussetTagId, MulsetTagId, XorsetTagId, EqsetTagId, LesetTagId, LtsetTagId, InsetTagId, CardTagId, EmoveTagId, DestroyTagId, DupTagId, CopyTagId, WasmovedTagId, SinkhTagId, TraceTagId, InternalTypeNameTagId, InternalFieldPairsTagId, FailedTagId, IsTagId, EnvpTagId, ToClosureTagId}

type
  NimonyStmt* = enum
    NoStmt
    CallS = (ord(CallTagId), "call")  ## call operation
    CmdS = (ord(CmdTagId), "cmd")  ## command operation
    GvarS = (ord(GvarTagId), "gvar")  ## global variable declaration
    TvarS = (ord(TvarTagId), "tvar")  ## thread local variable declaration
    VarS = (ord(VarTagId), "var")  ## variable declaration; type slot may be omitted when inferred from initializer
    ConstS = (ord(ConstTagId), "const")  ## const variable declaration
    ResultS = (ord(ResultTagId), "result")  ## result variable declaration
    GletS = (ord(GletTagId), "glet")  ## global let variable declaration
    TletS = (ord(TletTagId), "tlet")  ## thread local let variable declaration
    LetS = (ord(LetTagId), "let")  ## let variable declaration; type is optional when used in `(unpackflat …)`
    CursorS = (ord(CursorTagId), "cursor")  ## cursor variable declaration
    PatternvarS = (ord(PatternvarTagId), "patternvar")  ## pattern variable declaration
    ProcS = (ord(ProcTagId), "proc")  ## proc declaration
    FuncS = (ord(FuncTagId), "func")  ## function declaration
    IteratorS = (ord(IteratorTagId), "iterator")  ## iterator declaration
    ConverterS = (ord(ConverterTagId), "converter")  ## converter declaration
    MethodS = (ord(MethodTagId), "method")  ## method declaration
    MacroS = (ord(MacroTagId), "macro")  ## macro declaration
    TemplateS = (ord(TemplateTagId), "template")  ## template declaration
    TypeS = (ord(TypeTagId), "type")  ## type declaration
    BlockS = (ord(BlockTagId), "block")  ## block declaration
    EmitS = (ord(EmitTagId), "emit")  ## emit statement
    AsgnS = (ord(AsgnTagId), "asgn")  ## assignment statement
    ScopeS = (ord(ScopeTagId), "scope")  ## explicit scope annotation, like `stmts`
    IfS = (ord(IfTagId), "if")  ## if statement header
    WhenS = (ord(WhenTagId), "when")  ## when statement header
    BreakS = (ord(BreakTagId), "break")  ## `break` statement
    ContinueS = (ord(ContinueTagId), "continue")  ## `continue` statement
    ForS = (ord(ForTagId), "for")  ## for statement
    WhileS = (ord(WhileTagId), "while")  ## `while` statement
    CoroforS = (ord(CoroforTagId), "corofor")  ## closure-iterator for loop, lowered shape used between iterinliner and cps; first child is the iterator call, second child is a `(stmts ...)` whose first inner statement is a `(var :forLoopVar T .)` declaration that receives each yielded value
    CaseS = (ord(CaseTagId), "case")  ## `case` statement
    LabS = (ord(LabTagId), "lab")  ## label, target of a `jmp` instruction. Also a **Nimony** statement: `xelim` lowers short-circuit `and`/`or` chains to the flat `(if c (jmp L))` / `(lab L)` form (the two-target condition compiler, see `doc/final_ir.md`), which needs a merge label that is not an enclosing region's end — something `(block)`/`(break)` cannot express without one wrapper per merge
    JmpS = (ord(JmpTagId), "jmp")  ## jump/goto instruction. In Nimony IR it is **forward-only and scoped**: it may leave enclosing constructs but never enter one, and it never crosses a scope that owns destructible locals
    RetS = (ord(RetTagId), "ret")  ## `return` instruction
    YldS = (ord(YldTagId), "yld")  ## yield statement
    StmtsS = (ord(StmtsTagId), "stmts")  ## list of statements
    PragmasS = (ord(PragmasTagId), "pragmas")  ## begin of pragma section
    PragmaxS = (ord(PragmaxTagId), "pragmax")  ## pragma expressions
    InclS = (ord(InclTagId), "incl")  ## `incl` set operation; first child is the set's element type
    ExclS = (ord(ExclTagId), "excl")  ## `excl` set operation; first child is the set's element type
    IncludeS = (ord(IncludeTagId), "include")  ## `include` statement
    ImportS = (ord(ImportTagId), "import")  ## `import` statement
    ImportasS = (ord(ImportasTagId), "importas")  ## `import as` statement
    FromimportS = (ord(FromimportTagId), "fromimport")  ## `from import` statement
    ImportexceptS = (ord(ImportexceptTagId), "importexcept")  ## `importexcept` statement
    ExportS = (ord(ExportTagId), "export")  ## `export` statement
    ExportexceptS = (ord(ExportexceptTagId), "exportexcept")  ## `exportexcept` statement
    CommentS = (ord(CommentTagId), "comment")  ## `comment` statement; also used as a variadic trailer for module metadata
    DiscardS = (ord(DiscardTagId), "discard")  ## `discard` statement; optional expression to discard
    TryS = (ord(TryTagId), "try")  ## `try` statement
    RaiseS = (ord(RaiseTagId), "raise")  ## `raise` statement; bare `(raise .)` re-raises the in-flight exception (only valid inside an `except` block)
    UnpackdeclS = (ord(UnpackdeclTagId), "unpackdecl")  ## unpack var/let/const declaration
    AssumeS = (ord(AssumeTagId), "assume")  ## `assume` pragma/annotation
    AssertS = (ord(AssertTagId), "assert")  ## `assert` pragma/annotation
    CallstrlitS = (ord(CallstrlitTagId), "callstrlit")
    InfixS = (ord(InfixTagId), "infix")  ## infix call form kept verbatim inside unsem'd bodies: operator followed by two or more operands (extra args come from default parameters, e.g. `s $ 80` → `` `$`(s, 80, defaultReplacement) ``)
    PrefixS = (ord(PrefixTagId), "prefix")  ## prefix call form kept verbatim inside unsem'd bodies: operator followed by single operand
    HcallS = (ord(HcallTagId), "hcall")  ## hidden converter call
    StaticstmtS = (ord(StaticstmtTagId), "staticstmt")  ## `static` statement
    BindS = (ord(BindTagId), "bind")  ## `bind` statement
    MixinS = (ord(MixinTagId), "mixin")  ## `mixin` statement
    UsingS = (ord(UsingTagId), "using")  ## `using` statement
    AsmS = (ord(AsmTagId), "asm")  ## `asm` statement
    DeferS = (ord(DeferTagId), "defer")  ## `defer` statement

proc rawTagIsNimonyStmt*(raw: TagEnum): bool {.inline.} =
  raw in {CallTagId, CmdTagId, GvarTagId, TvarTagId, VarTagId, ConstTagId, ResultTagId, GletTagId, TletTagId, LetTagId, CursorTagId, PatternvarTagId, ProcTagId, FuncTagId, IteratorTagId, ConverterTagId, MethodTagId, MacroTagId, TemplateTagId, TypeTagId, BlockTagId, EmitTagId, AsgnTagId, ScopeTagId, IfTagId, WhenTagId, BreakTagId, ContinueTagId, ForTagId, WhileTagId, CoroforTagId, CaseTagId, LabTagId, JmpTagId, RetTagId, YldTagId, StmtsTagId, PragmasTagId, PragmaxTagId, InclTagId, ExclTagId, IncludeTagId, ImportTagId, ImportasTagId, FromimportTagId, ImportexceptTagId, ExportTagId, ExportexceptTagId, CommentTagId, DiscardTagId, TryTagId, RaiseTagId, UnpackdeclTagId, AssumeTagId, AssertTagId, CallstrlitTagId, InfixTagId, PrefixTagId, HcallTagId, StaticstmtTagId, BindTagId, MixinTagId, UsingTagId, AsmTagId, DeferTagId}

type
  NimonyType* = enum
    NoType
    ErrT = (ord(ErrTagId), "err")  ## indicates an error
    AtT = (ord(AtTagId), "at")  ## array indexing operation (typed Nimony form vs untyped Leng form); also used for generic proc/type instantiation `(at callee T1 T2 ...)` where an argument may also be a constant *value* bound to a `staticTypevar`. In a **type** slot the head is normally a type symbol, but it is a *template* symbol when the node is a deferred plugin call (see `(deferexpansion)`): a pass that walks types must not assume the head names a type
    AndT = (ord(AndTagId), "and")  ## boolean `and` operation; `Y+` form is also used for concept parent lists with more than two parents
    OrT = (ord(OrTagId), "or")  ## boolean `or` operation
    NotT = (ord(NotTagId), "not")  ## boolean `not` operation
    ProcT = (ord(ProcTagId), "proc")  ## proc declaration
    FuncT = (ord(FuncTagId), "func")  ## function declaration
    IteratorT = (ord(IteratorTagId), "iterator")  ## iterator declaration
    ConverterT = (ord(ConverterTagId), "converter")  ## converter declaration
    MethodT = (ord(MethodTagId), "method")  ## method declaration
    MacroT = (ord(MacroTagId), "macro")  ## macro declaration
    TemplateT = (ord(TemplateTagId), "template")  ## template declaration
    ObjectT = (ord(ObjectTagId), "object")  ## object type declaration
    EnumT = (ord(EnumTagId), "enum")  ## enum type declaration
    ProctypeT = (ord(ProctypeTagId), "proctype")  ## Nimony proc type. Slot 0 carries the nilability tag — either a `.` placeholder or one of `(notnil)`, `(nil)`, `(unchecked)`. Leng proc type, same shape as `(proc D ...)` with anonymous name slot (varargs spec; effects/body slots present but unused).
    IT = (ord(ITagId), "i")  ## `int` builtin type
    UT = (ord(UTagId), "u")  ## `uint` builtin type; size in bits followed by optional attributes (`(importc ...)`, `(header ...)`, etc.)
    FT = (ord(FTagId), "f")  ## `float` builtin type
    CT = (ord(CTagId), "c")  ## `char` builtin type
    BoolT = (ord(BoolTagId), "bool")  ## `bool` builtin type
    VoidT = (ord(VoidTagId), "void")  ## `void` return type
    PtrT = (ord(PtrTagId), "ptr")  ## `ptr` type contructor; the `(unchecked)` pragma relaxes nil checking on deref
    ArrayT = (ord(ArrayTagId), "array")  ## `array` type constructor (element type, index type/range)
    VarargsT = (ord(VarargsTagId), "varargs")  ## `varargs` type/proc annotation: Nimony carries the element type and an optional transformer symbol (e.g. `` `$` ``); Leng keeps only the element type
    StaticT = (ord(StaticTagId), "static")  ## `static` type or annotation
    TupleT = (ord(TupleTagId), "tuple")  ## `tuple` type
    ClosureTupleT = (ord(ClosureTupleTagId), "closureTuple")  ## internal lifted-closure tuple type: `(closureTuple <proctype> (ref RootObj))`. Structurally a two-element tuple — a function pointer plus its environment — but tagged distinctly so lambda lifting and the coroutine transform can recognize an *already lifted* closure/iterator value by its tag instead of by probing a plain `(tuple ...)`. Produced by `hexer`'s `lambdalifting`/`coro_transform`/`cps` only; `lengcgen` lowers it to an ordinary Leng `(tuple ...)`
    OnumT = (ord(OnumTagId), "onum")  ## enum with holes type
    AnumT = (ord(AnumTagId), "anum")  ## sum type discriminator enum ("auto enum")
    RefT = (ord(RefTagId), "ref")  ## `ref` type; the `(unchecked)` pragma relaxes nil checking on deref
    MutT = (ord(MutTagId), "mut")  ## `mut` type
    OutT = (ord(OutTagId), "out")  ## `out` type
    LentT = (ord(LentTagId), "lent")  ## `lent` type
    SinkT = (ord(SinkTagId), "sink")  ## `sink` type
    NiltT = (ord(NiltTagId), "nilt")  ## `nilt` type
    ConceptT = (ord(ConceptTagId), "concept")  ## `concept` type: two reserved slots, optional parent concepts (`.` / sym / `(and ...)`), a `Self` typevar `D`, and the concept body statements `S*` (body may be empty when parents are present)
    DistinctT = (ord(DistinctTagId), "distinct")  ## `distinct` type
    ItertypeT = (ord(ItertypeTagId), "itertype")  ## Nimony iterator type — first-class closure-iterator value at the type level. Shape mirrors `(proctype ...)`: slot 0 carries the nilability tag (`.` placeholder or one of `(notnil)`, `(nil)`, `(unchecked)`); remaining slots are params, return type, pragmas.
    RangetypeT = (ord(RangetypeTagId), "rangetype")  ## `rangetype` type
    UarrayT = (ord(UarrayTagId), "uarray")  ## `uarray` type
    SetT = (ord(SetTagId), "set")  ## `set` type
    AutoT = (ord(AutoTagId), "auto")  ## `auto` type
    SymkindT = (ord(SymkindTagId), "symkind")  ## `symkind` type
    TypekindT = (ord(TypekindTagId), "typekind")  ## `typekind` type
    TypedescT = (ord(TypedescTagId), "typedesc")  ## `typedesc` type
    UntypedT = (ord(UntypedTagId), "untyped")  ## `untyped` type
    TypedT = (ord(TypedTagId), "typed")  ## `typed` type
    CstringT = (ord(CstringTagId), "cstring")  ## `cstring` type; optional first child is the string literal used in a `cstring"…"` generalized string; further attributes carry importc/header overrides inlined from `{.importc.}` aliases
    PointerT = (ord(PointerTagId), "pointer")  ## `pointer` type; the optional `(nil)` annotation marks a nilable pointer; further attributes carry importc/header overrides inlined from `{.importc.}` aliases
    OrdinalT = (ord(OrdinalTagId), "ordinal")  ## `ordinal` type

proc rawTagIsNimonyType*(raw: TagEnum): bool {.inline.} =
  raw in {ErrTagId, AtTagId, AndTagId, OrTagId, NotTagId, ProcTagId, FuncTagId, IteratorTagId, ConverterTagId, MethodTagId, MacroTagId, TemplateTagId, ObjectTagId, EnumTagId, ProctypeTagId, ITagId, UTagId, FTagId, CTagId, BoolTagId, VoidTagId, PtrTagId, ArrayTagId, VarargsTagId, StaticTagId, TupleTagId, ClosureTupleTagId, OnumTagId, AnumTagId, RefTagId, MutTagId, OutTagId, LentTagId, SinkTagId, NiltTagId, ConceptTagId, DistinctTagId, ItertypeTagId, RangetypeTagId, UarrayTagId, SetTagId, AutoTagId, SymkindTagId, TypekindTagId, TypedescTagId, UntypedTagId, TypedTagId, CstringTagId, PointerTagId, OrdinalTagId}

type
  NimonyOther* = enum
    NoSub
    NilU = (ord(NilTagId), "nil")  ## nil pointer value; `T` is the pointer type it stands for. `nil` is the one type-polymorphic literal, so the frontend types every `ptr`/`ref`/`pointer`/`cstring` one (`derefs.nim`) and `T` survives into Leng; only a `nil` a later pass synthesizes is bare. A closure `nil` carries the proc type plus `X`, a nil environment
    NotnilU = (ord(NotnilTagId), "notnil")  ## `not nil` pointer annotation
    UncheckedU = (ord(UncheckedTagId), "unchecked")  ## `unchecked` pointer annotation (derefs do not require nil checking)
    KvU = (ord(KvTagId), "kv")  ## key-value pair; optional INTLIT indicates field is in an inherited object
    VvU = (ord(VvTagId), "vv")  ## value-value pair (used for explicitly named arguments in function calls)
    RangeU = (ord(RangeTagId), "range")  ## `(range a b)` construct
    RangesU = (ord(RangesTagId), "ranges")
    ParamU = (ord(ParamTagId), "param")  ## parameter declaration
    TypevarU = (ord(TypevarTagId), "typevar")  ## type variable declaration; constraint `.T` is optional
    StaticTypevarU = (ord(StaticTypevarTagId), "staticTypevar")  ## value generic parameter: a generic parameter that is a compile-time *value*; the type slot holds the value's plain element type (e.g. `int` for `N: static[int]`), never a `static` wrapper
    EfldU = (ord(EfldTagId), "efld")  ## enum field declaration; slot 2 carries the export marker *or* the compile-time value (may be `.`)
    FldU = (ord(FldTagId), "fld")  ## field declaration
    GfldU = (ord(GfldTagId), "gfld")  ## guarded field declaration, cannot be accessed outside an `of` branch
    WhenU = (ord(WhenTagId), "when")  ## when statement header
    ElifU = (ord(ElifTagId), "elif")  ## pair of (condition, action)
    ElseU = (ord(ElseTagId), "else")  ## `else` action
    TypevarsU = (ord(TypevarsTagId), "typevars")  ## type variable/generic parameters; after sem an entry may also be a `(staticTypevar ...)`
    CaseU = (ord(CaseTagId), "case")  ## `case` statement
    OfU = (ord(OfTagId), "of")  ## `of` branch within a `case` statement
    StmtsU = (ord(StmtsTagId), "stmts")  ## list of statements
    ParamsU = (ord(ParamsTagId), "params")  ## list of proc parameters, also used as a "proc type"
    PragmasU = (ord(PragmasTagId), "pragmas")  ## begin of pragma section
    EitherU = (ord(EitherTagId), "either")  ## `either` construct to combine location versions
    JoinU = (ord(JoinTagId), "join")  ## `join` construct inside `ite`
    UnpackflatU = (ord(UnpackflatTagId), "unpackflat")  ## unpack into flat variable list
    UnpacktupU = (ord(UnpacktupTagId), "unpacktup")  ## unpack tuple
    CallargsU = (ord(CallargsTagId), "callargs")  ## grouped call arguments in a for-loop plugin input
    ForcallU = (ord(ForcallTagId), "forcall")  ## for-loop plugin input: the iterator name, grouped call arguments, loop variables, and the loop body
    ExceptU = (ord(ExceptTagId), "except")  ## except subsection
    FinU = (ord(FinTagId), "fin")  ## finally subsection
    DeferexpansionU = (ord(DeferexpansionTagId), "deferexpansion")  ## emitted by a template *plugin* as its entire output to say "I cannot answer while the argument still contains type variables — ask me again after instantiation". The compiler then parks the sem-checked call in the tree as `(at <template> <args>…)` instead of replacing it with an expansion — `(at …)` because that is the only unresolved type application a type slot accepts. `subsGenericProc` substitutes into it like any other type, and the instantiation's re-sem turns it back into a call, which drives the plugin again with concrete types. Rejected (a hard error) when no argument contains a generic parameter, which is what makes the retry well-founded
    NeedtypesU = (ord(NeedtypesTagId), "needtypes")  ## emitted by a template *plugin* as its entire output to ask the compiler for the declarations of the named symbols. The compiler appends them to the plugin's second input (`loadTypeDefinitions()`) and runs the plugin again. This is how a plugin resolves a nominal type: it arrives in the main input as an opaque `Symbol`, and a plugin runs in its own process with no way to look it up. Only what is asked for is shipped, so a plugin that never asks pays nothing. Requesting a symbol that was already provided is a hard error, which is what bounds the loop

proc rawTagIsNimonyOther*(raw: TagEnum): bool {.inline.} =
  raw in {NilTagId, NotnilTagId, UncheckedTagId, KvTagId, VvTagId, RangeTagId, RangesTagId, ParamTagId, TypevarTagId, StaticTypevarTagId, EfldTagId, FldTagId, GfldTagId, WhenTagId, ElifTagId, ElseTagId, TypevarsTagId, CaseTagId, OfTagId, StmtsTagId, ParamsTagId, PragmasTagId, EitherTagId, JoinTagId, UnpackflatTagId, UnpacktupTagId, CallargsTagId, ForcallTagId, ExceptTagId, FinTagId, DeferexpansionTagId, NeedtypesTagId}

type
  NimonyPragma* = enum
    NoPragma
    CastP = (ord(CastTagId), "cast")  ## `cast` operation (typed cast expression, or `{.cast(pragma).}` pragma form)
    CursorP = (ord(CursorTagId), "cursor")  ## cursor variable declaration
    EmitP = (ord(EmitTagId), "emit")  ## emit statement
    UnionP = (ord(UnionTagId), "union")  ## first one is Leng union declaration, second one is Nimony union pragma
    InlineP = (ord(InlineTagId), "inline")  ## `inline` proc annotation
    NoinlineP = (ord(NoinlineTagId), "noinline")  ## `noinline` proc annotation
    ClosureP = (ord(ClosureTagId), "closure")  ## `closure` proc annotation; not a calling convention anymore, simply annotates a proc as a closure
    VarargsP = (ord(VarargsTagId), "varargs")  ## `varargs` type/proc annotation: Nimony carries the element type and an optional transformer symbol (e.g. `` `$` ``); Leng keeps only the element type
    SelectanyP = (ord(SelectanyTagId), "selectany")
    AlignP = (ord(AlignTagId), "align")
    BitsP = (ord(BitsTagId), "bits")
    NodeclP = (ord(NodeclTagId), "nodecl")  ## `nodecl` annotation
    RaisesP = (ord(RaisesTagId), "raises")  ## proc annotation; optional list of exception types the proc may raise
    UntypedP = (ord(UntypedTagId), "untyped")  ## `untyped` type
    MagicP = (ord(MagicTagId), "magic")  ## `magic` pragma; argument is the magic's name as string literal or ident (e.g. `"Bool"`, `HoleyEnum`)
    ImportcP = (ord(ImportcTagId), "importc")  ## `importc` pragma
    ImportcppP = (ord(ImportcppTagId), "importcpp")  ## `importcpp` pragma
    DynlibP = (ord(DynlibTagId), "dynlib")  ## `dynlib` pragma; on a Leng decl: static import library of an `importc` proc (native backend): the declaration binds through the image's import table instead of a runtime loader stub
    ExportcP = (ord(ExportcTagId), "exportc")  ## `exportc` pragma
    HeaderP = (ord(HeaderTagId), "header")  ## `header` pragma
    ThreadvarP = (ord(ThreadvarTagId), "threadvar")  ## `threadvar` pragma
    GlobalP = (ord(GlobalTagId), "global")  ## `global` pragma
    DiscardableP = (ord(DiscardableTagId), "discardable")  ## `discardable` pragma
    NoreturnP = (ord(NoreturnTagId), "noreturn")  ## `noreturn` pragma
    BorrowP = (ord(BorrowTagId), "borrow")  ## `borrow` pragma
    NoSideEffectP = (ord(NoSideEffectTagId), "noSideEffect")  ## `noSideEffect` pragma
    NodestroyP = (ord(NodestroyTagId), "nodestroy")  ## `nodestroy` pragma
    PluginP = (ord(PluginTagId), "plugin")  ## `plugin` pragma
    BycopyP = (ord(BycopyTagId), "bycopy")  ## `bycopy` pragma
    ByrefP = (ord(ByrefTagId), "byref")  ## `byref` pragma
    NoinitP = (ord(NoinitTagId), "noinit")  ## `noinit` pragma
    RequiresP = (ord(RequiresTagId), "requires")  ## `requires` pragma
    EnsuresP = (ord(EnsuresTagId), "ensures")  ## `ensures` pragma
    AssumeP = (ord(AssumeTagId), "assume")  ## `assume` pragma/annotation
    AssertP = (ord(AssertTagId), "assert")  ## `assert` pragma/annotation
    BuildP = (ord(BuildTagId), "build")  ## `build` pragma
    FeatureP = (ord(FeatureTagId), "feature")  ## `feature` pragma
    StringP = (ord(StringTagId), "string")  ## `string` pragma
    ViewP = (ord(ViewTagId), "view")  ## `view` pragma
    EstablishesBorrowP = (ord(EstablishesBorrowTagId), "establishesBorrow")  ## `establishesBorrow` pragma: the routine's result borrows from its first parameter. `let v = f(x)` then starts a borrow of `x` that lasts until `v` dies, so `x` cannot be mutated or passed to a `var` parameter in between. This is what carries the borrow across the call boundary for view constructors such as `toOpenArray`, whose bodies build the view out of a raw pointer the borrow checker cannot follow.
    IncompleteStructP = (ord(IncompleteStructTagId), "incompleteStruct")  ## `incompleteStruct` pragma
    InjectP = (ord(InjectTagId), "inject")  ## `inject` pragma
    GensymP = (ord(GensymTagId), "gensym")  ## `gensym` pragma
    DirtyP = (ord(DirtyTagId), "dirty")  ## `dirty` pragma
    ErrorP = (ord(ErrorTagId), "error")  ## `error` pragma
    ReportP = (ord(ReportTagId), "report")  ## `report` pragma
    TagsP = (ord(TagsTagId), "tags")  ## `tags` effect annotation
    DeprecatedP = (ord(DeprecatedTagId), "deprecated")  ## `deprecated` pragma
    SideEffectP = (ord(SideEffectTagId), "sideEffect")  ## explicit `sideEffect` pragma
    KeepOverflowFlagP = (ord(KeepOverflowFlagTagId), "keepOverflowFlag")  ## keep overflow flag
    SemanticsP = (ord(SemanticsTagId), "semantics")  ## proc with builtin behavior for expreval
    InheritableP = (ord(InheritableTagId), "inheritable")  ## `inheritable` pragma
    BaseP = (ord(BaseTagId), "base")  ## `base` pragma (currently ignored)
    PureP = (ord(PureTagId), "pure")  ## `pure` pragma (currently ignored)
    FinalP = (ord(FinalTagId), "final")  ## `final` pragma
    AcyclicP = (ord(AcyclicTagId), "acyclic")  ## `acyclic` pragma (currently ignored)
    PragmaP = (ord(PragmaTagId), "pragma")  ## `pragma` pragma
    PackedP = (ord(PackedTagId), "packed")  ## `packed` pragma
    PassiveP = (ord(PassiveTagId), "passive")  ## `passive` pragma
    PushP = (ord(PushTagId), "push")  ## `push` pragma
    CallConvP = (ord(CallConvTagId), "callConv")  ## `callConv` pragma for setting calling convention
    PopP = (ord(PopTagId), "pop")  ## `pop` pragma
    PassLP = (ord(PassLTagId), "passL")  ## `passL` pragma adds options to the backend linker
    PassCP = (ord(PassCTagId), "passC")  ## `passC` pragma adds options to the backend compiler
    MethodsP = (ord(MethodsTagId), "methods")  ## `methods` pragma lists vtable methods for a type
    SizeP = (ord(SizeTagId), "size")  ## `size` pragma for setting the byte size of a type
    UncheckedAccessP = (ord(UncheckedAccessTagId), "uncheckedAccess")  ## `uncheckedAccess` marker; only valid inside `{.cast(uncheckedAccess).}:` pragma blocks (allows for obj.guardedField outside of an `of` branch)
    UncheckedAssignP = (ord(UncheckedAssignTagId), "uncheckedAssign")  ## `uncheckedAssign` marker; only valid inside `{.cast(uncheckedAssign).}:` pragma blocks (ignored for Nim compat)
    ProfilerP = (ord(ProfilerTagId), "profiler")  ## `profiler` pragma; accepted for Nim source compatibility, semantically ignored
    StacktraceP = (ord(StacktraceTagId), "stacktrace")  ## `stackTrace` pragma; accepted for Nim source compatibility, semantically ignored
    GcsafeP = (ord(GcsafeTagId), "gcsafe")  ## `gcsafe` pragma; accepted for Nim source compatibility, semantically ignored
    UsedP = (ord(UsedTagId), "used")  ## `used` pragma; accepted for Nim source compatibility, semantically ignored
    CompileP = (ord(CompileTagId), "compile")  ## `compile` pragma (Nim-compatible alias of `build`; the source language is inferred from the file extension, e.g. `.m` → Objective-C)
    BundleP = (ord(BundleTagId), "bundle")  ## `bundle` pragma: a custom linker command override `(builder, tool[, args])`; the `tool` is built on demand by `builder` and replaces the final link step, consuming the project's link manifest
    InstructionP = (ord(InstructionTagId), "instruction")  ## target-pinned instruction annotation; the argument is an opcode NAME from `lib/intrinsics`'s `IntrinsicOp`, spelled as a string literal (`{.instruction: "bsf".}`). A string, not an ident: the name is data resolved by table lookup, it is never subject to scope or overload resolution, and an ident would additionally have to dodge Nim's keywords. The proc is a *declaration* of one machine instruction: calls to it become `(instr …)`, never an ABI call. Its signature spelling is dictated by the row's operand roles and checked at the declaration
    IntrinsicP = (ord(IntrinsicTagId), "intrinsic")  ## portable-intrinsic annotation; like `instruction` (same string-literal argument) but the opcode is target-neutral and may expand to any number of instructions (`Memcpy`, `AtomicFetchAdd`, …). Its signature is unified against the row's shape at the declaration
    RegisterP = (ord(RegisterTagId), "register")  ## pins a parameter, result or local to a named machine register (`{.register: "rdi".}`). In an `{.assembler.}` proc this is an *assertion* the back end verifies; in an ordinary proc it is a hard pin the register allocator honours
    StackP = (ord(StackTagId), "stack")  ## pins a local to a stack slot rather than a register (`{.stack.}`) — the memory counterpart of `(register …)`
    AssemblerP = (ord(AssemblerTagId), "assembler")  ## the `{.assembler.}` **proc pragma** (no children): every construct in the body maps one-to-one to assembler, in source order, with no temporaries invented and no operand materialised. The back end (arkham) owns that checking — see `nativenif/doc/intrinsics.md` §8. Spelled `assembler` rather than `asm` because Nim's parser reads a pragma entry as an expression and so cannot accept a keyword there; it is unrelated to the `(asm X+)` statement
    AlwaysInlineP = (ord(AlwaysInlineTagId), "alwaysInline")  ## the `{.alwaysInline.}` proc pragma: splice this proc at every call site, unconditionally — no size bound, no per-call-site score. Unlike `(inline)`, which is an *emission* annotation the inlining policy deliberately ignores, this one overrides the policy. It is the author asserting what a token count cannot see: typically "my hot path is two instructions and the bulk is a cold tail behind a `(noinline)` callee". Only the recursion guard still applies — that is termination, not heuristics
    NakedP = (ord(NakedTagId), "naked")  ## the `{.naked.}` **proc pragma** (no children): emit NO prologue and NO epilogue — the proc never touches SP, so on entry SP still points straight at the return address the `call` pushed. That is the one thing an ordinary proc cannot observe about its caller, and it is what lets `getStackTrace` seed a stack walk with a frame it did not create. Only legal together with `(assembler)`: without a frame there is nowhere to spill, so every location must already be declared. The back end (arkham) owns the checking
    InterruptP = (ord(InterruptTagId), "interrupt")  ## the `{.interrupt: "SysTick".}` **proc pragma**: this routine is the handler for the named exception or interrupt, and the back end installs its address in the interrupt table. WHICH names exist is a target question — arkham's, exactly as for `(register)` — so sem checks only what is true of every part: a handler is invoked by hardware, which passes no arguments and has nowhere to put a result, so the routine must take no parameters and return nothing. It is also a DCE ROOT: nothing in the program calls it, it is reached only through the table, and without that it is deleted and the device silently never responds. The C and LLVM backends refuse it — they have no interrupt table to install anything into, and `{.exportc.}` is what binds a handler by name against a vendor startup file

proc rawTagIsNimonyPragma*(raw: TagEnum): bool {.inline.} =
  raw in {CastTagId, CursorTagId, EmitTagId, UnionTagId, InlineTagId, NoinlineTagId, ClosureTagId, VarargsTagId, SelectanyTagId, AlignTagId, BitsTagId, NodeclTagId, RaisesTagId, UntypedTagId, MagicTagId, ImportcTagId, ImportcppTagId, DynlibTagId, ExportcTagId, HeaderTagId, ThreadvarTagId, GlobalTagId, DiscardableTagId, NoreturnTagId, BorrowTagId, NoSideEffectTagId, NodestroyTagId, PluginTagId, BycopyTagId, ByrefTagId, NoinitTagId, RequiresTagId, EnsuresTagId, AssumeTagId, AssertTagId, BuildTagId, FeatureTagId, StringTagId, ViewTagId, EstablishesBorrowTagId, IncompleteStructTagId, InjectTagId, GensymTagId, DirtyTagId, ErrorTagId, ReportTagId, TagsTagId, DeprecatedTagId, SideEffectTagId, KeepOverflowFlagTagId, SemanticsTagId, InheritableTagId, BaseTagId, PureTagId, FinalTagId, AcyclicTagId, PragmaTagId, PackedTagId, PassiveTagId, PushTagId, CallConvTagId, PopTagId, PassLTagId, PassCTagId, MethodsTagId, SizeTagId, UncheckedAccessTagId, UncheckedAssignTagId, ProfilerTagId, StacktraceTagId, GcsafeTagId, UsedTagId, CompileTagId, BundleTagId, InstructionTagId, IntrinsicTagId, RegisterTagId, StackTagId, AssemblerTagId, AlwaysInlineTagId, NakedTagId, InterruptTagId}

type
  NimonySym* = enum
    NoSym
    GvarY = (ord(GvarTagId), "gvar")  ## global variable declaration
    TvarY = (ord(TvarTagId), "tvar")  ## thread local variable declaration
    VarY = (ord(VarTagId), "var")  ## variable declaration; type slot may be omitted when inferred from initializer
    ParamY = (ord(ParamTagId), "param")  ## parameter declaration
    ConstY = (ord(ConstTagId), "const")  ## const variable declaration
    ResultY = (ord(ResultTagId), "result")  ## result variable declaration
    GletY = (ord(GletTagId), "glet")  ## global let variable declaration
    TletY = (ord(TletTagId), "tlet")  ## thread local let variable declaration
    LetY = (ord(LetTagId), "let")  ## let variable declaration; type is optional when used in `(unpackflat …)`
    CursorY = (ord(CursorTagId), "cursor")  ## cursor variable declaration
    PatternvarY = (ord(PatternvarTagId), "patternvar")  ## pattern variable declaration
    TypevarY = (ord(TypevarTagId), "typevar")  ## type variable declaration; constraint `.T` is optional
    StaticTypevarY = (ord(StaticTypevarTagId), "staticTypevar")  ## value generic parameter: a generic parameter that is a compile-time *value*; the type slot holds the value's plain element type (e.g. `int` for `N: static[int]`), never a `static` wrapper
    EfldY = (ord(EfldTagId), "efld")  ## enum field declaration; slot 2 carries the export marker *or* the compile-time value (may be `.`)
    FldY = (ord(FldTagId), "fld")  ## field declaration
    GfldY = (ord(GfldTagId), "gfld")  ## guarded field declaration, cannot be accessed outside an `of` branch
    ProcY = (ord(ProcTagId), "proc")  ## proc declaration
    FuncY = (ord(FuncTagId), "func")  ## function declaration
    IteratorY = (ord(IteratorTagId), "iterator")  ## iterator declaration
    ConverterY = (ord(ConverterTagId), "converter")  ## converter declaration
    MethodY = (ord(MethodTagId), "method")  ## method declaration
    MacroY = (ord(MacroTagId), "macro")  ## macro declaration
    TemplateY = (ord(TemplateTagId), "template")  ## template declaration
    TypeY = (ord(TypeTagId), "type")  ## type declaration
    BlockY = (ord(BlockTagId), "block")  ## block declaration
    ModuleY = (ord(ModuleTagId), "module")  ## module declaration
    CchoiceY = (ord(CchoiceTagId), "cchoice")  ## closed choice
    LabY = (ord(LabTagId), "lab")  ## label, target of a `jmp` instruction. Also a **Nimony** statement: `xelim` lowers short-circuit `and`/`or` chains to the flat `(if c (jmp L))` / `(lab L)` form (the two-target condition compiler, see `doc/final_ir.md`), which needs a merge label that is not an enclosing region's end — something `(block)`/`(break)` cannot express without one wrapper per merge

proc rawTagIsNimonySym*(raw: TagEnum): bool {.inline.} =
  raw in {GvarTagId, TvarTagId, VarTagId, ParamTagId, ConstTagId, ResultTagId, GletTagId, TletTagId, LetTagId, CursorTagId, PatternvarTagId, TypevarTagId, StaticTypevarTagId, EfldTagId, FldTagId, GfldTagId, ProcTagId, FuncTagId, IteratorTagId, ConverterTagId, MethodTagId, MacroTagId, TemplateTagId, TypeTagId, BlockTagId, ModuleTagId, CchoiceTagId, LabTagId}

type
  HookKind* = enum
    NoHook
    DestroyH = (ord(DestroyTagId), "destroy")
    DupH = (ord(DupTagId), "dup")
    CopyH = (ord(CopyTagId), "copy")
    WasmovedH = (ord(WasmovedTagId), "wasmoved")
    SinkhH = (ord(SinkhTagId), "sinkh")
    TraceH = (ord(TraceTagId), "trace")

proc rawTagIsHookKind*(raw: TagEnum): bool {.inline.} =
  raw >= DestroyTagId and raw <= TraceTagId

type
  ControlFlowKind* = enum
    NoControlFlow
    IteF = (ord(IteTagId), "ite")  ## if-then-else followed by `join` information followed by an optional label
    GraphF = (ord(GraphTagId), "graph")  ## disjoint subgraph annotation
    ForbindF = (ord(ForbindTagId), "forbind")  ## bindings for a `for` loop but the loop itself is mapped to gotos
    KillF = (ord(KillTagId), "kill")  ## some.var is about to disappear (scope exit)

proc rawTagIsControlFlowKind*(raw: TagEnum): bool {.inline.} =
  raw in {IteTagId, GraphTagId, ForbindTagId, KillTagId}

