# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

const
  TagData* = [
    ("err", 1),
    ("suf", 2),
    ("at", 3),
    ("deref", 4),
    ("dot", 5),
    ("pat", 6),
    ("par", 7),
    ("addr", 8),
    ("nil", 9),
    ("inf", 10),
    ("neginf", 11),
    ("nan", 12),
    ("false", 13),
    ("true", 14),
    ("and", 15),
    ("or", 16),
    ("not", 17),
    ("neg", 18),
    ("sizeof", 19),
    ("alignof", 20),
    ("offsetof", 21),
    ("oconstr", 22),
    ("aconstr", 23),
    ("bracket", 24),
    ("curly", 25),
    ("kv", 26),
    ("add", 27),
    ("sub", 28),
    ("mul", 29),
    ("div", 30),
    ("mod", 31),
    ("shr", 32),
    ("shl", 33),
    ("bitand", 34),
    ("bitor", 35),
    ("bitxor", 36),
    ("bitnot", 37),
    ("eq", 38),
    ("neq", 39),
    ("le", 40),
    ("lt", 41),
    ("cast", 42),
    ("conv", 43),
    ("call", 44),
    ("cmd", 45),
    ("range", 46),
    ("ranges", 47),
    ("gvar", 48),
    ("tvar", 49),
    ("var", 50),
    ("param", 51),
    ("const", 52),
    ("result", 53),
    ("let", 54),
    ("cursor", 55),
    ("typevar", 56),
    ("efld", 57),
    ("fld", 58),
    ("proc", 59),
    ("func", 60),
    ("iterator", 61),
    ("converter", 62),
    ("method", 63),
    ("macro", 64),
    ("template", 65),
    ("type", 66),
    ("block", 67),
    ("module", 68),
    ("cchoice", 69),
    ("ochoice", 70),
    ("emit", 71),
    ("asgn", 72),
    ("scope", 73),
    ("if", 74),
    ("when", 75),
    ("elif", 76),
    ("else", 77),
    ("typevars", 78),
    ("break", 79),
    ("continue", 80),
    ("for", 81),
    ("while", 82),
    ("case", 83),
    ("of", 84),
    ("lab", 85),
    ("jmp", 86),
    ("ret", 87),
    ("yld", 88),
    ("stmts", 89),
    ("params", 90),
    ("union", 91),
    ("object", 92),
    ("enum", 93),
    ("proctype", 94),
    ("atomic", 95),
    ("ro", 96),
    ("restrict", 97),
    ("i", 98),
    ("u", 99),
    ("f", 100),
    ("c", 101),
    ("bool", 102),
    ("void", 103),
    ("ptr", 104),
    ("array", 105),
    ("flexarray", 106),
    ("aptr", 107),
    ("cdecl", 108),
    ("stdcall", 109),
    ("safecall", 110),
    ("syscall", 111),
    ("fastcall", 112),
    ("thiscall", 113),
    ("noconv", 114),
    ("member", 115),
    ("inline", 116),
    ("noinline", 117),
    ("attr", 118),
    ("varargs", 119),
    ("was", 120),
    ("selectany", 121),
    ("pragmas", 122),
    ("align", 123),
    ("bits", 124),
    ("vector", 125),
    ("imp", 126),
    ("nodecl", 127),
    ("incl", 128),
    ("excl", 129),
    ("include", 130),
    ("import", 131),
    ("from", 132),
    ("importexcept", 133),
    ("export", 134),
    ("comment", 135),
    ("discard", 136),
    ("try", 137),
    ("raise", 138),
    ("onerr", 139),
    ("raises", 140),
    ("errs", 141),
    ("static", 142),
    ("ite", 143),
    ("graph", 144),
    ("forbind", 145),
    ("kill", 146),
    ("unpackflat", 147),
    ("unpacktup", 148),
    ("except", 149),
    ("fin", 150),
    ("refobj", 151),
    ("ptrobj", 152),
    ("tuple", 153),
    ("onum", 154),
    ("ref", 155),
    ("mut", 156),
    ("out", 157),
    ("lent", 158),
    ("sink", 159),
    ("nilt", 160),
    ("concept", 161),
    ("distinct", 162),
    ("itertype", 163),
    ("rangetype", 164),
    ("uarray", 165),
    ("openarray", 166),
    ("sett", 167),
    ("auto", 168),
    ("symkind", 169),
    ("typekind", 170),
    ("typedesc", 171),
    ("untyped", 172),
    ("typed", 173),
    ("cstring", 174),
    ("pointer", 175),
    ("ordinal", 176),
    ("magic", 177),
    ("importc", 178),
    ("importcpp", 179),
    ("exportc", 180),
    ("header", 181),
    ("threadvar", 182),
    ("global", 183),
    ("discardable", 184),
    ("noreturn", 185),
    ("borrow", 186),
    ("noSideEffect", 187),
    ("nodestroy", 188),
    ("plugin", 189),
    ("bycopy", 190),
    ("byref", 191),
    ("noinit", 192),
    ("requires", 193),
    ("ensures", 194),
    ("build", 195),
    ("string", 196),
    ("quoted", 197),
    ("hderef", 198),
    ("ddot", 199),
    ("haddr", 200),
    ("newoconstr", 201),
    ("tupleconstr", 202),
    ("set", 203),
    ("ashr", 204),
    ("oconv", 205),
    ("hconv", 206),
    ("dconv", 207),
    ("callstrlit", 208),
    ("infix", 209),
    ("prefix", 210),
    ("hcall", 211),
    ("compiles", 212),
    ("declared", 213),
    ("defined", 214),
    ("high", 215),
    ("low", 216),
    ("typeof", 217),
    ("unpack", 218),
    ("enumtostr", 219),
    ("ismainmodule", 220),
    ("defaultobj", 221),
    ("defaulttup", 222),
    ("expr", 223),
    ("arrat", 224),
    ("tupat", 225),
    ("plusset", 226),
    ("minusset", 227),
    ("mulset", 228),
    ("xorset", 229),
    ("eqset", 230),
    ("leset", 231),
    ("ltset", 232),
    ("inset", 233),
    ("card", 234),
    ("emove", 235),
    ("destroy", 236),
    ("dup", 237),
    ("copy", 238),
    ("wasmoved", 239),
    ("sinkh", 240),
    ("trace", 241)
  ]
const
  ErrTagId* = 1
  SufTagId* = 2
  AtTagId* = 3
  DerefTagId* = 4
  DotTagId* = 5
  PatTagId* = 6
  ParTagId* = 7
  AddrTagId* = 8
  NilTagId* = 9
  InfTagId* = 10
  NeginfTagId* = 11
  NanTagId* = 12
  FalseTagId* = 13
  TrueTagId* = 14
  AndTagId* = 15
  OrTagId* = 16
  NotTagId* = 17
  NegTagId* = 18
  SizeofTagId* = 19
  AlignofTagId* = 20
  OffsetofTagId* = 21
  OconstrTagId* = 22
  AconstrTagId* = 23
  BracketTagId* = 24
  CurlyTagId* = 25
  KvTagId* = 26
  AddTagId* = 27
  SubTagId* = 28
  MulTagId* = 29
  DivTagId* = 30
  ModTagId* = 31
  ShrTagId* = 32
  ShlTagId* = 33
  BitandTagId* = 34
  BitorTagId* = 35
  BitxorTagId* = 36
  BitnotTagId* = 37
  EqTagId* = 38
  NeqTagId* = 39
  LeTagId* = 40
  LtTagId* = 41
  CastTagId* = 42
  ConvTagId* = 43
  CallTagId* = 44
  CmdTagId* = 45
  RangeTagId* = 46
  RangesTagId* = 47
  GvarTagId* = 48
  TvarTagId* = 49
  VarTagId* = 50
  ParamTagId* = 51
  ConstTagId* = 52
  ResultTagId* = 53
  LetTagId* = 54
  CursorTagId* = 55
  TypevarTagId* = 56
  EfldTagId* = 57
  FldTagId* = 58
  ProcTagId* = 59
  FuncTagId* = 60
  IteratorTagId* = 61
  ConverterTagId* = 62
  MethodTagId* = 63
  MacroTagId* = 64
  TemplateTagId* = 65
  TypeTagId* = 66
  BlockTagId* = 67
  ModuleTagId* = 68
  CchoiceTagId* = 69
  OchoiceTagId* = 70
  EmitTagId* = 71
  AsgnTagId* = 72
  ScopeTagId* = 73
  IfTagId* = 74
  WhenTagId* = 75
  ElifTagId* = 76
  ElseTagId* = 77
  TypevarsTagId* = 78
  BreakTagId* = 79
  ContinueTagId* = 80
  ForTagId* = 81
  WhileTagId* = 82
  CaseTagId* = 83
  OfTagId* = 84
  LabTagId* = 85
  JmpTagId* = 86
  RetTagId* = 87
  YldTagId* = 88
  StmtsTagId* = 89
  ParamsTagId* = 90
  UnionTagId* = 91
  ObjectTagId* = 92
  EnumTagId* = 93
  ProctypeTagId* = 94
  AtomicTagId* = 95
  RoTagId* = 96
  RestrictTagId* = 97
  ITagId* = 98
  UTagId* = 99
  FTagId* = 100
  CTagId* = 101
  BoolTagId* = 102
  VoidTagId* = 103
  PtrTagId* = 104
  ArrayTagId* = 105
  FlexarrayTagId* = 106
  AptrTagId* = 107
  CdeclTagId* = 108
  StdcallTagId* = 109
  SafecallTagId* = 110
  SyscallTagId* = 111
  FastcallTagId* = 112
  ThiscallTagId* = 113
  NoconvTagId* = 114
  MemberTagId* = 115
  InlineTagId* = 116
  NoinlineTagId* = 117
  AttrTagId* = 118
  VarargsTagId* = 119
  WasTagId* = 120
  SelectanyTagId* = 121
  PragmasTagId* = 122
  AlignTagId* = 123
  BitsTagId* = 124
  VectorTagId* = 125
  ImpTagId* = 126
  NodeclTagId* = 127
  InclTagId* = 128
  ExclTagId* = 129
  IncludeTagId* = 130
  ImportTagId* = 131
  FromTagId* = 132
  ImportexceptTagId* = 133
  ExportTagId* = 134
  CommentTagId* = 135
  DiscardTagId* = 136
  TryTagId* = 137
  RaiseTagId* = 138
  OnerrTagId* = 139
  RaisesTagId* = 140
  ErrsTagId* = 141
  StaticTagId* = 142
  IteTagId* = 143
  GraphTagId* = 144
  ForbindTagId* = 145
  KillTagId* = 146
  UnpackflatTagId* = 147
  UnpacktupTagId* = 148
  ExceptTagId* = 149
  FinTagId* = 150
  RefobjTagId* = 151
  PtrobjTagId* = 152
  TupleTagId* = 153
  OnumTagId* = 154
  RefTagId* = 155
  MutTagId* = 156
  OutTagId* = 157
  LentTagId* = 158
  SinkTagId* = 159
  NiltTagId* = 160
  ConceptTagId* = 161
  DistinctTagId* = 162
  ItertypeTagId* = 163
  RangetypeTagId* = 164
  UarrayTagId* = 165
  OpenarrayTagId* = 166
  SettTagId* = 167
  AutoTagId* = 168
  SymkindTagId* = 169
  TypekindTagId* = 170
  TypedescTagId* = 171
  UntypedTagId* = 172
  TypedTagId* = 173
  CstringTagId* = 174
  PointerTagId* = 175
  OrdinalTagId* = 176
  MagicTagId* = 177
  ImportcTagId* = 178
  ImportcppTagId* = 179
  ExportcTagId* = 180
  HeaderTagId* = 181
  ThreadvarTagId* = 182
  GlobalTagId* = 183
  DiscardableTagId* = 184
  NoreturnTagId* = 185
  BorrowTagId* = 186
  NoSideEffectTagId* = 187
  NodestroyTagId* = 188
  PluginTagId* = 189
  BycopyTagId* = 190
  ByrefTagId* = 191
  NoinitTagId* = 192
  RequiresTagId* = 193
  EnsuresTagId* = 194
  BuildTagId* = 195
  StringTagId* = 196
  QuotedTagId* = 197
  HderefTagId* = 198
  DdotTagId* = 199
  HaddrTagId* = 200
  NewoconstrTagId* = 201
  TupleconstrTagId* = 202
  SetTagId* = 203
  AshrTagId* = 204
  OconvTagId* = 205
  HconvTagId* = 206
  DconvTagId* = 207
  CallstrlitTagId* = 208
  InfixTagId* = 209
  PrefixTagId* = 210
  HcallTagId* = 211
  CompilesTagId* = 212
  DeclaredTagId* = 213
  DefinedTagId* = 214
  HighTagId* = 215
  LowTagId* = 216
  TypeofTagId* = 217
  UnpackTagId* = 218
  EnumtostrTagId* = 219
  IsmainmoduleTagId* = 220
  DefaultobjTagId* = 221
  DefaulttupTagId* = 222
  ExprTagId* = 223
  ArratTagId* = 224
  TupatTagId* = 225
  PlussetTagId* = 226
  MinussetTagId* = 227
  MulsetTagId* = 228
  XorsetTagId* = 229
  EqsetTagId* = 230
  LesetTagId* = 231
  LtsetTagId* = 232
  InsetTagId* = 233
  CardTagId* = 234
  EmoveTagId* = 235
  DestroyTagId* = 236
  DupTagId* = 237
  CopyTagId* = 238
  WasmovedTagId* = 239
  SinkhTagId* = 240
  TraceTagId* = 241
