# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    ErrTagId
    SufTagId
    AtTagId
    DerefTagId
    DotTagId
    PatTagId
    ParTagId
    AddrTagId
    NilTagId
    NotnilTagId
    UncheckedTagId
    InfTagId
    NeginfTagId
    NanTagId
    FalseTagId
    TrueTagId
    AndTagId
    OrTagId
    XorTagId
    NotTagId
    NegTagId
    SizeofTagId
    AlignofTagId
    OffsetofTagId
    OconstrTagId
    AconstrTagId
    BracketTagId
    CurlyTagId
    CurlyatTagId
    KvTagId
    VvTagId
    OvfTagId
    AddTagId
    SubTagId
    MulTagId
    DivTagId
    ModTagId
    ShrTagId
    ShlTagId
    BitandTagId
    BitorTagId
    BitxorTagId
    BitnotTagId
    EqTagId
    NeqTagId
    LeTagId
    LtTagId
    CastTagId
    ConvTagId
    CallTagId
    CmdTagId
    RangeTagId
    RangesTagId
    GvarTagId
    TvarTagId
    VarTagId
    ParamTagId
    ConstTagId
    ResultTagId
    GletTagId
    TletTagId
    LetTagId
    CursorTagId
    PatternvarTagId
    TypevarTagId
    StaticTypevarTagId
    EfldTagId
    FldTagId
    GfldTagId
    ProcTagId
    FuncTagId
    IteratorTagId
    ConverterTagId
    MethodTagId
    MacroTagId
    TemplateTagId
    TypeTagId
    BlockTagId
    ModuleTagId
    CchoiceTagId
    OchoiceTagId
    EmitTagId
    AsgnTagId
    StoreTagId
    KeepovfTagId
    ScopeTagId
    IfTagId
    WhenTagId
    ElifTagId
    ElseTagId
    TypevarsTagId
    BreakTagId
    ContinueTagId
    ForTagId
    WhileTagId
    CoroforTagId
    CaseTagId
    OfTagId
    LabTagId
    JmpTagId
    RetTagId
    YldTagId
    StmtsTagId
    ParamsTagId
    UnionTagId
    ObjectTagId
    EnumTagId
    ProctypeTagId
    AtomicTagId
    RoTagId
    RestrictTagId
    CpprefTagId
    ITagId
    UTagId
    FTagId
    CTagId
    BoolTagId
    VoidTagId
    PtrTagId
    ArrayTagId
    FlexarrayTagId
    AptrTagId
    CdeclTagId
    StdcallTagId
    SafecallTagId
    SyscallTagId
    FastcallTagId
    ThiscallTagId
    NoconvTagId
    MemberTagId
    NimcallTagId
    InlineTagId
    NoinlineTagId
    ClosureTagId
    AttrTagId
    SmryTagId
    VarargsTagId
    WasTagId
    SelectanyTagId
    PragmasTagId
    PragmaxTagId
    AlignTagId
    BitsTagId
    VectorTagId
    NodeclTagId
    InclTagId
    ExclTagId
    IncludeTagId
    ImportTagId
    ImportasTagId
    FromimportTagId
    ImportexceptTagId
    ExportTagId
    FromexportTagId
    ExportexceptTagId
    CommentTagId
    DiscardTagId
    TryTagId
    RaiseTagId
    OnerrTagId
    RaisesTagId
    ErrsTagId
    StaticTagId
    IteTagId
    ItecTagId
    LoopTagId
    VTagId
    EtupatTagId
    UnknownTagId
    JtrueTagId
    MflagTagId
    VflagTagId
    EitherTagId
    JoinTagId
    GraphTagId
    ForbindTagId
    KillTagId
    UnpackflatTagId
    UnpacktupTagId
    CallargsTagId
    ForcallTagId
    UnpackdeclTagId
    ExceptTagId
    FinTagId
    TupleTagId
    ClosureTupleTagId
    OnumTagId
    AnumTagId
    RefTagId
    MutTagId
    OutTagId
    LentTagId
    SinkTagId
    NiltTagId
    ConceptTagId
    DistinctTagId
    ItertypeTagId
    RangetypeTagId
    UarrayTagId
    SetTagId
    AutoTagId
    SymkindTagId
    TypekindTagId
    TypedescTagId
    UntypedTagId
    TypedTagId
    CstringTagId
    PointerTagId
    OrdinalTagId
    MagicTagId
    ImportcTagId
    ImportcppTagId
    DynlibTagId
    ExportcTagId
    HeaderTagId
    ThreadvarTagId
    GlobalTagId
    DiscardableTagId
    NoreturnTagId
    BorrowTagId
    NoSideEffectTagId
    NodestroyTagId
    PluginTagId
    BycopyTagId
    ByrefTagId
    NoinitTagId
    RequiresTagId
    EnsuresTagId
    AssumeTagId
    AssertTagId
    BuildTagId
    FeatureTagId
    StringTagId
    ViewTagId
    EstablishesBorrowTagId
    IncompleteStructTagId
    QuotedTagId
    HderefTagId
    DdotTagId
    HaddrTagId
    NewrefTagId
    NewobjTagId
    TupTagId
    TupconstrTagId
    SetconstrTagId
    TabconstrTagId
    AshrTagId
    BaseobjTagId
    HconvTagId
    DconvTagId
    CallstrlitTagId
    InfixTagId
    PrefixTagId
    HcallTagId
    CompilesTagId
    DeclaredTagId
    DefinedTagId
    AstToStrTagId
    BindSymTagId
    BindSymNameTagId
    InstanceofTagId
    ProccallTagId
    HighTagId
    LowTagId
    TypeofTagId
    UnpackTagId
    FieldsTagId
    FieldpairsTagId
    EnumtostrTagId
    IsmainmoduleTagId
    InstantiationinfoTagId
    DefaultobjTagId
    DefaulttupTagId
    DefaultdistinctTagId
    DelayTagId
    Delay0TagId
    SuspendTagId
    ExprTagId
    DoTagId
    ArratTagId
    TupatTagId
    PlussetTagId
    MinussetTagId
    MulsetTagId
    XorsetTagId
    EqsetTagId
    LesetTagId
    LtsetTagId
    InsetTagId
    CardTagId
    EmoveTagId
    DestroyTagId
    DupTagId
    CopyTagId
    WasmovedTagId
    SinkhTagId
    TraceTagId
    ErrvTagId
    StaticstmtTagId
    BindTagId
    MixinTagId
    UsingTagId
    AsmTagId
    DeferTagId
    IndexTagId
    InjectTagId
    GensymTagId
    DirtyTagId
    ErrorTagId
    ReportTagId
    TagsTagId
    DeprecatedTagId
    SideEffectTagId
    KeepOverflowFlagTagId
    SemanticsTagId
    InheritableTagId
    BaseTagId
    PureTagId
    FinalTagId
    AcyclicTagId
    PragmaTagId
    InternalTypeNameTagId
    InternalFieldPairsTagId
    FailedTagId
    IsTagId
    EnvpTagId
    PackedTagId
    PassiveTagId
    PushTagId
    CallConvTagId
    PopTagId
    PassLTagId
    PassCTagId
    MethodsTagId
    SizeTagId
    UncheckedAccessTagId
    UncheckedAssignTagId
    ProfilerTagId
    StacktraceTagId
    GcsafeTagId
    UsedTagId
    CompileTagId
    BundleTagId
    ToClosureTagId
    InstructionTagId
    IntrinsicTagId
    InstrTagId
    RegisterTagId
    StackTagId
    AssemblerTagId
    DeferexpansionTagId
    NeedtypesTagId
    AlwaysInlineTagId
    NakedTagId
    InterruptTagId
    ConstrefTagId
    DependencyTagId
    PluginCallTagId
const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("err", 1),
    ("suf", 2),
    ("at", 3),
    ("deref", 4),
    ("dot", 5),
    ("pat", 6),
    ("par", 7),
    ("addr", 8),
    ("nil", 9),
    ("notnil", 10),
    ("unchecked", 11),
    ("inf", 12),
    ("neginf", 13),
    ("nan", 14),
    ("false", 15),
    ("true", 16),
    ("and", 17),
    ("or", 18),
    ("xor", 19),
    ("not", 20),
    ("neg", 21),
    ("sizeof", 22),
    ("alignof", 23),
    ("offsetof", 24),
    ("oconstr", 25),
    ("aconstr", 26),
    ("bracket", 27),
    ("curly", 28),
    ("curlyat", 29),
    ("kv", 30),
    ("vv", 31),
    ("ovf", 32),
    ("add", 33),
    ("sub", 34),
    ("mul", 35),
    ("div", 36),
    ("mod", 37),
    ("shr", 38),
    ("shl", 39),
    ("bitand", 40),
    ("bitor", 41),
    ("bitxor", 42),
    ("bitnot", 43),
    ("eq", 44),
    ("neq", 45),
    ("le", 46),
    ("lt", 47),
    ("cast", 48),
    ("conv", 49),
    ("call", 50),
    ("cmd", 51),
    ("range", 52),
    ("ranges", 53),
    ("gvar", 54),
    ("tvar", 55),
    ("var", 56),
    ("param", 57),
    ("const", 58),
    ("result", 59),
    ("glet", 60),
    ("tlet", 61),
    ("let", 62),
    ("cursor", 63),
    ("patternvar", 64),
    ("typevar", 65),
    ("staticTypevar", 66),
    ("efld", 67),
    ("fld", 68),
    ("gfld", 69),
    ("proc", 70),
    ("func", 71),
    ("iterator", 72),
    ("converter", 73),
    ("method", 74),
    ("macro", 75),
    ("template", 76),
    ("type", 77),
    ("block", 78),
    ("module", 79),
    ("cchoice", 80),
    ("ochoice", 81),
    ("emit", 82),
    ("asgn", 83),
    ("store", 84),
    ("keepovf", 85),
    ("scope", 86),
    ("if", 87),
    ("when", 88),
    ("elif", 89),
    ("else", 90),
    ("typevars", 91),
    ("break", 92),
    ("continue", 93),
    ("for", 94),
    ("while", 95),
    ("corofor", 96),
    ("case", 97),
    ("of", 98),
    ("lab", 99),
    ("jmp", 100),
    ("ret", 101),
    ("yld", 102),
    ("stmts", 103),
    ("params", 104),
    ("union", 105),
    ("object", 106),
    ("enum", 107),
    ("proctype", 108),
    ("atomic", 109),
    ("ro", 110),
    ("restrict", 111),
    ("cppref", 112),
    ("i", 113),
    ("u", 114),
    ("f", 115),
    ("c", 116),
    ("bool", 117),
    ("void", 118),
    ("ptr", 119),
    ("array", 120),
    ("flexarray", 121),
    ("aptr", 122),
    ("cdecl", 123),
    ("stdcall", 124),
    ("safecall", 125),
    ("syscall", 126),
    ("fastcall", 127),
    ("thiscall", 128),
    ("noconv", 129),
    ("member", 130),
    ("nimcall", 131),
    ("inline", 132),
    ("noinline", 133),
    ("closure", 134),
    ("attr", 135),
    ("smry", 136),
    ("varargs", 137),
    ("was", 138),
    ("selectany", 139),
    ("pragmas", 140),
    ("pragmax", 141),
    ("align", 142),
    ("bits", 143),
    ("vector", 144),
    ("nodecl", 145),
    ("incl", 146),
    ("excl", 147),
    ("include", 148),
    ("import", 149),
    ("importas", 150),
    ("fromimport", 151),
    ("importexcept", 152),
    ("export", 153),
    ("fromexport", 154),
    ("exportexcept", 155),
    ("comment", 156),
    ("discard", 157),
    ("try", 158),
    ("raise", 159),
    ("onerr", 160),
    ("raises", 161),
    ("errs", 162),
    ("static", 163),
    ("ite", 164),
    ("itec", 165),
    ("loop", 166),
    ("v", 167),
    ("etupat", 168),
    ("unknown", 169),
    ("jtrue", 170),
    ("mflag", 171),
    ("vflag", 172),
    ("either", 173),
    ("join", 174),
    ("graph", 175),
    ("forbind", 176),
    ("kill", 177),
    ("unpackflat", 178),
    ("unpacktup", 179),
    ("callargs", 180),
    ("forcall", 181),
    ("unpackdecl", 182),
    ("except", 183),
    ("fin", 184),
    ("tuple", 185),
    ("closureTuple", 186),
    ("onum", 187),
    ("anum", 188),
    ("ref", 189),
    ("mut", 190),
    ("out", 191),
    ("lent", 192),
    ("sink", 193),
    ("nilt", 194),
    ("concept", 195),
    ("distinct", 196),
    ("itertype", 197),
    ("rangetype", 198),
    ("uarray", 199),
    ("set", 200),
    ("auto", 201),
    ("symkind", 202),
    ("typekind", 203),
    ("typedesc", 204),
    ("untyped", 205),
    ("typed", 206),
    ("cstring", 207),
    ("pointer", 208),
    ("ordinal", 209),
    ("magic", 210),
    ("importc", 211),
    ("importcpp", 212),
    ("dynlib", 213),
    ("exportc", 214),
    ("header", 215),
    ("threadvar", 216),
    ("global", 217),
    ("discardable", 218),
    ("noreturn", 219),
    ("borrow", 220),
    ("noSideEffect", 221),
    ("nodestroy", 222),
    ("plugin", 223),
    ("bycopy", 224),
    ("byref", 225),
    ("noinit", 226),
    ("requires", 227),
    ("ensures", 228),
    ("assume", 229),
    ("assert", 230),
    ("build", 231),
    ("feature", 232),
    ("string", 233),
    ("view", 234),
    ("establishesBorrow", 235),
    ("incompleteStruct", 236),
    ("quoted", 237),
    ("hderef", 238),
    ("ddot", 239),
    ("haddr", 240),
    ("newref", 241),
    ("newobj", 242),
    ("tup", 243),
    ("tupconstr", 244),
    ("setconstr", 245),
    ("tabconstr", 246),
    ("ashr", 247),
    ("baseobj", 248),
    ("hconv", 249),
    ("dconv", 250),
    ("callstrlit", 251),
    ("infix", 252),
    ("prefix", 253),
    ("hcall", 254),
    ("compiles", 255),
    ("declared", 256),
    ("defined", 257),
    ("astToStr", 258),
    ("bindSym", 259),
    ("bindSymName", 260),
    ("instanceof", 261),
    ("proccall", 262),
    ("high", 263),
    ("low", 264),
    ("typeof", 265),
    ("unpack", 266),
    ("fields", 267),
    ("fieldpairs", 268),
    ("enumtostr", 269),
    ("ismainmodule", 270),
    ("instantiationinfo", 271),
    ("defaultobj", 272),
    ("defaulttup", 273),
    ("defaultdistinct", 274),
    ("delay", 275),
    ("delay0", 276),
    ("suspend", 277),
    ("expr", 278),
    ("do", 279),
    ("arrat", 280),
    ("tupat", 281),
    ("plusset", 282),
    ("minusset", 283),
    ("mulset", 284),
    ("xorset", 285),
    ("eqset", 286),
    ("leset", 287),
    ("ltset", 288),
    ("inset", 289),
    ("card", 290),
    ("emove", 291),
    ("destroy", 292),
    ("dup", 293),
    ("copy", 294),
    ("wasmoved", 295),
    ("sinkh", 296),
    ("trace", 297),
    ("errv", 298),
    ("staticstmt", 299),
    ("bind", 300),
    ("mixin", 301),
    ("using", 302),
    ("asm", 303),
    ("defer", 304),
    ("index", 305),
    ("inject", 306),
    ("gensym", 307),
    ("dirty", 308),
    ("error", 309),
    ("report", 310),
    ("tags", 311),
    ("deprecated", 312),
    ("sideEffect", 313),
    ("keepOverflowFlag", 314),
    ("semantics", 315),
    ("inheritable", 316),
    ("base", 317),
    ("pure", 318),
    ("final", 319),
    ("acyclic", 320),
    ("pragma", 321),
    ("internalTypeName", 322),
    ("internalFieldPairs", 323),
    ("failed", 324),
    ("is", 325),
    ("envp", 326),
    ("packed", 327),
    ("passive", 328),
    ("push", 329),
    ("callConv", 330),
    ("pop", 331),
    ("passL", 332),
    ("passC", 333),
    ("methods", 334),
    ("size", 335),
    ("uncheckedAccess", 336),
    ("uncheckedAssign", 337),
    ("profiler", 338),
    ("stacktrace", 339),
    ("gcsafe", 340),
    ("used", 341),
    ("compile", 342),
    ("bundle", 343),
    ("toClosure", 344),
    ("instruction", 345),
    ("intrinsic", 346),
    ("instr", 347),
    ("register", 348),
    ("stack", 349),
    ("assembler", 350),
    ("deferexpansion", 351),
    ("needtypes", 352),
    ("alwaysInline", 353),
    ("naked", 354),
    ("interrupt", 355),
    ("constref", 356),
    ("dependency", 357),
    ("pluginCall", 358)
  ]
