# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

const
  TagData* = [
    ("err", 1),
    ("suf", 2),
    ("at", 3),
    ("deref", 4),
    ("dot", 5),
    ("pat", 6),
    ("par", 7),
    ("addr", 8),
    ("nil", 9),
    ("inf", 10),
    ("neginf", 11),
    ("nan", 12),
    ("false", 13),
    ("true", 14),
    ("and", 15),
    ("or", 16),
    ("not", 17),
    ("neg", 18),
    ("sizeof", 19),
    ("alignof", 20),
    ("offsetof", 21),
    ("oconstr", 22),
    ("aconstr", 23),
    ("kv", 24),
    ("add", 25),
    ("sub", 26),
    ("mul", 27),
    ("div", 28),
    ("mod", 29),
    ("shr", 30),
    ("shl", 31),
    ("bitand", 32),
    ("bitor", 33),
    ("bitxor", 34),
    ("bitnot", 35),
    ("eq", 36),
    ("neq", 37),
    ("le", 38),
    ("lt", 39),
    ("cast", 40),
    ("conv", 41),
    ("call", 42),
    ("cmd", 43),
    ("range", 44),
    ("ranges", 45),
    ("gvar", 46),
    ("tvar", 47),
    ("var", 48),
    ("param", 49),
    ("const", 50),
    ("result", 51),
    ("let", 52),
    ("cursor", 53),
    ("typevar", 54),
    ("efld", 55),
    ("fld", 56),
    ("proc", 57),
    ("func", 58),
    ("iterator", 59),
    ("converter", 60),
    ("method", 61),
    ("macro", 62),
    ("template", 63),
    ("type", 64),
    ("block", 65),
    ("module", 66),
    ("cchoice", 67),
    ("ochoice", 68),
    ("emit", 69),
    ("asgn", 70),
    ("scope", 71),
    ("if", 72),
    ("when", 73),
    ("elif", 74),
    ("else", 75),
    ("typevars", 76),
    ("break", 77),
    ("continue", 78),
    ("for", 79),
    ("while", 80),
    ("case", 81),
    ("of", 82),
    ("lab", 83),
    ("jmp", 84),
    ("ret", 85),
    ("yld", 86),
    ("stmts", 87),
    ("params", 88),
    ("union", 89),
    ("object", 90),
    ("enum", 91),
    ("proctype", 92),
    ("atomic", 93),
    ("ro", 94),
    ("restrict", 95),
    ("i", 96),
    ("u", 97),
    ("f", 98),
    ("c", 99),
    ("bool", 100),
    ("void", 101),
    ("ptr", 102),
    ("array", 103),
    ("flexarray", 104),
    ("aptr", 105),
    ("cdecl", 106),
    ("stdcall", 107),
    ("safecall", 108),
    ("syscall", 109),
    ("fastcall", 110),
    ("thiscall", 111),
    ("noconv", 112),
    ("member", 113),
    ("inline", 114),
    ("noinline", 115),
    ("attr", 116),
    ("varargs", 117),
    ("was", 118),
    ("selectany", 119),
    ("pragmas", 120),
    ("align", 121),
    ("bits", 122),
    ("vector", 123),
    ("imp", 124),
    ("nodecl", 125),
    ("incl", 126),
    ("excl", 127),
    ("include", 128),
    ("import", 129),
    ("from", 130),
    ("importexcept", 131),
    ("export", 132),
    ("comment", 133),
    ("discard", 134),
    ("try", 135),
    ("raise", 136),
    ("onerr", 137),
    ("raises", 138),
    ("errs", 139),
    ("static", 140),
    ("ite", 141),
    ("graph", 142),
    ("forbind", 143),
    ("kill", 144),
    ("unpackflat", 145),
    ("unpacktup", 146),
    ("except", 147),
    ("fin", 148),
    ("refobj", 149),
    ("ptrobj", 150),
    ("tuple", 151),
    ("onum", 152),
    ("ref", 153),
    ("mut", 154),
    ("out", 155),
    ("lent", 156),
    ("sink", 157),
    ("nilt", 158),
    ("concept", 159),
    ("distinct", 160),
    ("itertype", 161),
    ("rangetype", 162),
    ("uarray", 163),
    ("openarray", 164),
    ("sett", 165),
    ("auto", 166),
    ("symkind", 167),
    ("typekind", 168),
    ("typedesc", 169),
    ("untyped", 170),
    ("typed", 171),
    ("cstring", 172),
    ("pointer", 173),
    ("ordinal", 174),
    ("magic", 175),
    ("importc", 176),
    ("importcpp", 177),
    ("exportc", 178),
    ("header", 179),
    ("threadvar", 180),
    ("global", 181),
    ("discardable", 182),
    ("noreturn", 183),
    ("borrow", 184),
    ("noSideEffect", 185),
    ("nodestroy", 186),
    ("plugin", 187),
    ("bycopy", 188),
    ("byref", 189),
    ("noinit", 190),
    ("requires", 191),
    ("ensures", 192),
    ("build", 193),
    ("string", 194),
    ("quoted", 195),
    ("hderef", 196),
    ("ddot", 197),
    ("haddr", 198),
    ("newoconstr", 199),
    ("tupleconstr", 200),
    ("set", 201),
    ("ashr", 202),
    ("oconv", 203),
    ("hconv", 204),
    ("dconv", 205),
    ("callstrlit", 206),
    ("infix", 207),
    ("prefix", 208),
    ("hcall", 209),
    ("compiles", 210),
    ("declared", 211),
    ("defined", 212),
    ("high", 213),
    ("low", 214),
    ("typeof", 215),
    ("unpack", 216),
    ("enumtostr", 217),
    ("ismainmodule", 218),
    ("defaultobj", 219),
    ("defaulttup", 220),
    ("expr", 221),
    ("arrat", 222),
    ("tupat", 223),
    ("plusset", 224),
    ("minusset", 225),
    ("mulset", 226),
    ("xorset", 227),
    ("eqset", 228),
    ("leset", 229),
    ("ltset", 230),
    ("inset", 231),
    ("card", 232),
    ("emove", 233),
    ("destroy", 234),
    ("dup", 235),
    ("copy", 236),
    ("wasmoved", 237),
    ("sinkh", 238),
    ("trace", 239)
  ]
const
  ErrTagId* = 1
  SufTagId* = 2
  AtTagId* = 3
  DerefTagId* = 4
  DotTagId* = 5
  PatTagId* = 6
  ParTagId* = 7
  AddrTagId* = 8
  NilTagId* = 9
  InfTagId* = 10
  NeginfTagId* = 11
  NanTagId* = 12
  FalseTagId* = 13
  TrueTagId* = 14
  AndTagId* = 15
  OrTagId* = 16
  NotTagId* = 17
  NegTagId* = 18
  SizeofTagId* = 19
  AlignofTagId* = 20
  OffsetofTagId* = 21
  OconstrTagId* = 22
  AconstrTagId* = 23
  KvTagId* = 24
  AddTagId* = 25
  SubTagId* = 26
  MulTagId* = 27
  DivTagId* = 28
  ModTagId* = 29
  ShrTagId* = 30
  ShlTagId* = 31
  BitandTagId* = 32
  BitorTagId* = 33
  BitxorTagId* = 34
  BitnotTagId* = 35
  EqTagId* = 36
  NeqTagId* = 37
  LeTagId* = 38
  LtTagId* = 39
  CastTagId* = 40
  ConvTagId* = 41
  CallTagId* = 42
  CmdTagId* = 43
  RangeTagId* = 44
  RangesTagId* = 45
  GvarTagId* = 46
  TvarTagId* = 47
  VarTagId* = 48
  ParamTagId* = 49
  ConstTagId* = 50
  ResultTagId* = 51
  LetTagId* = 52
  CursorTagId* = 53
  TypevarTagId* = 54
  EfldTagId* = 55
  FldTagId* = 56
  ProcTagId* = 57
  FuncTagId* = 58
  IteratorTagId* = 59
  ConverterTagId* = 60
  MethodTagId* = 61
  MacroTagId* = 62
  TemplateTagId* = 63
  TypeTagId* = 64
  BlockTagId* = 65
  ModuleTagId* = 66
  CchoiceTagId* = 67
  OchoiceTagId* = 68
  EmitTagId* = 69
  AsgnTagId* = 70
  ScopeTagId* = 71
  IfTagId* = 72
  WhenTagId* = 73
  ElifTagId* = 74
  ElseTagId* = 75
  TypevarsTagId* = 76
  BreakTagId* = 77
  ContinueTagId* = 78
  ForTagId* = 79
  WhileTagId* = 80
  CaseTagId* = 81
  OfTagId* = 82
  LabTagId* = 83
  JmpTagId* = 84
  RetTagId* = 85
  YldTagId* = 86
  StmtsTagId* = 87
  ParamsTagId* = 88
  UnionTagId* = 89
  ObjectTagId* = 90
  EnumTagId* = 91
  ProctypeTagId* = 92
  AtomicTagId* = 93
  RoTagId* = 94
  RestrictTagId* = 95
  ITagId* = 96
  UTagId* = 97
  FTagId* = 98
  CTagId* = 99
  BoolTagId* = 100
  VoidTagId* = 101
  PtrTagId* = 102
  ArrayTagId* = 103
  FlexarrayTagId* = 104
  AptrTagId* = 105
  CdeclTagId* = 106
  StdcallTagId* = 107
  SafecallTagId* = 108
  SyscallTagId* = 109
  FastcallTagId* = 110
  ThiscallTagId* = 111
  NoconvTagId* = 112
  MemberTagId* = 113
  InlineTagId* = 114
  NoinlineTagId* = 115
  AttrTagId* = 116
  VarargsTagId* = 117
  WasTagId* = 118
  SelectanyTagId* = 119
  PragmasTagId* = 120
  AlignTagId* = 121
  BitsTagId* = 122
  VectorTagId* = 123
  ImpTagId* = 124
  NodeclTagId* = 125
  InclTagId* = 126
  ExclTagId* = 127
  IncludeTagId* = 128
  ImportTagId* = 129
  FromTagId* = 130
  ImportexceptTagId* = 131
  ExportTagId* = 132
  CommentTagId* = 133
  DiscardTagId* = 134
  TryTagId* = 135
  RaiseTagId* = 136
  OnerrTagId* = 137
  RaisesTagId* = 138
  ErrsTagId* = 139
  StaticTagId* = 140
  IteTagId* = 141
  GraphTagId* = 142
  ForbindTagId* = 143
  KillTagId* = 144
  UnpackflatTagId* = 145
  UnpacktupTagId* = 146
  ExceptTagId* = 147
  FinTagId* = 148
  RefobjTagId* = 149
  PtrobjTagId* = 150
  TupleTagId* = 151
  OnumTagId* = 152
  RefTagId* = 153
  MutTagId* = 154
  OutTagId* = 155
  LentTagId* = 156
  SinkTagId* = 157
  NiltTagId* = 158
  ConceptTagId* = 159
  DistinctTagId* = 160
  ItertypeTagId* = 161
  RangetypeTagId* = 162
  UarrayTagId* = 163
  OpenarrayTagId* = 164
  SettTagId* = 165
  AutoTagId* = 166
  SymkindTagId* = 167
  TypekindTagId* = 168
  TypedescTagId* = 169
  UntypedTagId* = 170
  TypedTagId* = 171
  CstringTagId* = 172
  PointerTagId* = 173
  OrdinalTagId* = 174
  MagicTagId* = 175
  ImportcTagId* = 176
  ImportcppTagId* = 177
  ExportcTagId* = 178
  HeaderTagId* = 179
  ThreadvarTagId* = 180
  GlobalTagId* = 181
  DiscardableTagId* = 182
  NoreturnTagId* = 183
  BorrowTagId* = 184
  NoSideEffectTagId* = 185
  NodestroyTagId* = 186
  PluginTagId* = 187
  BycopyTagId* = 188
  ByrefTagId* = 189
  NoinitTagId* = 190
  RequiresTagId* = 191
  EnsuresTagId* = 192
  BuildTagId* = 193
  StringTagId* = 194
  QuotedTagId* = 195
  HderefTagId* = 196
  DdotTagId* = 197
  HaddrTagId* = 198
  NewoconstrTagId* = 199
  TupleconstrTagId* = 200
  SetTagId* = 201
  AshrTagId* = 202
  OconvTagId* = 203
  HconvTagId* = 204
  DconvTagId* = 205
  CallstrlitTagId* = 206
  InfixTagId* = 207
  PrefixTagId* = 208
  HcallTagId* = 209
  CompilesTagId* = 210
  DeclaredTagId* = 211
  DefinedTagId* = 212
  HighTagId* = 213
  LowTagId* = 214
  TypeofTagId* = 215
  UnpackTagId* = 216
  EnumtostrTagId* = 217
  IsmainmoduleTagId* = 218
  DefaultobjTagId* = 219
  DefaulttupTagId* = 220
  ExprTagId* = 221
  ArratTagId* = 222
  TupatTagId* = 223
  PlussetTagId* = 224
  MinussetTagId* = 225
  MulsetTagId* = 226
  XorsetTagId* = 227
  EqsetTagId* = 228
  LesetTagId* = 229
  LtsetTagId* = 230
  InsetTagId* = 231
  CardTagId* = 232
  EmoveTagId* = 233
  DestroyTagId* = 234
  DupTagId* = 235
  CopyTagId* = 236
  WasmovedTagId* = 237
  SinkhTagId* = 238
  TraceTagId* = 239
