#       Nimony
# (c) Copyright 2024 Andreas Rumpf
#
# See the file "license.txt", included in this
# distribution, for details about the copyright.

## Nimony index generator.

import std / [os, assertions, sets, hashes, tables, syncio]
include ".." / lib / nifprelude
include ".." / lib / compat2
import ".." / lib / nifreader as rd
from ".." / lib / nifcoreparse import parse
import ".." / lib / [nifindexes, symparser]
import decls, nimony_model, programs, semos
import ".." / models / nifindex_tags

proc getAttachedOp(symId: SymId, attackedOp: var AttachedOp): bool =
  var name = pool.syms[symId]
  extractBasename(name)

  attackedOp = case name
    of "=destroy": attachedDestroy
    of "=wasMoved": attachedWasMoved
    of "=trace": attachedTrace
    of "=copy": attachedCopy
    of "=sink": attachedSink
    of "=dup": attachedDup
    else: return false

  return true

proc buildIndexExports(exports: Table[string, HashSet[SymId]]; infile: string): TokenBuf =
  result = default(TokenBuf)
  let mp = splitModulePath infile
  if exports.len != 0:
    result = createTokenBuf(32)
    for suffix, syms in exports:
      # open NIF file to get the path of source file of the module from the line info.
      let modPath = mp.dir / (suffix & mp.ext)
      var fileId: lineinfos.FileId
      var r = rd.open(modPath)
      var mbuf = createTokenBuf()
      parse(r, mbuf)
      rd.close(r)
      var mn = beginRead(mbuf)
      if mn.isTagLit: inc mn      # into the stmts; first child carries the info
      fileId = pool.man.getFileId(mn.info)
      assert fileId.isValid
      let path = pool.files[fileId].toAbsolutePath
      result.addParLe(TagId(FromexportIdx))
      result.addStrLit(path, NoLineInfo)
      for s in syms:
        var isGlobal = false
        let ident = extractBasename(pool.syms[s], isGlobal)
        result.addIdent(ident, NoLineInfo)
      result.addParRi()

proc indexFromNif*(infile: string) =
  ## Extract index from `infile` Nif file and write it to `*.idx.nif` file.
  ##
  ## See https://github.com/nim-lang/nimony/issues/1162
  var r = rd.open(infile)
  var buf = createTokenBuf()
  parse(r, buf)
  rd.close(r)
  var n = beginRead buf
  let root = n.info
  var converterIndexMap = default seq[(SymId, SymId)]
  var exports = default Table[string, HashSet[SymId]]  # Module suffix -> symbols to export in the module

  n.into StmtsS:
    while n.hasMore:
      if n.isTagLit:
        case n.stmtKind:
        of ProcS, FuncS, ConverterS, MethodS:
          let kind = n.stmtKind
          let routine = takeRoutine(n, SkipFinalParRi)
          let symId = routine.name.symId
          if kind == ConverterS:
            if not routine.exported.isDotToken and
               routine.typevars.typeKind != InvokeT:
              # don't register instances and not exported ones
              let root = routine.retType.skipModifier.symId
              converterIndexMap.add((root, symId))
        of ExportS:
          # .nif files generated by `nim nif foo.nim` has `(exports symbol1, symbol2, ...)`, but doesn't have other kinds of export node.
          # export statement like `export modname` becomes `(exports symbols1, symbols2, ...)` where symbols1, symbols2, ... are exported symbols in the module.
          # So they are indexed only with `FromexportIdx`.
          n.into ExportS:
            while n.hasMore:
              assert n.isSymbol
              let sym = n.symId
              let name = pool.syms[sym]
              let suffix = extractModule(name)
              assert suffix != ""
              exports.mgetOrPut(suffix, default(HashSet[SymId])).incl sym
              inc n, AnyExpr
        else:
          skip n
      else:
        skip n


  var exportBuf = buildIndexExports(exports, infile)

  try:
    createIndex infile, root, true,
      IndexSections(
        converters: move converterIndexMap,
        exportBuf: exportBuf)
  except:
    quit "createIndex failed: " & infile
